# Literature

# The One-way Error Component Regression Model

## INTRODUCTION

A panel data regression differs from a regular time-series or cross-section regression in that it has a double subscript on its variables, i.e.

$$  y_{it}= \alpha + X_{it}^{'} \beta + u_{it}                      $$ $$ i=1, ... , N  ; t=1, ... ,T  $$ (2.1)

with \$ i \$ denoting households, individuals, firms, countries, etc. and t denoting time. The i subscript, therefore, denotes the cross-section dimension whereas t denotes the time-series dimension. $$ \alpha  $$ is a scalar, $$ \beta $$ is $$ K × 1 $$ and Xi t is the \$ it\_{th} \$ observation on K explanatory variables. Most of the panel data applications utilize a one-way error component model for the disturbances, with

$$ u_{it}= \mu_i +  v_{it}      $$ (2.2)

where μi denotes the unobservable individual-specific effect and νi t denotes the remainder disturbance. For example, in an earnings equation in labor economics, yi t will measure earnings of the head of the household, whereas $$ X_{it} $$ may contain a set of variables like experience, education, union membership, sex, race, etc. Note that μi is time-invariant and it accounts for any individual-specific effect that is not included in the regression. In this case we could think of it as the individual's unobserved ability. The remainder disturbance $$ v_{it} $$ varies with individuals and time and can be thought of as the usual disturbance in the regression. Alternatively, for a production function utilizing data on firms across time, $$ y_{it} $$ will measure output and $$ X_{it} $$ will measure inputs. The unobservable firm-specific effects will be captured by the $$ \mu_i $$ and we can think of these as the unobservable entrepreneurial or managerial skills of the firm's executives. Early applications of error components in economics include Kuh (1959) on investment, Mundlak (1961) and Hoch (1962) on production functions and Balestra and Nerlove (1966) on demand for natural gas. In vector form (2.1) can be written as

$$ y= \alpha i_{NT} + X \beta + u = Z \delta + u      $$ (2.3)

$$ y= \alpha i_{NT} + X \beta + u = Z \delta + u      $$ (2.3)

where \$ y \$ is \$ NT × 1 \$, \$ X \$ is \$ NT × K \$, \$ Z = [ι\_{NT} , X] \$, \$ \delta\^{'} = (α^{'},^\beta{'}) \$ and $ι_NT$ is a vector of ones of dimension NT. Also, (2.2) can be written as

$$ u=Z_\mu \mu +v  $$ (2.4)

$$  y_{it} = \alpha + X_{it}^{'} + U_{it}   $$ , \$ i=1,...,N ; t=1,...,T \$ with i denoting households, individuals, firms, countries, etc. and t denoting time. The i subscript, therefore, denotes the cross-section dimension whereas t denotes the time-series dimension. \$ \alpha \$ is a scalar, \$ \beta \$ is \$ K × 1 \$ and \$X\_{it} \$is the \$ it\^{th} \$ observation on K explanatory variables. disturbances, with it $$ u_{it}=u_i  + v_{it}     $$

where μi denotes the unobservable individual-specific effect and $ν{it}$ denotes the remainder disturbance. For example, in an earnings equation in labor economics, $y_{it}$ will measure earnings of the head of the household, whereas Xi t may contain a set of variables like experience, education, union membership, sex, race, etc. Note that μi is time-invariant and it accounts for any individual-specific effect that is not included in the regression. In this case we could think of it as the individual's unobserved ability. The remainder disturbance \$ ν{it} \$ varies with individuals and time and can be thought of as the usual disturbance in the regression. Alternatively, for a production function utilizing data on firms across time, \$ y\_{it} \$ will measure output and \$ X\_{it} \$ will measure inputs. The unobservable firm-specific effects will be captured by the \$ \mu\_i \$ and we can think of these as the unobservable entrepreneurial or managerial skills of the firm's executives. Early applications of error components in economics include Kuh (1959) on investment, Mundlak (1961) and Hoch (1962) on production functions and Balestra and Nerlove (1966) on demand for natural gas. In vector form (2.1) can be written as

$$ y= \alpha i_{NT}  + X\beta +u = Z\delta + u $$

where $y$ is \$ NT × 1\$ , X is $NT × K$ , \$ Z = [i\_{NT} , X] \$ , \$ \delta^{'}=(^\alpha{'},\beta\^{'})\$ and $i_{NT}$ is a vector of ones of dimension $NT$ . Also, (2.2) can be written as

$$ u=Z_\mu \mu  + v$$ (2.4)

where \$ u\^{'} = (u\_{11}, . . . , u\_{1T} , u\_{21}, . . . , u\_{2T}, . . . , u\_{N1}, . . . , u\_{NT} ) \$ with the observations stacked such that the slower index is over individuals and the faster index is over time.\$ Z\_\mu = IN \otimes ιT \$ where IN is an identity matrix of dimension N, ιT is a vector of ones of dimension T and \$ \otimes \$ denotes Kronecker product. \$ Z\_\mu \$ is a selector matrix of ones and zeros, or simply the matrix of individual dummies that one may include in the regression to estimate theμi if they are assumed to be fixed parameters. \$ \mu\^{'} = (\mu\_1, . . . , \mu\_N )\$ and $ν^{'} = (ν11, . . . , ν_{1T} , . . . , ν_{N1}, . . . , ν_{NT} )$. Note that \$Z\_\mu Z\^{'}\mu = I_N \otimes J_T \$ where $J_T$ is a matrix of ones of dimension T and \$ P = Zμ(Z^{'}^\mu Z\mu){−1} Z\^{'}\mu \$ , the projectionmatrix on \$ Z\_\mu \$ , reduces to \$ IN \otimes J_T \$ where \$J \_T= JT /T \$ . P is a matrix which averages the observation across time for each individual, and Q = INT − P is a matrix which obtains the deviations from individual means. For example, regressing y on the matrix of dummy variables $Z_μ$ gets the predicted values \$ P_y \$ which has a typical element

$$ \bar y_i = \sum_{t=1}^T \frac{y_{it}}{T}  $$ repeated T times for each individual. The residuals of this regression are given by Qy which has a typical element $$ (y_{it} - \bar y _{i.} ) $$ P and Q are (i) symmetric idempotent matrices, i.e.

$P^{'} = P$ and \$ P\^2 = P \$. This means that $rank(P) = tr(P) = N$ and $rank(Q) = tr(Q) = N(T − 1)$ . This uses the result that the rank of an idempotent matrix is equal to its trace (see Graybill, 1961,theorem 1.63). Also, (ii) P and Q are orthogonal, i.e. \$PQ=0 \$ and (iii) they sum to the identity matrix $P + Q = I_{NT}$. In fact, any two of these properties imply the third (see Graybill, 1961, theorem 1.68).

## THE FIXED EFFECTS MODEL

In this case, the μi are assumed to be fixed parameters to be estimated and the remainder disturbances stochastic with $v_{it}$ independent and identically distributed $IID(0,\sigma_v^2)$. The $X_{it}$ are assumed independent of the $v_{it}$ for all i and t. The fixed effects model is an appropriate specification if we are focusing on a specific set of N firms, say, IBM, GE,Westinghouse, etc. and our inference is restricted to the behavior of these sets of firms. Alternatively, it could be a set of N OECD countries, or N American states. Inference in this case is conditional on the particular N firms, countries or states that are observed. One can substitute the disturbances given by (2.4) into (2.3) to get

\$ y=\alpha i\_{IT} + X\beta + Z\_\mu \mu +v = Z\delta + Z\_\mu \mu +v \$ (2.5)

and then perform ordinary least squares (OLS) on (2.5) to get estimates of \$ \alpha,\beta  and  µ \$

Note that Z is \$ NT \times (K+1)\$ and $Z_µ$ , the matrix of individual dummies, is\$NT \times N \$ NT × N. If N is large, (2.5) will include too many individual dummies, and the matrix to be inverted by OLS is large and of dimension $(N + K)$. In fact, since α and β are the parameters of interest, one can obtain the LSDV (least squares dummy variables) estimator from (2.5), by premultiplying the model by Q and performing OLS on the resulting transformed model:

\$ Qy=QX\beta + Qv\$ (2.6)

This uses the fact that $QZ_\mu =Qi_{NT}=0$ , since $PZ_\mu =Z_\mu$ the Q matrix wipes out the individual effects. This is a regression of $\tilde y =QY$ with element $(y_{it} - \bar y _{i.} )$ on $\check X=QX$ with typical element

$$
\widetilde{\beta}=\left(X^{\prime} Q X\right)^{-1} X^{\prime} Q y
$$\
(2.7) with $\operatorname{var}(\widetilde{\beta})=\sigma_{v}^{2}\left(X^{\prime} Q X\right)^{-1}=\sigma_{v}^{2}\left(\widetilde{X}^{\prime} \tilde{X}\right)^{-1}$ . $\widetilde{\beta}$ could have been obtained from (2.5) using results on partitioned inverse or the Frisch--Waugh--Lovell theorem discussed in Davidson and MacKinnon (1993, p. 19). This uses the fact that P is the projection matrix on $Z_{\mu}$ and $Q = I_{NT} − P$ (see problem 2.1). In addition, generalized least squares (GLS) on (2.6), using the generalized inverse, will also yield $\widetilde{\beta }$ (see problem 2.2).

Note that for the simple regression $$y_{it}=\beta x_{it}+ \mu_i+ v_i     $$ (2.8)

and averaging over time gives $$  \bar {y}_{i.}= \beta \bar{x}_{i.}+ \mu_i+ \bar{v}_i   $$ (2.9)

Therefore, subtracting (2.9) from (2.8) gives $$y_{it}-\bar{y}_{i.}=\beta (x_{it}-\bar{x}_{i.}) + (v_{it}-\bar{v}_{i.})   $$ (2.10)

Also, averaging across all observations in (2.8) gives $$\bar{y}_{..}=\alpha + \beta \bar{x}_{..} + \bar{v}_{..} $$ (2.11)i =0where we utilized the restriction that \$\sum*{i=1}\^{n}* \mu{i}=0 \$ This is an arbitrary restriction on the dummy variable coefficients to avoid the dummy variable trap, or perfect multicollinearity; see Suits (1984) for alternative formulations of this restriction. In fact only $\beta$ and \$ (\alpha + \mu*{i})\$ are estimable from (2.8), and not α and μi separately, unless a restriction like* $$\sum_{i=1}^{n} \mu_{i}=0 $$ is imposed. In this case, $\widetilde {\beta}$ is obtained from regression (2.10), $$\widetilde {\alpha}= \bar {y}_{..}-\widetilde {\beta} \bar{x}_{..} $$ can be recovered from (2.11) and $$\widetilde {\mu}_{i}=\bar{y}_{i.}- \widetilde {\alpha} - \widetilde {\beta} \bar{X}_{i.} $$ from (2.9). For large labor or consumer panels, where N is very large,regressions like (2.5) may not be feasible, since one is including (N − 1) dummies in the regression. This fixed effects (FE) least squares, also known as least squares dummy variables (LSDV), suffers from a large loss of degrees of freedom. We are estimating (N − 1) extra parameters, and too many dummies may aggravate the problem of multicollinearity among the regressors. In addition, this FE estimator cannot estimate the effect of any time-invariant variable like sex, race, religion, schooling or union participation. These time-invariant variables are wiped out by the Q transformation, the deviations from means transformation (see (2.10)). Alternatively, one can see that these time-invariant variables are spanned by the individual dummies in (2.5) and therefore any regression package attempting (2.5) will fail, signaling perfect multicollinearity. If (2.5) is the true model, LSDV is the best linear unbiased estimator (BLUE) as long as $v_{it}$ is the standard classical disturbance with mean 0 and variance--covariance matrix \$\sigma {v}\^{2} I\_{NT} \$ . Note that as $T \rightarrow \infty$ the FE estimator is consistent. However, if T is fixed and $N \rightarrow \infty$ as is typical in short labor panels, then only the FE estimator of β is consistent; the FE estimators of the individual effects $\alpha + \mu_{i}$ are not consistent since the number of these parameters increases as N increases. This is the incidental parameter problem discussed by Neyman and Scott (1948) and reviewed more recently by Lancaster (2000). Note that when the true model is fixed effects as in (2.5), OLS on (2.1) yields biased and inconsistent estimates of the regression parameters. This is an omission variables bias due to the fact that OLS deletes the individual dummies when in fact they are relevant.

(1) *Testing for fixed effects.* One could test the joint significance of these dummies, i.e. H0; $\mu_{1}=\mu_{2}= ... = \mu_{N-1}=0$ , by performing an F-test. (Testing for individual effects will be treated extensively in Chapter 4.) This is a simple Chow test with the restricted residual sums of squares (RRSS) being that of OLS on the pooled model and the unrestricted residual sums of squares (URSS) being that of the LSDV regression. If N is large, one can perform the Within transformation and use that residual sum of squares as the URSS. In this case

$$F_{0}=    \frac{ \dfrac{RRSS-URSS}{N-1}}{\dfrac{URSS}{NT-N-K} } \sim  F_{N-1,N(T-1)-K}           $$ (2.12)

(2) *Computational warning.* One computational caution for those using theWithin regression given by (2.10). The $s^{2}$ f this regression as obtained from a typical regression package divides the residual sums of squares by NT − K since the intercept and the dummies are not included. The proper $s^{2}$ , say $s^{*2}$ from the LSDV regression in (2.5), would divide the same residual sums of squares by $N(T − 1) − K$ . Therefore, one has to adjust the variances obtained from the Within regression (2.10) by multiplying the variance--covariance matrix by $$\frac{s^{2}}{s^{*2}} $$ or simply by multiplying by $[NT − K]/[N(T − 1) − K]$

(3) *Robust estimates of the standard errors.* For the Within estimator, Arellano (1987) suggests a simple method for obtaining robust estimates of the standard errors that allow for a general variance--covariance matrix on the $v_{it}$ as in White (1980). One would stack the panel as an equation for each individual: $$y_{i}= Z_{i} \delta + \mu i_{it} + v_{i} $$ (2.13)

where $y_i$ is T × \$Z_i =[l_T,X_i] \$, $X_i$ is T × K, $\mu _i$ is a scalar, $\delta ^{\prime} = (\alpha, \beta^{\prime} )$ , $i_T$ is a vector of ones of dimension T and $v_i$ is T x 1 . In general, $E(v_i,v_i^{\prime}) = \Omega _ i$ for i = 1, 2, . . . , N, where $\Omega _i$ is a positive definite matrix of dimension T . We still assume $E(v_i,v_j^{\prime}) =0$ for $i \ne j$ T is assumed small and N large as in household or company panels, and the asymptotic results are performed for $N \rightarrow \infty$ and T fixed. Performing the Within transformation on this set of equations (2.13) one gets

$$  \widetilde {y}_i=\widetilde{X}_{i} \beta + \widetilde{v}_{i}  $$ (2.14)

where $$\widetilde{y}=Qy $$ , $$\widetilde{X}=QX $$ and $$\widetilde{v}=Qv $$ , with $$\widetilde{y}=(\widetilde{y}_1^{\prime}, ...,\widetilde{y}_N^{\prime} )^{\prime} $$ and $$\widetilde{y}_i=(I_T-\bar{J}_T) y_i $$ Computing robust least squares on this system, as described by White (1980), under the restriction that each equation has the same $\beta$ one gets the Within estimator of β which has the following asymptotic distribution:

$$N^{\frac{1}{2} }  (\widetilde{\beta}- \beta ) \sim N(0,M^{-1}VM^{-1} ) $$ (2.15)

where $$M=\frac{ p\lim(\widetilde{X}^{\prime} \widetilde{X})} {N} $$ Note that $$\widetilde{X}_i=(I_T - \bar{J}_T) X_i  $$ and $$\widetilde{X}^{\prime} diag[\Omega_i] Q \widetilde{X} $$ (see problem 2.3). In this case, V is estimated by $$ \frac{  \widetilde{V}=\sum_{i=1}^{N} \widetilde{X}_i^{\prime}\widetilde{u}_i \widetilde{u}_i^{\prime}\widetilde{X}_i^{\prime} } {N}  $$ where $$\widetilde{u}_i=\widetilde{y}_i- \widetilde{X}_i \widetilde{\beta}_i$$ . Therefore, the robust asymptotic variance-- covariance matrix of $\beta$ is estimated by $$
\operatorname{var}(\widetilde{\beta})=\left(\widetilde{X}^{\prime} \tilde{X}\right)^{-1}\left[\sum_{i=1}^{N} \widetilde{X}_{i}^{\prime} \tilde{u}_{i} \tilde{u}_{i}^{\prime} \widetilde{X}_{i}\right]\left(\widetilde{X}^{\prime} \tilde{X}\right)^{-1}
$$

## THE RANDOM EFFECTS MODEL

There are too many parameters in the fixed effects model and the loss of degrees of freedom can be avoided if the μi can be assumed random. In this case \$ \mu*i* \sim IID(0, \sigma\mu\^2)\$, \$ν\_{it} ∼ IID(0, \sigma\_v\^2 ) \$ and the $\mu_i$ are independent of the $v_{it}$ . In addition, the $X_{it}$ are independent of the $\mu_i$ and $v_{it}$,for all i and t. The random effects model is an appropriate specification if we are drawing N individuals randomly from a large population. This is usually the case for household panel studies. Care is taken in the design of the panel to make it "representative" of the population we are trying to make inferences about. In this case, N is usually large and a fixed effects model would lead to an enormous loss of degrees of freedom. The individual effect is characterized as random and inference pertains to the population from which this sample was randomly drawn.

But what is the population in this case? Nerlove and Balestra (1996) emphasize Haavelmo's (1944) view that the population "consists not of an infinity of individuals, in general, but of an infinity of decisions" that each individual might make. This view is consistent with a random effects specification. From (2.4), one can compute the variance--covariance matrix

```{=tex}
\begin{equation}
\begin{aligned}
\Omega &=E\left(u u^{\prime}\right)=Z_{\mu} E\left(\mu \mu^{\prime}\right) Z_{\mu}^{\prime}+E\left(v v^{\prime}\right) \\
&=\sigma_{\mu}^{2}\left(I_{N} \otimes J_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes I_{T}\right)
\end{aligned}
\end{equation}
```
This implies a homoskedastic variance $\operatorname{var}\left(u_{i t}\right)=\sigma_{\mu}^{2}+\sigma_{v}^{2} \mathrm{f}$ for all i and t, and an equicorrelated block-diagonal covariance matrix which exhibits serial correlation over time only between the disturbances of the same individual. In fact,

$\begin{aligned} \operatorname{cov}\left(u_{i t}, u_{j s}\right) &=\sigma_{\mu}^{2}+\sigma_{v}^{2} & \text { for } \quad i=j, t=s \\ &=\sigma_{\mu}^{2} & \text { for } i=j, t \neq s \end{aligned}$

and zero otherwise. This also means that the correlation coefficient between $\mu _{it}$ and $\mu _{js}$ is $\begin{aligned} \rho=\operatorname{correl}\left(u_{i t}, u_{j s}\right) &=1 & & \text { for } i=j, t=s \\ &=\sigma_{\mu}^{2} /\left(\sigma_{\mu}^{2}+\sigma_{v}^{2}\right) & \text { for } i=j, t \neq s \end{aligned}$

and zero otherwise. In order to obtain the GLS estimator of the regression coefficients, we need \$\Omega \^{-1} \$. This is a huge matrix for typical panels and is of dimension $NT × NT$. No brute force inversion should be attempted even if the researcher's application has a small N and T .1 We will follow a simple trick devised by Wansbeek and Kapteyn (1982b, 1983) that allows the derivation of \$\Omega \^{-1} \$ ans $\Omega^{-1 / 2}$ Essentially, one replaces $J_{T}$ by $T \bar{J}_{T}$ and $I_{T}$ by $\left(E_{T}+\bar{J}_{T}\right)$ where $E_T$ is by definition $\left(I_{T}-\bar{J}_{T}\right)$ . In this case

$\Omega=T \sigma_{\mu}^{2}\left(I_{N} \otimes \bar{J}_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes E_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes \bar{J}_{T}\right)$

Collecting terms with the same matrices, we get \begin{equation}
\Omega=\left(T \sigma_{\mu}^{2}+\sigma_{v}^{2}\right)\left(I_{N} \otimes \bar{J}_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes E_{T}\right)=\sigma_{1}^{2} P+\sigma_{v}^{2} Q
\end{equation}

where $\sigma_{1}^{2}=T \sigma_{\mu}^{2}+\sigma_{v}^{2}$ . (2.18) is the spectral decomposition representation of $\Omega$, with $\sigma_1^2$ being the first unique characteristic root of$\Omega$ of multiplicity $N(T − 1)$. It is easy to verify, using the properties of P and Q, that

\begin{equation}
\Omega^{-1}=\frac{1}{\sigma_{1}^{2}} P+\frac{1}{\sigma_{v}^{2}} Q
\end{equation} and \begin{equation}
\Omega^{-1 / 2}=\frac{1}{\sigma_{1}} P+\frac{1}{\sigma_{v}} Q
\end{equation}

In fact, $\Omega^{r}=\left(\sigma_{1}^{2}\right)^{r} P+\left(\sigma_{v}^{2}\right)^{r} Q$ where r is an arbitrary scalar. Now we can obtain GLS as a weighted least squares. Fuller and Battese (1973, 1974) suggested premultiplying the regression equation given in (2.3) by $\sigma_{v} \Omega^{-1 / 2}=Q+\left(\sigma_{v} / \sigma_{1}\right) P$ and performing OLS on the resulting transformed regression. In this case, $y^{*}=\sigma_{v} \Omega^{-1 / 2} y$ has a typical element $y_{i t}-\theta \bar{y}_{i .}$ where $\theta=1-\left(\sigma_{v} / \sigma_{1}\right)$ (see problem 2.4). This transformed regression inverts a matrix of dimension $(K + 1)$ and can easily be implemented using any regression package.

The best quadratic unbiased (BQU) estimators of the variance components arise naturally from the spectral decomposition of $\Omega$ . In fact, $P u \sim\left(0, \sigma_{1}^{2} P\right)$ and $Q u \sim\left(0, \sigma_{v}^{2} Q\right)$ and

\begin{equation}
\widehat{\sigma}_{1}^{2}=\frac{u^{\prime} P u}{\operatorname{tr}(P)}=T \sum_{i=1}^{N} \bar{u}_{i .}^{2} / N
\end{equation} and

```{=tex}
\begin{equation}
\widehat{\sigma}_{v}^{2}=\frac{u^{\prime} Q u}{\operatorname{tr}(Q)}=\frac{\sum_{i=1}^{N} \sum_{t=1}^{T}\left(u_{i t}-\bar{u}_{i .}\right)^{2}}{N(T-1)}
\end{equation}
```
provide the BQU estimators of $\sigma_1^2$ and$\sigma_v^2$ , respectively (see problem 2.5).

These are analyses of variance-type estimators of the variance components and are minimum variance-unbiased under normality of the disturbances (see Graybill, 1961). The true disturbances are not known and therefore (2.21) and (2.22) are not feasible. Wallace and Hussain (1969) suggest substituting OLS residual $\widehat{u}_{\mathrm{OLS}}$ instead of the true u. After all, under the random effects model, the OLS estimates are still unbiased and consistent, but no longer efficient. Amemiya (1971) shows that these estimators of the variance components have a different asymptotic distribution from that knowing the true disturbances. He suggests using the LSDV residuals instead of the OLS residuals. In this case $\tilde{u}=y-\tilde{\alpha} \iota_{N T}-X \widetilde{\beta}$ where and $\bar{X}_{. .}^{\prime}$ is a $1 \times K$

vector of averages of all regressors. Substituting these $\hat{u}$ for u in (2.21) and (2.22) we get the Amemiya-type estimators of the variance components. The resulting estimates of the variance components have the same asymptotic distribution as that knowing the true disturbances:

\begin{equation}
\left(\begin{array}{c}
\sqrt{N T}\left(\widehat{\sigma}_{v}^{2}-\sigma_{v}^{2}\right) \\
\sqrt{N}\left(\widehat{\sigma}_{\mu}^{2}-\sigma_{\mu}^{2}\right)
\end{array}\right) \sim N\left(0,\left(\begin{array}{cc}
2 \sigma_{v}^{4} & 0 \\
0 & 2 \sigma_{\mu}^{4}
\end{array}\right)\right)
\end{equation}

where $\widehat{\sigma}_{\mu}^{2}=\left(\widehat{\sigma}_{1}^{2}-\widehat{\sigma}_{v}^{2}\right) / T .^{3}$

Swamy and Arora (1972) suggest running two regressions to get estimates of the variance components from the corresponding mean square errors of these regressions. The first regression is the Within regression, given in (2.10), which yields the following $s^2$:


\begin{equation}
\widehat{\sigma}_{v}^{2}=\left[y^{\prime} Q y-y^{\prime} Q X\left(X^{\prime} Q X\right)^{-1} X^{\prime} Q y\right] /[N(T-1)-K]
\end{equation}

The second regression is the Between regression which runs the regression of averages across time, i.e.


\begin{equation}
\bar{y}_{i .}=\alpha+\bar{X}_{i .}^{\prime} \beta+\bar{u}_{i .} \quad i=1, \ldots, N
\end{equation}

(2.25)

This is equivalent to premultiplying the model in (2.5) by P and running OLS. The only caution is that the latter regression has NT observations because it repeats the averages T times for each individual, while the cross-section regression in (2.25) is based on N observations. To remedy this, one can run the cross-section regression

\begin{equation}
\sqrt{T} \bar{y}_{i .}=\alpha \sqrt{T}+\sqrt{T} \bar{X}_{i .}^{\prime} \beta+\sqrt{T} \bar{u}_{i .}
\end{equation} (2.26)

where one can easily verify that $\operatorname{var}\left(\sqrt{T} \bar{u}_{i .}\right)=\sigma_{1}^{2} .$ This regression will yield an $s^{2}$ given by

\begin{equation}
\widehat{\sigma}_{1}^{2}=\left(y^{\prime} P y-y^{\prime} P Z\left(Z^{\prime} P Z\right)^{-1} Z^{\prime} P y\right) /(N-K-1)
\end{equation} (2.27)

Note that stacking the following two transformed regressions we just performed yields \begin{equation}
\left(\begin{array}{l}
Q y \\
P y
\end{array}\right)=\left(\begin{array}{l}
Q Z \\
P Z
\end{array}\right) \delta+\left(\begin{array}{c}
Q u \\
P u
\end{array}\right)
\end{equation} (2.28)

and the transformed error has mean 0 and variance--covariance matrix given by

$$
\left(\begin{array}{cc}
\sigma_{v}^{2} Q & 0 \\
0 & \sigma_{1}^{2} P
\end{array}\right)
$$

Problem 2.7 asks the reader to verify that OLS on this system of 2NT observations yields OLS on the pooled model (2.3). Also, GLS on this system yields GLS on (2.3). Alternatively, one could get rid of the constant α by running the following stacked regressions:

\begin{equation}
\left(\begin{array}{c}
Q y \\
\left(P-\bar{J}_{N T}\right) y
\end{array}\right)=\left(\begin{array}{c}
Q X \\
\left(P-\bar{J}_{N T}\right) X
\end{array}\right) \beta+\left(\begin{array}{c}
Q u \\
\left(P-\bar{J}_{N T}\right) u
\end{array}\right)
\end{equation} (2.29)

This follows from the fact that QιNT = 0 and (P − J¯NT )ιNT = 0. The transformed error has zero mean and variance--covariance matrix $$
\left(\begin{array}{cc}
\sigma_{v}^{2} Q & 0 \\
0 & \sigma_{1}^{2}\left(P-\bar{J}_{N T}\right)
\end{array}\right)
$$ OLS on this system yields OLS on (2.3) and GLS on (2.29) yields GLS on (2.3). In fact, \begin{equation}
\begin{aligned}
\widehat{\beta}_{\mathrm{GLS}}=&\left[\left(X^{\prime} Q X / \sigma_{v}^{2}\right)+X^{\prime}\left(P-\bar{J}_{N T}\right) X / \sigma_{1}^{2}\right]^{-1}\left[\left(X^{\prime} Q y / \sigma_{v}^{2}\right)\right.\\
&\left.+X^{\prime}\left(P-\bar{J}_{N T}\right) y / \sigma_{1}^{2}\right] \\
=&\left[W_{X X}+\phi^{2} B_{X X}\right]^{-1}\left[W_{X y}+\phi^{2} B_{X y}\right]
\end{aligned}
\end{equation} (2.30)

with $\operatorname{var}\left(\widehat{\beta}_{\mathrm{GLS}}\right)=\sigma_{v}^{2}\left[W_{X X}+\phi^{2} B_{X X}\right]^{-1} .$ Note that $W_{X X}=X^{\prime} Q X, B_{X X}=X^{\prime}\left(P-\bar{J}_{N T}\right) X$ and $\phi^{2}=\sigma_{v}^{2} / \sigma_{1}^{2}$. Also, the Within estimator of $\beta$ is $\underline{\beta}_{\text {Within }}=W_{X X}^{-1} W_{X y}$ and the Between estimator of $\beta$ is $\widehat{\beta}_{\text {Between }}=B_{X X}^{-1} B_{X y} .$ This shows that $\widehat{\beta}_{\mathrm{GLS}}$ is a matrix weighted average of $\widetilde{\beta}_{\text {Within and }} \widehat{\beta}_{\text {Between }}$ weighing each estimate by the inverse of its corresponding variance. In fact

\begin{equation}
\widehat{\beta}_{\mathrm{GLS}}=W_{1} \widetilde{\beta}_{\mathrm{Within}}+W_{2} \widehat{\beta}_{\mathrm{Between}}
\end{equation} (2.31) where $$
W_{1}=\left[W_{X X}+\phi^{2} B_{X X}\right]^{-1} W_{X X}
$$ and $$
W_{2}=\left[W_{X X}+\phi^{2} B_{X X}\right]^{-1}\left(\phi^{2} B_{X X}\right)=I-W_{1}
$$ This was demonstrated by Maddala (1971). Note that (i) if $\sigma_{\mu}^{2}=0$ then $\phi^{2}=1$ and $\widehat{\beta}_{\text {GLS }}$ reduces to $\widehat{\beta}_{\text {OLs. }}$ (ii) If $T \rightarrow \infty$, then $\phi^{2} \rightarrow 0$ and $\widehat{\beta}_{\text {GLS }}$ tends to $\widetilde{\beta}_{\text {Within. }}$ Also, if $W_{X X}$ is huge compared to $B_{X X}$ then $\widehat{\beta}_{\mathrm{GLS}}$ will be close to $\widetilde{\beta}_{\text {Within }}$. However, if $B_{X X}$ dominates $W_{X X}$ then $\widehat{\beta}_{\mathrm{GLS}}$ tends to $\widehat{\beta}_{\text {Between. }}$ In other words, the Within estimator ignores the Between variation, and the Between estimator ignores the Within variation. The OLS estimator gives equal weight to the Between and Within variations. From $(2.30)$, it is clear that $\operatorname{var}\left(\widetilde{\beta}_{\text {Within }}\right)-\operatorname{var}\left(\hat{\beta}_{\mathrm{GLS}}\right)$ is a positive semidefinite matrix, since $\phi^{2}$ is positive. However, as $T \rightarrow \infty$ for any fixed $N, \phi^{2} \rightarrow 0$ and both $\widehat{\beta}_{\mathrm{GLS}}$ and $\widetilde{\beta}_{\text {Within }}$ have the same asymptotic variance.

Another estimator of the variance components was suggested by Nerlove (1971a). His zuggestion is to estimate $\sigma^{2}$ as $\sum^{N} \cdot(\widehat{u} \cdot-\widehat{\pi})^{2} /(N-1)$ where $\widehat{u}$. are the dummv coefficients estimates from the LSDV regression. $\sigma_{v}^{2}$ is estimated from the Within residual sums of squares divided by $N T$ without correction for degrees of freedom. ${ }^{4}$

Note that, except for Nerlove's (1971a) method, one has to retrieve $\widehat{\sigma}_{\mu}^{2}$ as $\left(\widehat{\sigma}_{1}^{2}-\widehat{\sigma}_{v}^{2}\right) / T .$ In this case, there is no guarantee that the estimate of $\widehat{\sigma}_{\mu}^{2}$ would be nonnegative. Searle (1971) has an extensive discussion of the problem of negative estimates of the variance components in the biometrics literature. One solution is to replace these negative estimates by zero. This in fact is the suggestion of the Monte Carlo study by Maddala and Mount (1973). This study finds that negative estimates occurred only when the true $\sigma_{\mu}^{2}$ was small and close to zero. In these cases OLS is still a viable estimator. Therefore, replacing negative $\widehat{\sigma}_{\mu}^{2}$ by zero is not a bad sin after all, and the problem is dismissed as not being serious. ${ }^{5}$

How about the properties of the various feasible GLS estimators of $\beta$ Under the random effects model, GLS based on the true variance components is BLUE, and all the feasible GLS estimators considered are asymptotically efficient as either N or \$N \rightarrow \infty \$. Maddala and Mount (1973) compared OLS, Within, Between, feasible GLS methods, MINQUE, Henderson's method III, true GLS and maximum likelihood estimation using their Monte Carlo study. They found little to choose among the various feasible GLS estimators in small samples and argued in favor of methods that were easier to compute. MINQUE was dismissed as more difficult to compute and the applied researcher given one shot at the data was warned to compute at least two methods of estimation, like an ANOVA feasible GLS and maximum likelihood to ensure that they do not yield drastically different results. If they do give different results, the authors diagnose misspecification.

Taylor (1980) derived exact finite sample results for the one-way error component model. He compared the Within estimator with the Swamy--Arora feasible GLS estimator. He found the following important results:

(1) Feasible GLS is more efficient than LSDV for all but the fewest degrees of freedom.
(2) The variance of feasible GLS is never more than 17% above the Cramer--Rao lower bound.
(3) More efficient estimators of the variance components do not necessarily yield more efficient feasible GLS estimators.

These finite sample results are confirmed by the Monte Carlo experiments carried out by Maddala and Mount (1973) and Baltagi (1981a).

Bellmann, Breitung and Wagner (1989) consider the bias in estimating the variance components using the Wallace and Hussain (1969) method due to the replacement of the true disturbances by OLS residuals, also the bias in the regression coefficients due to the use of estimated variance components rather than the true variance components. The magnitude of this bias is estimated using bootstrap methods for two economic applications. The first application relates product innovations, import pressure and factor inputs using a panel at the industry level. The second application estimates the earnings of 936 full-time working German males based on the first and second wave of the German Socio-Economic Panel. Only the first application revealed considerable bias in estimating \$\sigma\_\mu\^2 \$. However, this did not affect the bias much in the corresponding regression coefficients

### Fixed vs Random

Having discussed the fixed effects and the random effects models and the assumptions underlying them, the reader is left with the daunting question, which one to choose? This is not as easy a choice as it might seem. In fact, the fixed versus random effects issue has generated a hot debate in the biometrics and statistics literature which has spilled over into the panel data econometrics literature. Mundlak (1961) and Wallace and Hussain (1969) were early proponents of the fixed effects model and Balestra and Nerlove (1966) were advocates of the random error component model. In Chapter 4, we will study a specification test proposed by Hausman (1978) which is based on the difference between the fixed and random effects estimators. Unfortunately, applied researchers have interpreted a rejection as an adoption of the fixed effects model and nonrejection as an adoption of the random effects model.6 Chamberlain (1984) showed that the fixed effects model imposes testable restrictions on the parameters of the reduced form model and one should check the validity of these restrictions before adopting the fixed effects model (see Chapter 4). Mundlak (1978) argued that the random effects model assumes exogeneity of all the regressors with the random individual effects. In contrast, the fixed effects model allows for endogeneity of all the regressors with these individual effects. So, it is an "all" or "nothing" choice of exogeneity of the regressors and the individual effects, see Chapter 7 for a more formal discussion of this subject.

Hausman and Taylor (1981) allowed for some of the regressors to be correlated with the individual effects, as opposed to the all or nothing choice. These over-identification restrictions are testable using a Hausman-type test (see Chapter 7). For the applied researcher, performing fixed effects and random effects and the associated Hausman test reported in standard packages like Stata, LIMDEP, TSP, etc., the message is clear: Do not stop here. Test the restrictions implied by the fixed effects model derived by Chamberlain (1984) (see Chapter 4) and check whether a Hausman and Taylor (1981) specification might be a viable alternative (see Chapter 7).

# The Two-way Error Component Regression Model

## NTRODUCTION

Wallace and Hussain (1969), Nerlove (1971b) and Amemiya (1971), among others, the regression model given by (2.1), but with two-way error components disturbances: \begin{equation}
u_{i t}=\mu_{i}+\lambda_{t}+v_{i t} \quad i=1, \ldots, N ; t=1, \ldots, T
\end{equation} (3.1)

where $\mu_i$ denotes the unobservable individual effect discussed in Chapter 2, $\lambda_t$ denotes the unobservable time effect and $v_{it}$ is the remainder stochastic disturbance term. Note that $\lambda_t$ is individual-invariant and it accounts for any time-specific effect that is not included in the regression. For example, it could account for strike year effects that disrupt production; oil embargo effects that disrupt the supply of oil and affect its price; Surgeon General reports on the ill-effects of smoking, or government laws restricting smoking in public places, all of which could affect consumption behavior. In vector form, (3.1) can be written as

\begin{equation}
u=Z_{\mu} \mu+Z_{\lambda} \lambda+v
\end{equation} (3.2)

where $Z_\mu, \mu$ and $v$ were defined earlier. $Z_\lambda = i_N \otimes I_T$ is the matrix of time dummies that one may include in the regression to estimate the $\lambda_t$ if they are fixed parameters, and $\lambda^{\prime}= (\lambda_1, ..., \lambda_T )$ Note that $$Z_\lambda Z_\lambda^ {\prime}=J_N \otimes I_T $$ and the projection on $Z_{\lambda}$ is $$Z_{\lambda}\left(Z_{\lambda}^{\prime} Z_{\lambda}\right)^{-1} Z_{\lambda}^{\prime}=\bar{J}_{N} \otimes I_T  $$ This last matrix averages the data over individuals, i.e., if we regress y on $Z_\lambda$, the predicted values are given by $$ (\bar {J_N} \otimes I_T)y $$ which has typical element $\bar{y}_{. t}=\sum_{i=1}^{N} y_{i t} / N$ .

## THE FIXED EFFECTS MODEL

If the $\mu_{i}$ and $\lambda_{t}$ are assumed to be fixed parameters to be estimated and the remainder disturbances stochastic with $v_{i t} \sim \operatorname{IID}\left(0, \sigma_{v}^{2}\right)$, then (3.1) represents a two-way fixed effects error component model. The $X_{i t}$ are assumed independent of the $v_{i t}$ for all $i$ and $t$. Inference in this case is conditional on the particular $N$ individuals and over the specific time periods observed. Recall that $Z_{\lambda}$, the matrix of time dummies, is $N T \times T$. If $N$ or $T$ is large, there will be too many dummy variables in the regression $\{(N-1)+(T-1)\}$ of them, and this causes an enormous loss in degrees of freedom. In addition, this attenuates the problem of multicollinearity among the regressors. Rather than invert a large $(N+T+K-1)$ matrix, one can obtain the fixed effects estimates of $\beta$ by performing the following Within transformation given by Wallace and Hussain (1969):

\begin{equation}
Q=E_{N} \otimes E_{T}=I_{N} \otimes I_{T}-I_{N} \otimes \bar{J}_{T}-\bar{J}_{N} \otimes I_{T}+\bar{J}_{N} \otimes \bar{J}_{T}
\end{equation} (3.3)

where $E_{N}=I_{N}-\bar{J}_{N}$ and $E_{T}=I_{T}-\bar{J}_{T}$. This transformation "sweeps" the $\mu_{i}$ and $\lambda_{t}$ effects. In fact, $\tilde{y}=Q y$ has a typical element $\tilde{y}_{i t}=\left(y_{i t}-\bar{y}_{i .}-\bar{y}_{i t}+\bar{y} . .\right)$ where $\bar{y}_{. .}=\sum_{i} \sum_{t} y_{i t} /$ $N T$, and one would perform the regression of $\tilde{y}=Q y$ on $\widetilde{X}=Q X$ to get the Within estimator $\widetilde{\beta}=\left(X^{\prime} Q X\right)^{-1} X^{\prime} Q y$

Note that by averaging the simple regression given in (2.8) over individuals, we get

\begin{equation}
\bar{y}_{. t}=\alpha+\beta \bar{x}_{. t}+\lambda_{t}+\bar{v}_{. t}
\end{equation} (3.4)

where we have utilized the restriction that $\sum_i \mu_i=0$ to avoid the dummy variable trap.
Similarly the averages defined in (2.9) and (2.11) still hold using  $\sum_t \lambda_t=0$ and one can deduce that

\begin{equation}
\left(y_{i t}-\bar{y}_{i .}-\bar{y}_{. t}+\bar{y}_{. .}\right)=\left(x_{i t}-\bar{x}_{i .}-\bar{x}_{. t}+\bar{x}_{. .}\right) \beta+\left(v_{i t}-\bar{v}_{i .}-\bar{v}_{. t}+\bar{v}_{. .}\right)
\end{equation}  (3.5)

OLS on this model gives $\widetilde {\beta}$ the Within estimator for the two-way model. Once again, the
Within estimate of the intercept can be deduced from 
$$\widetilde {\alpha}=\bar{y}_..-\widetilde {\beta} \bar{x}  $$
and those of $\mu_i$ and $\lambda_i$ are given by

\begin{equation}
\tilde{\mu}_{i}=\left(\bar{y}_{i .}-\bar{y}_{. .}\right)-\widetilde{\beta}\left(\bar{x}_{i .}-\bar{x}_{. .}\right)
\end{equation} (3.6)

\begin{equation}
\tilde{\lambda}_{t}=\left(\bar{y}_{. t}-\bar{y}_{. .}\right)-\widetilde{\beta}\left(\bar{x}_{. t}-\bar{x}_{. .}\right)
\end{equation} (3.7)

Note that the Within estimator cannot estimate the effect of time-invariant and individualinvariant variables because the Q transformation wipes out these variables. If the true model
is a two-way fixed effects model as in (3.2), then OLS on (2.1) yields biased and inconsistent estimates of the regression coefficients. OLS ignores both sets of dummy variables, whereas the one-way fixed effects estimator considered in Chapter 2 ignores only the time dummies. If
these time dummies are statistically significant, the one-way fixed effects estimator will also
suffer from omission bias.

### Testing for Fixed Effects

As in the one-way error component model case, one can test for joint significance of the dummy
variables: 

$$
H_{0}: \mu_{1}=\ldots=\mu_{N-1}=0 \quad \text { and } \quad \lambda_{1}=\ldots=\lambda_{T-1}=0
$$
The restricted residual sums of squares (RRSS) is that of pooled OLS and the unrestricted residual sums of squares (URSS) is that from the Within regression in (3.5). In this case,

\begin{equation}
F_{1}=\frac{(\mathrm{RRSS}-\mathrm{URSS}) /(N+T-2)}{\mathrm{URSS} /(N-1)(T-1)-K} \stackrel{H_{0}}{\sim} F_{(N+T-2),(N-1)(T-1)-K}
\end{equation}  (3.8)

Next, one can test for the existence of individual effects allowing for time effects, i.e.
$H_{2}: \mu_{1}==u_{N}=0 \quad$ allowing $\quad \lambda \neq 0$ for $t=1 \ldots \quad T-1$

The URSS is still the Within residual sum of squares. However, the RRSS is the regression with time-series dummies only, or the regression based upon

\begin{equation}
\left(y_{i t}-\bar{y}_{. t}\right)=\left(x_{i t}-\bar{x}_{. t}\right) \beta+\left(u_{i t}-\bar{u}_{. t}\right)
\end{equation} (3.9)

In this case the resulting $F$ -statistic is $F_{2} \stackrel{H_{0}}{\sim} F_{(N-1),(N-1)(T-1)-K}$. Note that $F_{2}$ differs from $F_{0}$ in ( $2.12$ ) in testing for $\mu_{i}=0$. The latter tests $H_{0}: \mu_{i}=0$ assuming that $\lambda_{t}=0$, whereas the former tests $H_{2}: \mu_{i}=0$ allowing $\lambda_{t} \neq 0$ for $t=1, \ldots, T-1$. Similarly, one can test for the existence of time effects allowing for individual effects, i.e.

\begin{equation}
H_{3}: \lambda_{1}=\ldots=\lambda_{T-1}=0 \quad \text { allowing } \quad \mu_{i} \neq 0 ; i=1, \ldots,(N-1)
\end{equation}

The RRSS is given by the regression in (2.10), while the URSS is obtained from the regression
(3.5). In this case, the resulting F-statistic is $F_{3} \sim^{H_{0}} F_{(T-1),(N-1)(T-1)-K}$ .
 
 *Computational Warning*
 
 As in the one-way model, $s^2$ from the regression in (3.5) as obtained from any standard regression package has to be adjusted for loss of degrees of freedom. In this case, one divides by$ (N − 1)(T − 1) − K $ and multiplies by $(NT − K) $to get the proper variance–covariance matrix of the Within estimator.
 
## THE RANDOM EFFECTS MODEL

If $\mu_{i} \sim \operatorname{IID}\left(0, \sigma_{\mu}^{2}\right), \lambda_{t} \sim \operatorname{IID}\left(0, \sigma_{\lambda}^{2}\right)$ and $v_{i t} \sim \operatorname{IID}\left(0, \sigma_{v}^{2}\right)$ independent of each other, then this
is the two-way random effects model. In addition, $X_{i t}$ is independent of $\mu_{i}, \lambda_{t}$ and $v_{i t}$ for all $i$ and $t$. Inference in this case pertains to the large population from which this sample was randomly drawn. From (3.2), one can compute the variance-covariance matrix

\begin{equation}
\begin{aligned}
\Omega &=E\left(u u^{\prime}\right)=Z_{\mu} E\left(\mu \mu^{\prime}\right) Z_{\mu}^{\prime}+Z_{\lambda} E\left(\lambda \lambda^{\prime}\right) Z_{\lambda}^{\prime}+\sigma_{v}^{2} I_{N T} \\
&=\sigma_{\mu}^{2}\left(I_{N} \otimes J_{T}\right)+\sigma_{\lambda}^{2}\left(J_{N} \otimes I_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes I_{T}\right)
\end{aligned}
\end{equation} (3.10)

The disturbances are homoskedastic with $\operatorname{var}\left(u_{i t}\right)=\sigma_{\mu}^{2}+\sigma_{\lambda}^{2}+\sigma_{v}^{2}$ for all $i$ and $t$,

\begin{equation}
\begin{array}{rl}
\operatorname{cov}\left(u_{i t}, u_{j s}\right)=\sigma_{\mu}^{2} & i=j, t \neq s \\
=\sigma_{\lambda}^{2} & i \neq j, t=s
\end{array}
\end{equation} (3.11)

and zero otherwise. This means that the correlation coefficient

\begin{equation}
\begin{aligned}
\operatorname{correl}\left(u_{i t}, u_{j s}\right) &=\sigma_{\mu}^{2} /\left(\sigma_{\mu}^{2}+\sigma_{\lambda}^{2}+\sigma_{v}^{2}\right) & & i=j, t \neq s \\
&=\sigma_{\lambda}^{2} /\left(\sigma_{\mu}^{2}+\sigma_{\lambda}^{2}+\sigma_{v}^{2}\right) & & i \neq j, t=s \\
&=1 & & i=j, t=s \\
&=0 & & i \neq j, t \neq s
\end{aligned}
\end{equation} (3.12)

In order to get $\Omega^{-1}$, we replace $J_{N}$ by $N \bar{J}_{N}, I_{N}$ by $E_{N}+\bar{J}_{N}, J_{T}$ by $T \bar{J}_{T}$ and $I_{T}$ by $E_{T}+\bar{J}_{T}$ and collect terms with the same matrices. This gives

\begin{equation}
\Omega=\sum_{i=1}^{4} \lambda_{i} Q_{i}
\end{equation} (3.13)

where $\lambda_{1}=\sigma_{v}^{2}, \lambda_{2}=T \sigma_{\mu}^{2}+\sigma_{v}^{2}, \lambda_{3}=N \sigma_{\lambda}^{2}+\sigma_{v}^{2}$ and $\lambda_{4}=T \sigma_{\mu}^{2}+N \sigma_{\lambda}^{2}+\sigma_{v}^{2}$. Correspond-
ingly, $Q_{1}=E_{N} \otimes E_{T}, Q_{2}=E_{N} \otimes \bar{J}_{T}, Q_{3}=\bar{J}_{N} \otimes E_{T}$ and $Q_{4}=\bar{J}_{N} \otimes \bar{J}_{T}$, respectively.
The $\lambda_{i}$ are the distinct characteristic roots of $\Omega$ and the $Q_{i}$ are the corresponding matrices of eigenprojectors. $\lambda_{1}$ is of multiplicity $(N-1)(T-1), \lambda_{2}$ is of multiplicity $(N-1), \lambda_{3}$ is of multiplicity $(T-1)$ and $\lambda_{4}$ is of multiplicity $1 .{ }^{1}$ Each $Q_{i}$ is symmetric and idempotent with its rank equal to its trace. Moreover, the $Q_{i}$ are pairwise orthogonal and sum to the identity matrix. The advantages of this spectral decomposition are that

\begin{equation}
\Omega^{r} =\sum_{i=1}^{4} \lambda_{i}^{r} Q_{i}
\end{equation} (3.14)
 
where $r$ is an arbitrary scalar so that

\begin{equation}
\sigma_{v} \Omega^{-1 / 2}=\sum_{i=1}^{4}\left(\sigma_{v} / \lambda_{i}^{1 / 2}\right) Q_{i}
\end{equation} (3.15)

and the typical element of $y^{*}=\sigma_{\nu} \Omega^{-1 / 2} y$ is given by 

\begin{equation}
y_{i t}^{*}=y_{i t}-\theta_{1} \bar{y}_{i .}-\theta_{2} \bar{y}_{. t}+\theta_{3} \bar{y}_{. .}
\end{equation} (3.16)

where $\theta_{1}=1-\left(\sigma_{v} / \lambda_{2}^{1 / 2}\right), \theta_{2}=1-\left(\sigma_{v} / \lambda_{3}^{1 / 2}\right)$ and $\theta_{3}=\theta_{1}+\theta_{2}+\left(\sigma_{v} / \lambda_{4}^{1 / 2}\right)-1$. As a result,
GLS can be obtained as OLS of $y^{*}$ on $Z^{*}$, where $Z^{*}=\sigma_{\nu} \Omega^{-1 / 2} Z$. This transformation was first derived by Fuller and Battese (1974), see also Baltagi (1993).

The best quadratic unbiased (BQU) estimators of the variance components arise naturally from the fact that $Q_{i} u \sim\left(0, \lambda_{i} Q_{i}\right) .$ Hence,

\begin{equation}
\widehat{\lambda}_{i}=u^{\prime} Q_{i} u / \operatorname{tr}\left(Q_{i}\right)
\end{equation} (3.17)

is the BQU estimator of $\lambda_{i}$ for $i=1,2,3$. These ANOVA estimators are minimum variance unbiased (MVU) under normality of the disturbances (see Graybill, 1961 ). As in the one-way error component model, one can obtain feasible estimates of the variance components by replacing the true disturbances by OLS residuals (see Wallace and Hussain, 1969 ). OLS is still an unbiased and consistent estimator under the random effects model, but it is inefficient and results in biased standard errors and $t$ -statistics. Alternatively, one could substitute the Within residuals with $\tilde{u}=y-\widetilde{\alpha} \iota_{N T}-X \widetilde{\beta}$, where $\tilde{\alpha}=\bar{y}_{. .}-\bar{X}_{. .}^{\prime} \tilde{\beta}$ and $\widetilde{\beta}$ is obtained by the regression
in (3.5). This is the method proposed by Amemiya (1971). In fact, Amemiya (1971) shows that the Wallace and Hussain (1969) estimates of the variance components have a different asymptotic distribution from that knowing the true disturbances, while the Amemiya (1971) estimates of the variance components have the same asymptotic distribution as that knowing the true disturbances:

\begin{equation}
\left(\begin{array}{c}
\sqrt{N T}\left(\widehat{\sigma}_{v}^{2}-\sigma_{v}^{2}\right) \\
\sqrt{N}\left(\widehat{\sigma}_{\mu}^{2}-\sigma_{\mu}^{2}\right) \\
\sqrt{T}\left(\widehat{\sigma}^{2}-\sigma_{\mu}^{2}\right)
\end{array}\right) \sim N\left(0,\left(\begin{array}{ccc}
2 \sigma_{v}^{4} & 0 & 0 \\
0 & 2 \sigma_{\mu}^{4} & 0 \\
0 & 0 & 2 \sigma^{4}
\end{array}\right)\right)
\end{equation} (3.18)

SubstitutingOLSorWithin residuals instead of the true disturbances in (3.17) introduces bias in
the corresponding estimates of the variance components. The degrees of freedom corrections
that make these estimates unbiased depend upon traces of matrices that involve the matrix
of regressors X. These corrections are given in Wallace and Hussain (1969) and Amemiya
(1971), respectively. Alternatively, one can infer these correction terms from the more general
unbalanced error component model considered in Chapter 9.
Swamy and Arora (1972) suggest running three least squares regressions and estimating
the variance components from the corresponding mean square errors of these regressions. The
first regression corresponds to the Within regression which transforms the original model by 
$Q_1=E_N \otimes E_T$ . This is equivalent to the regression in (3.5), and yields the following estimate
of $\sigma_v^2$ : 

\begin{equation}
\widehat{\lambda}_{1}=\widehat{\sigma}_{v}^{2}=\left[y^{\prime} Q_{1} y-y^{\prime} Q_{1} X\left(X^{\prime} Q_{1} X\right)^{-1} X^{\prime} Q_{1} y\right] /[(N-1)(T-1)-K]
\end{equation} (3.19)      
( à arranger)

The second regression is the Between individuals regression which transforms the original
model by $$Q_2=E_N \otimes \bar{J}_T $$ This is equivalent to the regression of  $$ (\bar{y}_{i.}- \bar{y}_{i..}) $$  on 
$$ (\bar{X}_{i.}- \bar{X}_{i..}) $$ 
and yields the following estimate of
$ \lambda_2=T\sigma_v^2 + \sigma_v^2 $: 

\begin{equation}
\widehat{\lambda}_{2}=\left[y^{\prime} Q_{2} y-y^{\prime} Q_{2} X\left(X^{\prime} Q_{2} X\right)^{-1} X^{\prime} Q_{2} y\right] /[(N-1)-K]
\end{equation} (3.20)

from which one obtains $\widehat{\sigma}_{\mu}^{2}=\left(\widehat{\lambda}_{2}-\widehat{\sigma}_{v}^{2}\right) / T .$ The third regression is the Between time-periods regression which transforms the original model by $Q_{3}=\bar{J}_{N} \otimes E_{T}$. This is equivalent to the regression of $\left(\bar{y}_{. t}-\bar{y}_{. .}\right)$ on $\left(\bar{X}_{. t}-\bar{X}_{. .}\right)$ and yields the following estimate of $\lambda_{3}=N \sigma_{\lambda}^{2}+\sigma_{v}^{2}$

\begin{equation}
\widehat{\lambda}_{3}=\left[y^{\prime} Q_{3} y-y^{\prime} Q_{3} X\left(X^{\prime} Q_{3} X\right)^{-1} X^{\prime} Q_{3} y\right] /[(T-1)-K]
\end{equation} (3.21)

from which one obtains
$$ (\widehat{\widehat {\sigma_\lambda^2} }= \widehat{\widehat {\lambda} }_3 -  \widehat{\widehat {\lambda} }_v)/N $$  Stacking the three transformed regressions just
performed yields  

\begin{equation}
\left(\begin{array}{l}
Q_{1} y \\
Q_{2} y \\
Q_{3} y
\end{array}\right)=\left(\begin{array}{l}
Q_{1} X \\
Q_{2} X \\
Q_{3} X
\end{array}\right) \beta+\left(\begin{array}{l}
Q_{1} u \\
Q_{2} u \\
Q_{3} u
\end{array}\right)
\end{equation} (3.22)

since $Q_{i} \iota_{N T}=0$ for $i=1,2,3$, and the transformed error has mean 0 and variance-covariance matrix given by $\operatorname{diag}\left[\lambda_{i} Q_{i}\right]$ with $i=1,2,3 .$ Problem $3.4$ asks the reader to show that $\mathrm{OLS}$ on this system of $3 N T$ observations yields the same estimator of $\beta$ as OLS on the pooled model (2.3). Also, GLS on this system of equations (3.22) yields the same estimator of $\beta$ as GLS on (2.3). In fact,

\begin{equation}
\begin{aligned}
\widehat{\beta}_{\mathrm{GLS}}=&\left[\left(X^{\prime} Q_{1} X\right) / \sigma_{v}^{2}+\left(X^{\prime} Q_{2} X\right) / \lambda_{2}+\left(X^{\prime} Q_{3} X\right) / \lambda_{3}\right]^{-1} \\
& \times\left[\left(X^{\prime} Q_{1} y\right) / \sigma_{v}^{2}+\left(X^{\prime} Q_{2} y\right) / \lambda_{2}+\left(X^{\prime} Q_{3} y\right) / \lambda_{3}\right] \\
=&\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1}\left[W_{X y}+\phi_{2}^{2} B_{X y}+\phi_{3}^{2} C_{X y}\right]
\end{aligned}
\end{equation} (3.23)

with $\operatorname{var}\left(\widehat{\beta}_{\mathrm{GLS}}\right)=\sigma_{v}^{2}\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1}$. Note that $W_{X X}=X^{\prime} Q_{1} X, B_{X X}=X^{\prime} Q_{2} X$
and $C_{X X}=X^{\prime} Q_{3} X$ with $\phi_{2}^{2}=\sigma_{v}^{2} / \lambda_{2}, \phi_{3}^{2}=\sigma_{v}^{2} / \lambda_{3} .$ Also, the Within estimator of $\beta$ is $\widetilde{\beta}_{W}=$
$W_{X X}^{-1} W_{X y}$, the Between individuals estimator of $\beta$ is $\widehat{\beta}_{B}=B_{X X}^{-1} B_{X y}$ and the Between timeperiods estimator of $\beta$ is $\widehat{\beta}_{C}=C_{X X}^{-1} C_{X y}$. This shows that $\widehat{\beta}_{\mathrm{GLS}}$ is a matrix-weighted average of $\widetilde{\beta}_{W}, \widehat{\beta}_{B}$ and $\widehat{\beta}_{C}$. In fact,

\begin{equation}
\widehat{\beta}_{\mathrm{GLS}}=W_{1} \widetilde{\beta}_{W}+W_{2} \widehat{\beta}_{B}+W_{3} \widehat{\beta}_{C}
\end{equation} (3.24)

where 

\begin{equation}
\begin{aligned}
&W_{1}=\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1} W_{X X} \\
&W_{2}=\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1}\left(\phi_{2}^{2} B_{X X}\right) \\
&W_{3}=\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1}\left(\phi_{3}^{2} C_{X X}\right)
\end{aligned}
\end{equation}

This was demonstrated by Maddala (1971). Note that (i) if $\sigma_{\mu}^{2}=\sigma_{\lambda}^{2}=0, \phi_{2}^{2}=\phi_{3}^{2}=1$ and $\widehat{\beta}_{\mathrm{GLS}}$ reduces to $\widehat{\beta}_{\mathrm{OLs}}$; (ii) as $T$ and $N \rightarrow \infty, \phi_{2}^{2}$ and $\phi_{3}^{2} \rightarrow 0$ and $\widehat{\beta}_{\mathrm{GLS}}$ tends to $\widetilde{\beta}_{W}$; (iii) if
$\phi_{2}^{2} \rightarrow \infty$ with $\phi_{3}^{2}$ finite, then $\widehat{\beta}_{\mathrm{GLS}}$ tends to $\widehat{\beta}_{B}$; (iv) if $\phi_{3}^{2} \rightarrow \infty$ with $\phi_{2}^{2}$ finite, then $\widehat{\beta}_{\text {GLS }}$ tends to $\widehat{\beta}_{C}$.
Wallace and Hussain (1969) compare $\widehat{\beta}_{\mathrm{GLS}}$ and $\widetilde{\beta}_{\text {Within }}$ in the case of nonstochastic (repetitive) $X$ and find that both are (i) asymptotically normal, (ii) consistent and unbiased and that

(iii) $\widehat{\beta}_{\mathrm{GLS}}$ has a smaller generalized variance (i.e. more efficient) in finite samples. In the case of nonstochastic (nonrepetitive) $X$ they find that both $\widehat{\beta}_{\mathrm{GLS}}$ and $\widetilde{\beta}_{\text {Within }}$ are consistent, asymptotically unbiased and have equivalent asymptotic variance-covariance matrices, as both $N$ and $T \rightarrow \infty$. The last statement can be proved as follows: the limiting variance of the GLS estimator is

\begin{equation}
\frac{1}{N T} \lim _{N \rightarrow \infty \atop T \rightarrow \infty}\left(X^{\prime} \Omega^{-1} X / N T\right)^{-1}=\frac{1}{N T} \lim _{N \rightarrow \infty \atop T \rightarrow \infty}\left[\sum_{i=1}^{3} \frac{1}{\lambda_{i}}\left(X^{\prime} Q_{i} X / N T\right)\right]^{-1}
\end{equation} (3.25)

but the limit of the inverse is the inverse of the limit, and

\begin{equation}
\lim _{N \rightarrow \infty \atop T \rightarrow \infty} \frac{X^{\prime} Q_{i} X}{N T} \quad \text { for } i=1,2,3
\end{equation} (3.26)

all exist and are positive semidefinite, since $$\lim _{N \rightarrow \infty \atop T \rightarrow \infty}\left(X^{\prime} X / N T\right)$$ is assumed finite and positive definite. Hence

$$
\lim _{N \rightarrow \infty \atop T \rightarrow \infty} \frac{1}{\left(N \sigma_{\lambda}^{2}+\sigma_{v}^{2}\right)}\left(\frac{X^{\prime} Q_{3} X}{N T}\right)=0
$$

and
$$
\lim _{N \rightarrow \infty \atop T \rightarrow \infty} \frac{1}{\left(T \sigma_{\mu}^{2}+\sigma_{v}^{2}\right)}\left(\frac{X^{\prime} Q_{2} X}{N T}\right)=0
$$
Therefore the limiting variance of the GLS estimator becomes
$$
\frac{1}{N T} \lim _{N \rightarrow \infty \atop T \rightarrow \infty} \sigma_{v}^{2}\left(\frac{X^{\prime} Q_{1} X}{N T}\right)^{-1}
$$

which is the limiting variance of the Within estimator. One can extend Nerlove's (1971a) method for the one-way model, by estimating $\sigma_{\mu}^{2}$ as $\sum_{i=1}^{N}\left(\widehat{\mu}_{i}-\widehat{\mu}\right)^{2} /(N-1)$ and $\sigma_{\lambda}^{2}$ as $\sum_{t=1}^{T}\left(\widehat{\lambda}_{t}-\bar{\lambda}\right)^{2} /(T-1)$ where the $\widehat{\mu}_{i}$ and $\widehat{\lambda}_{t}$ are obtained
as coefficients from the least squares dummy variables regression (LSDV). $\sigma_{v}^{2}$ is estimated from the Within residual sums of squares divided by $N T$. Baltagi (1995, appendix 3) develops two other methods of estimating the variance components. The first is Rao's (1970) minimum norm quadratic unbiased estimation (MINQUE) and the second is Henderson's method III as described by Fuller and Battese (1973). These methods require more notation and development and may be skipped in a brief course on this subject. Chapter 9 studies these estimation methods in the context of an unbalanced error component model.

Baltagi (1981a) performed a Monte Carlo study on a simple regression equation with twoway error component disturbances and studied the properties of the following estimators:
OLS, the Within estimator and six feasible GLS estimators denoted by WALHUS, AMEMIYA, SWAR, MINQUE, FUBA and NERLOVE corresponding to the methods developed by Wallace and Hussain (1969), Amemiya (1971), Swamy and Arora (1972), Rao (1972), Fuller and Battese (1974) and Nerlove (1971a), respectively. The mean square error of these estimators was computed relative to that of true GLS, i.e. GLS knowing the true variance components. To review some of the properties of these estimators: OLS is unbiased, but asymptotically inefficient, and its standard errors are biased; see Moulton (1986) for the extent of this bias in empirical applications. In contrast, the Within estimator is unbiased whether or not prior

information about the variance components is available. It is also asymptotically equivalent to the GLS estimator in case of weakly nonstochastic exogenous variables. Early in the literature, Wallace and Hussain (1969) recommended the Within estimator for the practical researcher, based on theoretical considerations but more importantly for its ease of computation. In Wallace and Hussain's (1969, p. 66) words the "covariance estimators come off with a surprisingly clear bill of health". True GLS is BLUE, but the variance components are usually not known and have to be estimated. All of the feasible GLS estimators considered are asymptotically efficient. In fact, Prucha (1984) showed that as long as the estimate of $\sigma_{v}^{2}$ is consistent, and the probability limits of the estimates $\sigma_{\mu}^{2}$ and $\sigma_{\lambda}^{2}$ are finite, the corresponding feasible GLS estimator is asymptotically efficient. Also, Swamy and Arora (1972) proved the existence of a family of asymptotically efficient two-stage feasible GLS estimators of the regression coefficients. Therefore, based on asymptotics only, one cannot differentiate among these twostage GLS estimators. This leaves undecided the question of which estimator is the best to use. Some analytical results were obtained by Swamy (1971) and Swamy and Arora (1972). These studies derived the relative efficiencies of (i) SWAR with respect to OLS, (ii) SWAR with respect to Within and (iii) Within with respect to OLS. Then, for various values of $N, T$, the variance components, the Between groups, Between time-periods and Within groups sums of squares of the independent variable, they tabulated these relative efficiency values (see Swamy, 1971 , chapters II and III; Swamy and Arora, 1972, p. 272). Among their basic findings is the fact that, for small samples, SWAR is less efficient than OLS if $\sigma_{\mu}^{2}$ and $\sigma_{\lambda}^{2}$ are small. Also, SWAR is less efficient than Within if $\sigma_{\mu}^{2}$ and $\sigma_{\lambda}^{2}$ are large. The latter result is disconcerting, since Within, which uses only a part of the available data, is more efficient than SWAR, a feasible GLS estimator, which uses all of the available data.

# Test of Hypotheses with Panel Data







## REFERENCES 