<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Analyses | Panel Analyses Report</title>
  <meta name="description" content="dans ce livre nous produisons le rapport complet d’analyses du panel des taxes des pays Africains." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Analyses | Panel Analyses Report" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="dans ce livre nous produisons le rapport complet d’analyses du panel des taxes des pays Africains." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Analyses | Panel Analyses Report" />
  
  <meta name="twitter:description" content="dans ce livre nous produisons le rapport complet d’analyses du panel des taxes des pays Africains." />
  

<meta name="author" content="David BYAMUNGU" />


<meta name="date" content="2021-10-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="test-of-hypotheses-with-panel-data.html"/>
<link rel="next" href="references-1.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>




<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="the-one-way-error-component-regression-model.html"><a href="the-one-way-error-component-regression-model.html"><i class="fa fa-check"></i><b>2</b> The One-way Error Component Regression Model</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-one-way-error-component-regression-model.html"><a href="the-one-way-error-component-regression-model.html#introduction"><i class="fa fa-check"></i><b>2.1</b> INTRODUCTION</a></li>
<li class="chapter" data-level="2.2" data-path="the-one-way-error-component-regression-model.html"><a href="the-one-way-error-component-regression-model.html#the-fixed-effects-model"><i class="fa fa-check"></i><b>2.2</b> THE FIXED EFFECTS MODEL</a></li>
<li class="chapter" data-level="2.3" data-path="the-one-way-error-component-regression-model.html"><a href="the-one-way-error-component-regression-model.html#the-random-effects-model"><i class="fa fa-check"></i><b>2.3</b> THE RANDOM EFFECTS MODEL</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="the-one-way-error-component-regression-model.html"><a href="the-one-way-error-component-regression-model.html#fixed-vs-random"><i class="fa fa-check"></i><b>2.3.1</b> Fixed vs Random</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-two-way-error-component-regression-model.html"><a href="the-two-way-error-component-regression-model.html"><i class="fa fa-check"></i><b>3</b> The Two-way Error Component Regression Model</a>
<ul>
<li class="chapter" data-level="3.1" data-path="the-two-way-error-component-regression-model.html"><a href="the-two-way-error-component-regression-model.html#ntroduction"><i class="fa fa-check"></i><b>3.1</b> NTRODUCTION</a></li>
<li class="chapter" data-level="3.2" data-path="the-two-way-error-component-regression-model.html"><a href="the-two-way-error-component-regression-model.html#the-fixed-effects-model-1"><i class="fa fa-check"></i><b>3.2</b> THE FIXED EFFECTS MODEL</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="the-two-way-error-component-regression-model.html"><a href="the-two-way-error-component-regression-model.html#testing-for-fixed-effects"><i class="fa fa-check"></i><b>3.2.1</b> Testing for Fixed Effects</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="the-two-way-error-component-regression-model.html"><a href="the-two-way-error-component-regression-model.html#the-random-effects-model-1"><i class="fa fa-check"></i><b>3.3</b> THE RANDOM EFFECTS MODEL</a></li>
<li class="chapter" data-level="3.4" data-path="the-two-way-error-component-regression-model.html"><a href="the-two-way-error-component-regression-model.html#references"><i class="fa fa-check"></i><b>3.4</b> REFERENCES</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="test-of-hypotheses-with-panel-data.html"><a href="test-of-hypotheses-with-panel-data.html"><i class="fa fa-check"></i><b>4</b> Test of Hypotheses with Panel Data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="test-of-hypotheses-with-panel-data.html"><a href="test-of-hypotheses-with-panel-data.html#tests-for-poolability-of-the-data"><i class="fa fa-check"></i><b>4.1</b> TESTS FOR POOLABILITY OF THE DATA</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="test-of-hypotheses-with-panel-data.html"><a href="test-of-hypotheses-with-panel-data.html#test-for-poolability-under"><i class="fa fa-check"></i><b>4.1.1</b> Test for Poolability under</a></li>
<li class="chapter" data-level="4.1.2" data-path="test-of-hypotheses-with-panel-data.html"><a href="test-of-hypotheses-with-panel-data.html#test-for-poolability-under-the-general-assumption"><i class="fa fa-check"></i><b>4.1.2</b> Test for Poolability under the General Assumption</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="test-of-hypotheses-with-panel-data.html"><a href="test-of-hypotheses-with-panel-data.html#tests-for-individual-and-time-effects"><i class="fa fa-check"></i><b>4.2</b> TESTS FOR INDIVIDUAL AND TIME EFFECTS</a></li>
<li class="chapter" data-level="4.3" data-path="test-of-hypotheses-with-panel-data.html"><a href="test-of-hypotheses-with-panel-data.html#hausmans-specification-test"><i class="fa fa-check"></i><b>4.3</b> HAUSMAN’S SPECIFICATION TEST</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analyses.html"><a href="analyses.html"><i class="fa fa-check"></i><b>5</b> Analyses</a>
<ul>
<li class="chapter" data-level="5.1" data-path="analyses.html"><a href="analyses.html#netoyage-de-la-base-des-données"><i class="fa fa-check"></i><b>5.1</b> Netoyage de la base des données</a></li>
<li class="chapter" data-level="5.2" data-path="analyses.html"><a href="analyses.html#modele-avec-les-pays-comme-individus"><i class="fa fa-check"></i><b>5.2</b> Modele avec les pays comme individus</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="analyses.html"><a href="analyses.html#agregation-des-données-avec-la-méthode-reduce"><i class="fa fa-check"></i><b>5.2.1</b> Agregation des données avec la méthode reduce</a></li>
<li class="chapter" data-level="5.2.2" data-path="analyses.html"><a href="analyses.html#analyse-descriptive-des-varariales"><i class="fa fa-check"></i><b>5.2.2</b> Analyse descriptive des Varariales</a></li>
<li class="chapter" data-level="5.2.3" data-path="analyses.html"><a href="analyses.html#overall-variations"><i class="fa fa-check"></i><b>5.2.3</b> Overall Variations</a></li>
<li class="chapter" data-level="5.2.4" data-path="analyses.html"><a href="analyses.html#between-variations"><i class="fa fa-check"></i><b>5.2.4</b> Between Variations</a></li>
<li class="chapter" data-level="5.2.5" data-path="analyses.html"><a href="analyses.html#within-variations"><i class="fa fa-check"></i><b>5.2.5</b> Within variations</a></li>
<li class="chapter" data-level="5.2.6" data-path="analyses.html"><a href="analyses.html#modélisation"><i class="fa fa-check"></i><b>5.2.6</b> Modélisation</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="analyses.html"><a href="analyses.html#modèle-avec-les-marchandises-comme-individus"><i class="fa fa-check"></i><b>5.3</b> Modèle avec les marchandises comme individus</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="6" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>6</b> Conclusion</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Panel Analyses Report</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analyses" class="section level1" number="5">
<h1><span class="header-section-number">Chapter 5</span> Analyses</h1>
<p>Nous faisons <em>application</em> des méthodes présentées dans le chapitre précédant pour l’analyse des données de pannel</p>
<p>Avant de passefr à la modélisation, nous ferons une description de nos variables d’interet d’une manière statique : nos prédicteurs et la variables réponses</p>
<div id="netoyage-de-la-base-des-données" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Netoyage de la base des données</h2>
<p>Aperçue globale des données</p>
<table>
<caption>
<span id="tab:unnamed-chunk-3">Table 5.1: </span>Echantillon de la base des données
</caption>
<thead>
<tr>
<th style="text-align:right;">
N°
</th>
<th style="text-align:left;">
Country/destination
</th>
<th style="text-align:right;">
Year
</th>
<th style="text-align:left;">
Goods
</th>
<th style="text-align:right;">
Weight
</th>
<th style="text-align:right;">
Taxe
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2011
</td>
<td style="text-align:left;">
GRUES SUR PNEUMATIQUE
</td>
<td style="text-align:right;">
13500
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2011
</td>
<td style="text-align:left;">
CAMION FAMIL
</td>
<td style="text-align:right;">
12000
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2011
</td>
<td style="text-align:left;">
CAMION SOMUL
</td>
<td style="text-align:right;">
24000
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2013
</td>
<td style="text-align:left;">
Café vert arabica k4
</td>
<td style="text-align:right;">
183
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2013
</td>
<td style="text-align:left;">
Café vert arabica k4
</td>
<td style="text-align:right;">
19520
</td>
<td style="text-align:right;">
264771
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2013
</td>
<td style="text-align:left;">
Café vert arabica k4
</td>
<td style="text-align:right;">
19520
</td>
<td style="text-align:right;">
272817
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2013
</td>
<td style="text-align:left;">
Café vert arabica k4
</td>
<td style="text-align:right;">
19520
</td>
<td style="text-align:right;">
283220
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2013
</td>
<td style="text-align:left;">
Café vert arabica k4
</td>
<td style="text-align:right;">
19520
</td>
<td style="text-align:right;">
264142
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2013
</td>
<td style="text-align:left;">
CAMION
</td>
<td style="text-align:right;">
24000
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
AFRIQUE DU SUD
</td>
<td style="text-align:right;">
2017
</td>
<td style="text-align:left;">
Instruments et appareils du n°90.15
</td>
<td style="text-align:right;">
654
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>Voici la structure de la base des données</p>
<p>La variables <strong>Goods </strong> a 740 modalités. En observant de près les modalités, on trouve que ces modalités sont rédondantes.Pour cela, il faudra une récodification des cettes variales.</p>
<p>Ainsi, donc les modalités representant la même marchandise seront groupées ensemble , pour des raisons de simplification.</p>
<p>Usage de tm et Stringr pour manipuler les chaines des caractères</p>
<pre><code>##  [1] &quot;Autres Marchandises&quot;                      
##  [2] &quot;Bois&quot;                                     
##  [3] &quot;Machines et appareils domestique&quot;         
##  [4] &quot;Médicaments et plantes médécinales&quot;       
##  [5] &quot;Poissaons, viande et oeufs&quot;               
##  [6] &quot;Matériels de construction&quot;                
##  [7] &quot;Materiel Informatique et Electroniques&quot;   
##  [8] &quot;Véhicules,camions,Motos et acc&quot;           
##  [9] &quot;Vetements,tissus et acc et chaussure&quot;     
## [10] &quot;boissons, bières et limonades&quot;            
## [11] &quot;Machine us Ingsutriel&quot;                    
## [12] &quot;Article Menange et Campement&quot;             
## [13] &quot;sacs, sachetsn emballages&quot;                
## [14] &quot;Papiers et fournitures de bureaux&quot;        
## [15] &quot;Produits alimentaires,prep et huiles&quot;     
## [16] &quot;caféarabica&quot;                              
## [17] &quot;Minérais et dérivés&quot;                      
## [18] &quot;engins et tracteurs&quot;                      
## [19] &quot;Cigarette et papier cigarettes et tabac&quot;  
## [20] &quot;constructionprefabriquees&quot;                
## [21] &quot;cadreset conteneurs&quot;                      
## [22] &quot;Pièces de Réchange appareils&quot;             
## [23] &quot;Générateurs,baterie et piles&quot;             
## [24] &quot;etuis en plastique ou textile&quot;            
## [25] &quot;Pétrole et dérivées et huile de graissage&quot;
## [26] &quot;boissons, bières,liqueurs et limonades&quot;   
## [27] &quot;produits beaute&quot;                          
## [28] &quot;peauxdes betes&quot;</code></pre>
<p>netoyyage de la variable country_desti qui est un facteur dans le quel nous retrouvons les niveaux rédondants (sur l’identifiant des pays)</p>
<p>Dans la base des données il y a des entreprises que l’on a enregistré à la place des pays. ces genre des cas ont été traité par remplacement avec le <em>NA</em> pour <strong>Not Available</strong> et ces dernier on été élagués de la base des données, car nous avions jugé qu’ aucune méthode d’imputation n’est applicable pour ce genre de situation. Nous avions fait la même chose pour les variables telles que <strong>Les marchandises</strong>.</p>
<p><strong>Nouvelle base de données pour les analyses</strong></p>
<p>Regroupement des variables pour la synthèse pour rendre la base des données simple à exploiter, éliminer les NA dans les observations telsque les pays et les valeurs pour les marchandises et les taxes.</p>

<p>Les données de panel, ou données longitudinales possèdent les deux dimensions précédentes (individuelle et temporelle). En effet, il est souvent intéressant d’identifier l’effet associé à chaque individu (un effet qui ne varie pas dans le temps, mais qui varie d’un individu à un autre). Cet effet peut être fixe ou aléatoire.</p>
<p>Par conséquent, le modèle en données de panel s’écrit comme un modèle à double indice qui prend la forme suivante :</p>
<p><span class="math display">\[ Y_{it}= \alpha_i\sum_{k}\beta_{ki}x_{ki}+ \epsilon_{it} \]</span></p>
<p>avec
<span class="math display">\[ i:1 \rightarrow N \]</span><br />
et
<span class="math display">\[ t:1 \rightarrow T \]</span></p>
<p>La double dimension qu’offrent les données de panel est un atout majeur. En effet, si les données en séries temporelles permettent d’étudier l’évolution des relations dans le temps, elles ne permettent pas de contrôler l’hétérogénéité entre les individus. A l’inverse, les données en coupes transversales permettent d’analyser l’hétérogénéité entre les individus mais elles ne peuvent pas tenir compte des comportements dynamiques, puisque la dimension temporelle est exclue du champ d’analyse.</p>
<p>Ainsi, en utilisant des données de panel, on pourra exploiter les deux sources de variation de l’information statistique :
- Temporelle où variabilité intra-individuelle (within)
- et individuelle ou variabilité inter-individuelle (Between).</p>
</div>
<div id="modele-avec-les-pays-comme-individus" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Modele avec les pays comme individus</h2>
<div id="agregation-des-données-avec-la-méthode-reduce" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Agregation des données avec la méthode reduce</h3>
</div>
<div id="analyse-descriptive-des-varariales" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Analyse descriptive des Varariales</h3>
<p>Conversion des données en modèle des panels des données</p>
<pre><code>##  [1] &quot;AFRIQUE DU SUD&quot;                          
##  [2] &quot;ALGERIE&quot;                                 
##  [3] &quot;ALLEMAGNE&quot;                               
##  [4] &quot;AMERIQUE LATINE&quot;                         
##  [5] &quot;GRANDE BRATAGNE&quot;                         
##  [6] &quot;ANGOLA&quot;                                  
##  [7] &quot;ARABIE&quot;                                  
##  [8] &quot;ASIE&quot;                                    
##  [9] &quot;AUSTRALIE&quot;                               
## [10] &quot;BELGIQUE&quot;                                
## [11] &quot;BURUNDI&quot;                                 
## [12] &quot;CANADA&quot;                                  
## [13] &quot;CHINE&quot;                                   
## [14] &quot;CHYPRE&quot;                                  
## [15] &quot;CONGO BRAZA&quot;                             
## [16] &quot;REP TCHEQUE&quot;                             
## [17] &quot;NA&quot;                                      
## [18] &quot;EMIRATES ARABES UNIES&quot;                   
## [19] &quot;ESPAGNE&quot;                                 
## [20] &quot;FRANCE&quot;                                  
## [21] &quot;GABON&quot;                                   
## [22] &quot;GRECE&quot;                                   
## [23] &quot;HONG KONG&quot;                               
## [24] &quot;ILE MAURICE&quot;                             
## [25] &quot;INDE&quot;                                    
## [26] &quot;ITALIE&quot;                                  
## [27] &quot;JAPON&quot;                                   
## [28] &quot;KENYA&quot;                                   
## [29] &quot;KP - Corée, République Populaire démocra&quot;
## [30] &quot;LUXEMBOURG&quot;                              
## [31] &quot;MALAISIE&quot;                                
## [32] &quot;MAROC&quot;                                   
## [33] &quot;NERLAND&quot;                                 
## [34] &quot;PAYS BAS&quot;                                
## [35] &quot;NIGERIA&quot;                                 
## [36] &quot;NOUVELLE ZELANDE&quot;                        
## [37] &quot;OUGANDA&quot;                                 
## [38] &quot;PANAMA&quot;                                  
## [39] &quot;PHILLIPINE&quot;                              
## [40] &quot;POLOGNE&quot;                                 
## [41] &quot;PORTUGAL&quot;                                
## [42] &quot;ROYAUME UNI&quot;                             
## [43] &quot;RDC&quot;                                     
## [44] &quot;USA&quot;                                     
## [45] &quot;RWANDA&quot;                                  
## [46] &quot;SINGAPOUR&quot;                               
## [47] &quot;SUISSE&quot;                                  
## [48] &quot;SENEGAL&quot;                                 
## [49] &quot;SOMALIE&quot;                                 
## [50] &quot;SOUDAN&quot;                                  
## [51] &quot;SUD SOUDAN&quot;                              
## [52] &quot;SUEDE&quot;                                   
## [53] &quot;Swaziland&quot;                               
## [54] &quot;TANZANIE&quot;                                
## [55] &quot;TCHAD&quot;                                   
## [56] &quot;THAILANDE&quot;                               
## [57] &quot;UNION EUROPEENNE&quot;                        
## [58] &quot;ZAMBIE&quot;</code></pre>
</div>
<div id="overall-variations" class="section level3" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Overall Variations</h3>
<pre><code>## 
## ====================================================================================
## Statistic  N    St. Dev.         Min        Pctl(25)      Pctl(75)         Max      
## ------------------------------------------------------------------------------------
## Taxes     228 24,567,143.00 -8,268,474.00 -8,268,474.00 -5,225,015.00 153,754,050.00
## Weight    228  407,973.40    -218,369.60   -196,559.50    -7,893.40    2,883,127.00 
## ------------------------------------------------------------------------------------</code></pre>
<p>L’écart-type des taxes pour les individus à travars le temps est 24,567,143.00 et celle des poids des marchandises est de 407,973.40 Kg .</p>
</div>
<div id="between-variations" class="section level3" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> Between Variations</h3>
<pre><code>## 
## ==========================================================================
## Statistic N      Mean       St. Dev.   Min Pctl(25)  Pctl(75)      Max    
## --------------------------------------------------------------------------
## Taxes     58 4,215,140.00 9,499,457.00  0     0     3,345,864.0 47,724,880
## Weight    58  132,331.80   196,253.90  100  19,665   120,394.6   940,804  
## --------------------------------------------------------------------------</code></pre>
<p>De ce tableau, on peut lire que:</p>
<ul>
<li>Les taxes varient de varient de 4,215,140.00 en moyenne d’un individu à un autre</li>
<li>Les poids des marchandises varient de 132,331.80 dollars d’un pays à un autre.</li>
</ul>
</div>
<div id="within-variations" class="section level3" number="5.2.5">
<h3><span class="header-section-number">5.2.5</span> Within variations</h3>
<pre><code>## 
## ==========================================================================
## Statistic  N    St. Dev.        Min       Pctl(25)   Pctl(75)      Max    
## --------------------------------------------------------------------------
## Taxes     228 20,714,497.00 -47,724,880 -3,291,776.0 175,658.1 133,691,390
## Weight    228  322,405.60    -870,261    -63,771.4   29,042.9   2,624,477 
## --------------------------------------------------------------------------</code></pre>
<p>De ce tableau, on peut lire que :</p>
<ul>
<li>L’écart moyen des taxes dans un pays, d’une année à une autre est de 20,714,497.00 dollars.</li>
<li>L’écart moyen des poids des marchandises est de 322,405.60 kg d’une année à une autre, pour un pays.</li>
</ul>
</div>
<div id="modélisation" class="section level3" number="5.2.6">
<h3><span class="header-section-number">5.2.6</span> Modélisation</h3>
<p>Modèle à polaire, considérant que le modèle est le même pour tous les pays. ce la suppose l’absence des éffets aléatoire et des éffets aléatoires.</p>
<pre><code>## Pooling Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = &quot;pooling&quot;)
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -76127299  -3525554    -38253         0    822609 135485918 
## 
## Coefficients:
##                Estimate  Std. Error t-value Pr(&gt;|t|)    
## (Intercept) -8.7251e+05  1.3302e+06 -0.6559   0.5125    
## Weight       4.1859e+01  2.8796e+00 14.5367   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    1.37e+17
## Residual Sum of Squares: 7.0803e+16
## R-Squared:      0.48321
## Adj. R-Squared: 0.48092
## F-statistic: 211.315 on 1 and 226 DF, p-value: &lt; 2.22e-16</code></pre>
<p>Le modèle s’écrit:
<span class="math display">\[Y= 4.1859e^{01} X - 8.7251e^{05}  \]</span>
Avec:</p>
<ul>
<li>Y : Les taxes recoltées pour les différentes marchandises dans tout les pays</li>
<li>X : Le poids globales des toutes les marchandises ayant traversé la douane pour chaque période concernant notre étude, et pour chaque individus</li>
</ul>
<p>Notons que, pour ce type de panel, nos individus sont les pays et le temps est mésuré en année , à partir de l’année 2010 jusqu’en 2020.</p>
<p>La variable poids, dans les données des bases a été agrées, en calculant la somme de tous les poids pour pour les différentes marchandises n pour une année
Ainsi, nous avions:</p>
<p><span class="math display">\[ P_{i.t}=\sum_{j=1}^{n} P{i..} \]</span>
i indiquant les marchandises , de la prémière à la n-ième marchandise. Ainsi donc, nous avions somme les poids de chaque marchandise pour trouver le poids annuel des marchanides ayant traversé la douane d’un pays. Il en est de même pour les taxes.</p>
<p>Le coefficient associé au poids des marchandises est significatif car le p-value associé est inférieur à 0,05. Tansdis que le terme indépendant n’est pas significativement différent de 0 vu que le p-value associé est supérieur au seuil.</p>
<p>Ainsi donc, quand le poids augmente d’une unité, les taxes augmentent de 4,185 unités, pour tous les pays, et à travers le temps. Cette augmentation est significativement différent de 0.</p>
<p>En testant la significativité globale du modèle, nous utilisant le Langranhe Multiplier test.</p>
<pre><code>## 
##  Lagrange Multiplier Test - (Honda) for unbalanced panels
## 
## data:  Taxes ~ Weight
## normal = 0.89501, p-value = 0.1854
## alternative hypothesis: significant effects</code></pre>
<p>Le test pour le modèle <code>pooling</code> est non significatif vu que le p-value associé au test est supérieur au seuil de 5% (0,05). Ainsi donc, nous adoptons l’hypothèse nulle du test selon laquelle le modèle polaire n’est pas significatif.</p>
<p>Modele à éffet fixes.
Nous produisons ce modèle en utilisant la methode <code>Within</code> qui traduit les variations de la variables dependante en fonction des variables dépendantes, mais pour un individus à travers le temps.</p>
<pre><code>## Oneway (individual) effect Within Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, effect = &quot;individual&quot;, 
##     model = &quot;within&quot;)
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -69551626  -1715042         0         0   1537006 114103679 
## 
## Coefficients:
##        Estimate Std. Error t-value  Pr(&gt;|t|)    
## Weight  39.6087     3.8914  10.178 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    9.7404e+16
## Residual Sum of Squares: 6.0386e+16
## R-Squared:      0.38005
## Adj. R-Squared: 0.16728
## F-statistic: 103.601 on 1 and 169 DF, p-value: &lt; 2.22e-16</code></pre>
<p>ici, nous modélisons les éffets individuels.
Le coefficient des taxes signifie, que les pays augmentaient leurs importations d’une unitées, chacune, nous aurions une augmentation de 39,6087 dollars pour ce pays.</p>
<p>EXtraction des effets fixes
Ce sont les effects individuels spécifiques pour chaque pays.</p>
<p>On remarque que:</p>
<ul>
<li>La chine a 21758301 dollars de taxe de plus que la moyenne des taxes de tous les pays, et ce, d’une manière significative.</li>
<li>HONG KONG 21758301 dollars de plus que la moyenne des pays, et ce, significativement.</li>
<li>Les effets individuels de tous les autres pays ne sont pas significativement différents de 0 vu que les p-values associées, respectivement pour chaque pays sont de loin supérieur au seuil chacune.</li>
</ul>
<p>Le modèle à éffets aléatoire</p>
<pre><code>## Oneway (individual) effect Between Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = &quot;between&quot;)
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## Observations used in estimation: 58
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -17710356  -1366186    300948         0    907729  22825793 
## 
## Coefficients:
##                Estimate  Std. Error t-value  Pr(&gt;|t|)    
## (Intercept) -9.2150e+05  9.0924e+05 -1.0135    0.3152    
## Weight       3.8816e+01  3.8643e+00 10.0449 3.886e-14 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    5.1437e+15
## Residual Sum of Squares: 1.8358e+15
## R-Squared:      0.64309
## Adj. R-Squared: 0.63671
## F-statistic: 100.9 on 1 and 56 DF, p-value: 3.886e-14</code></pre>
<p>Ainsi donc, le modèle within s’écrit:</p>
<p><span class="math display">\[ Y = + 3.8816e^{01}X - 9.2150e^{05} \]</span>
Pour fragmentation d’une unité pour le poids des marchandises, on observe une augmentation des taxes de 38,81 unitées d’un pays à un autre. cela signifie que, si un pays à importé un 1Kg plus qu’un autre, nous observerons une différence de 38,82 dollars pour les taxes.</p>
<pre><code>## 
##  F test for individual effects
## 
## data:  Taxes ~ Weight
## F = 0.51147, df1 = 57, df2 = 169, p-value = 0.998
## alternative hypothesis: significant effects</code></pre>
<p>Le choix du modèle en utlisant le test d’Hausman</p>
<p>Ce test consiste à comparer les coefficients de ce s deux modèles, pour en fint chhoisir le modèle qui est consistant entre les modèle à éffet individuel et le modèle à éffet aléatoire.</p>
<pre><code>## 
##  Hausman Test
## 
## data:  Taxes ~ Weight
## chisq = 0.020872, df = 1, p-value = 0.8851
## alternative hypothesis: one model is inconsistent</code></pre>
<p>Ce test étant non qignificatif, c’est-à-dire , nous adoptons l’hypothèse nulle : les coefficients du modèle à éffet fixe et ceux du modèle à éffet aléatoire ne sont pas significativement différents. Ainsi donc, nous utiliserons les modèles à éffets aléatoire car celui-ci est efficien (éficace).</p>
<p>Effet aleatoire</p>
<pre><code>## Oneway (individual) effect Random Effect Model 
##    (Wallace-Hussain&#39;s transformation)
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = &quot;random&quot;, 
##     random.method = &quot;walhus&quot;)
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Effects:
##                     var   std.dev share
## idiosyncratic 3.578e+14 1.891e+07     1
## individual    0.000e+00 0.000e+00     0
## theta:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0       0       0       0       0       0 
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -76127299  -3525554    -38253         0    822609 135485918 
## 
## Coefficients:
##                Estimate  Std. Error z-value Pr(&gt;|z|)    
## (Intercept) -8.7251e+05  1.3302e+06 -0.6559   0.5119    
## Weight       4.1859e+01  2.8796e+00 14.5367   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    1.37e+17
## Residual Sum of Squares: 7.0803e+16
## R-Squared:      0.48321
## Adj. R-Squared: 0.48092
## Chisq: 211.315 on 1 DF, p-value: &lt; 2.22e-16</code></pre>

</div>
</div>
<div id="modèle-avec-les-marchandises-comme-individus" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Modèle avec les marchandises comme individus</h2>
<p>Modèle à polaire, considérant les deux effets</p>
<pre><code>## Pooling Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = &quot;pooling&quot;)
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -76127299  -3525554    -38253         0    822609 135485918 
## 
## Coefficients:
##                Estimate  Std. Error t-value Pr(&gt;|t|)    
## (Intercept) -8.7251e+05  1.3302e+06 -0.6559   0.5125    
## Weight       4.1859e+01  2.8796e+00 14.5367   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    1.37e+17
## Residual Sum of Squares: 7.0803e+16
## R-Squared:      0.48321
## Adj. R-Squared: 0.48092
## F-statistic: 211.315 on 1 and 226 DF, p-value: &lt; 2.22e-16</code></pre>
<p>Modele à éffet aléatoire</p>
<pre><code>## Oneway (individual) effect Within Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, effect = &quot;individual&quot;, 
##     model = &quot;within&quot;)
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -69551626  -1715042         0         0   1537006 114103679 
## 
## Coefficients:
##        Estimate Std. Error t-value  Pr(&gt;|t|)    
## Weight  39.6087     3.8914  10.178 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    9.7404e+16
## Residual Sum of Squares: 6.0386e+16
## R-Squared:      0.38005
## Adj. R-Squared: 0.16728
## F-statistic: 103.601 on 1 and 169 DF, p-value: &lt; 2.22e-16</code></pre>
<p>l’expression du modèle est : $ Y=39,6087 X$</p>
<p>Ainsi donc, ce coefficient étant significatif, traduit que l’augmentation du poids des marchnise de une unité entrainte une augmentation des taxes perçues de 39,6087 dollars, pour la même marchandise</p>
<p>Le modèle à éffets aléatoire</p>
<pre><code>## Oneway (individual) effect Between Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = &quot;between&quot;)
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## Observations used in estimation: 58
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -17710356  -1366186    300948         0    907729  22825793 
## 
## Coefficients:
##                Estimate  Std. Error t-value  Pr(&gt;|t|)    
## (Intercept) -9.2150e+05  9.0924e+05 -1.0135    0.3152    
## Weight       3.8816e+01  3.8643e+00 10.0449 3.886e-14 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    5.1437e+15
## Residual Sum of Squares: 1.8358e+15
## R-Squared:      0.64309
## Adj. R-Squared: 0.63671
## F-statistic: 100.9 on 1 and 56 DF, p-value: 3.886e-14</code></pre>
<p>Le modèle s’écrit de la manière suivante:</p>
<p><span class="math display">\[Y= 3.8816e^{01}X -9.2150e^{05}\]</span>
Le coefficient associé au poids étant significatif, on trouve que: si une marchandise dépassait en poids une autre de 1Kg, les taxes perçues pour cette marchandises dépasseraient cette autre de 38,8 dollars.</p>
<p>Condidérant le R-Carré ajutsté, Ce modèle explique à 63,7% les variations des taxes en fonction des poids des marchandises.</p>
<p>Pour arbitrer le choix entre le modèle à effet fixe et le modèle à éffet aléatoire, nous allons utiliser le test d’Hausman qui consite à comprer les coefficients de ces deux modèles</p>
<pre><code>## # A tibble: 1 x 5
##   statistic p.value parameter method       alternative              
##       &lt;dbl&gt;   &lt;dbl&gt;     &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;                    
## 1      9.03 0.00265         1 Hausman Test one model is inconsistent</code></pre>
<p>Le test d’Hausman étant significatif pour ces données, nous optons donc le modèle à éffet à éffet fixe pour estimer les taxes sachant que les individus sont les marchandises car celui-ci est consistant.</p>
<p>On suppose donc une variation significative entre les marchandises.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="test-of-hypotheses-with-panel-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["panel-analyses-book.pdf", "panel-analyses-book.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
