% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\title{Panel Analyses Report}
\author{David BYAMUNGU}
\date{2021-10-18}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Panel Analyses Report},
  pdfauthor={David BYAMUNGU},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{fancyhdr}
\usepackage[left=3cm, right=2.5cm, bottom=3cm, top=3cm]{geometry}
\usepackage{titling}
\fancypagestyle{titlpage}{
fancyfoot[LE,RO]{thepage of pageref{LastPage}}
fancyfoot[LE,LO]{Project}
}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{apalike}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{intro}{%
\chapter{Introduction}\label{intro}}

Dans ce document nous cherchons à modéliser les taxes perçues dans différents pays , formant un panel dont la période est 10 ans.
Ainsi, nous expliquerons la variable taxe par:

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  Le poids des Marchandises
\item
  La qualité des Marchandises
\end{enumerate}

Le but est d'arbitrer entre:

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  le modèle \emph{pooling}
\item
  le \emph{modele à éffet fixe} et
\item
  le \emph{modèle à éffet aléatoire}
\end{enumerate}

et en fin produire un \texttt{modèle\ dynamique} permettant d'expliquer la variation du taxe au cours du temps, avec comme variable dépendante additionnelle le taxe décalé

Nous expliquons Notre méthodologie dans la partie suivante.

\hypertarget{the-one-way-error-component-regression-model}{%
\chapter{The One-way Error Component Regression Model}\label{the-one-way-error-component-regression-model}}

\hypertarget{introduction}{%
\section{INTRODUCTION}\label{introduction}}

A panel data regression differs from a regular time-series or cross-section regression in that it has a double subscript on its variables, i.e.

\begin{equation}
 y_{it}= \alpha + X_{it}^{'} \beta + u_{it}                      $$ $$ i=1, ... , N  ; t=1, ... ,T 
 \end{equation}(2.1)

with \$ i \$ denoting households, individuals, firms, countries, etc. and t denoting time. The i subscript, therefore, denotes the cross-section dimension whereas t denotes the time-series dimension. \[ \alpha  \] is a scalar, \[ \beta \] is \[ K × 1 \] and Xi t is the \$ it\_\{th\} \$ observation on K explanatory variables. Most of the panel data applications utilize a one-way error component model for the disturbances, with

\[ u_{it}= \mu_i +  v_{it}      \] (2.2)

where μi denotes the unobservable individual-specific effect and νi t denotes the remainder disturbance. For example, in an earnings equation in labor economics, yi t will measure earnings of the head of the household, whereas \[ X_{it} \] may contain a set of variables like experience, education, union membership, sex, race, etc. Note that μi is time-invariant and it accounts for any individual-specific effect that is not included in the regression. In this case we could think of it as the individual's unobserved ability. The remainder disturbance \[ v_{it} \] varies with individuals and time and can be thought of as the usual disturbance in the regression. Alternatively, for a production function utilizing data on firms across time, \[ y_{it} \] will measure output and \[ X_{it} \] will measure inputs. The unobservable firm-specific effects will be captured by the \[ \mu_i \] and we can think of these as the unobservable entrepreneurial or managerial skills of the firm's executives. Early applications of error components in economics include Kuh (1959) on investment, Mundlak (1961) and Hoch (1962) on production functions and Balestra and Nerlove (1966) on demand for natural gas. In vector form (2.1) can be written as

\begin{equation} y= \alpha i_{NT} + X \beta + u = Z \delta + u     \end{equation} (2.3)

\begin{equation} y= \alpha i_{NT} + X \beta + u = Z \delta + u      \end{equation} (2.3)

where \$ y \$ is \$ NT × 1 \$, \$ X \$ is \$ NT × K \$, \$ Z = {[}ι\_\{NT\} , X{]} \$, \$ \delta\^{}\{'\} = (α\textsuperscript{\{'\},}\beta{'}) \$ and \(ι_NT\) is a vector of ones of dimension NT. Also, (2.2) can be written as

\begin{equation} u=Z_\mu \mu +v  \end{equation} (2.4)

\[  y_{it} = \alpha + X_{it}^{'} + U_{it}   \] , \$ i=1,\ldots,N ; t=1,\ldots,T \$ with i denoting households, individuals, firms, countries, etc. and t denoting time. The i subscript, therefore, denotes the cross-section dimension whereas t denotes the time-series dimension. \$ \alpha \$ is a scalar, \$ \beta \$ is \$ K × 1 \$ and \$X\_\{it\} \$is the \$ it\^{}\{th\} \$ observation on K explanatory variables. disturbances, with it \[ u_{it}=u_i  + v_{it}     \]

where μi denotes the unobservable individual-specific effect and \(ν{it}\) denotes the remainder disturbance. For example, in an earnings equation in labor economics, \(y_{it}\) will measure earnings of the head of the household, whereas Xi t may contain a set of variables like experience, education, union membership, sex, race, etc. Note that μi is time-invariant and it accounts for any individual-specific effect that is not included in the regression. In this case we could think of it as the individual's unobserved ability. The remainder disturbance \$ ν\{it\} \$ varies with individuals and time and can be thought of as the usual disturbance in the regression. Alternatively, for a production function utilizing data on firms across time, \$ y\_\{it\} \$ will measure output and \$ X\_\{it\} \$ will measure inputs. The unobservable firm-specific effects will be captured by the \$ \mu\_i \$ and we can think of these as the unobservable entrepreneurial or managerial skills of the firm's executives. Early applications of error components in economics include Kuh (1959) on investment, Mundlak (1961) and Hoch (1962) on production functions and Balestra and Nerlove (1966) on demand for natural gas. In vector form (2.1) can be written as

\[ y= \alpha i_{NT}  + X\beta +u = Z\delta + u \]

where \(y\) is \$ NT × 1\$ , X is \(NT × K\) , \$ Z = {[}i\_\{NT\} , X{]} \$ , \$ \delta\^{}\{`\}=(\^{}\alpha{'},\beta\^{}\{'\})\$ and \(i_{NT}\) is a vector of ones of dimension \(NT\) . Also, (2.2) can be written as

\begin{equation} u=Z_\mu \mu  + v\end{equation} (2.4)

where \$ u\^{}\{`\} = (u\_\{11\}, . . . , u\_\{1T\} , u\_\{21\}, . . . , u\_\{2T\}, . . . , u\_\{N1\}, . . . , u\_\{NT\} ) \$ with the observations stacked such that the slower index is over individuals and the faster index is over time.\$ Z\_\mu = IN \otimes ιT \$ where IN is an identity matrix of dimension N, ιT is a vector of ones of dimension T and \$ \otimes \$ denotes Kronecker product. \$ Z\_\mu \$ is a selector matrix of ones and zeros, or simply the matrix of individual dummies that one may include in the regression to estimate theμi if they are assumed to be fixed parameters. \$ \mu\^{}\{'\} = (\mu\_1, . . . , \mu\_N )\$ and \(ν^{'} = (ν11, . . . , ν_{1T} , . . . , ν_{N1}, . . . , ν_{NT} )\). Note that \$Z\_\mu Z\^{}\{`\}\mu = I\_N \otimes J\_T \$ where \(J_T\) is a matrix of ones of dimension T and \$ P = Zμ(Z\textsuperscript{\{'\}}\mu Z\mu)\{−1\} Z\^{}\{'\}\mu \$ , the projectionmatrix on \$ Z\_\mu \$ , reduces to \$ IN \otimes J\_T \$ where \$J \_T= JT /T \$ . P is a matrix which averages the observation across time for each individual, and Q = INT − P is a matrix which obtains the deviations from individual means. For example, regressing y on the matrix of dummy variables \(Z_μ\) gets the predicted values \$ P\_y \$ which has a typical element

\[ \bar y_i = \sum_{t=1}^T \frac{y_{it}}{T}  \] repeated T times for each individual. The residuals of this regression are given by Qy which has a typical element \[ (y_{it} - \bar y _{i.} ) \] P and Q are (i) symmetric idempotent matrices, i.e.

\(P^{'} = P\) and \$ P\^{}2 = P \$. This means that \(rank(P) = tr(P) = N\) and \(rank(Q) = tr(Q) = N(T − 1)\) . This uses the result that the rank of an idempotent matrix is equal to its trace (see Graybill, 1961,theorem 1.63). Also, (ii) P and Q are orthogonal, i.e.~\$PQ=0 \$ and (iii) they sum to the identity matrix \(P + Q = I_{NT}\). In fact, any two of these properties imply the third (see Graybill, 1961, theorem 1.68).

\hypertarget{the-fixed-effects-model}{%
\section{THE FIXED EFFECTS MODEL}\label{the-fixed-effects-model}}

In this case, the μi are assumed to be fixed parameters to be estimated and the remainder disturbances stochastic with \(v_{it}\) independent and identically distributed \(IID(0,\sigma_v^2)\). The \(X_{it}\) are assumed independent of the \(v_{it}\) for all i and t. The fixed effects model is an appropriate specification if we are focusing on a specific set of N firms, say, IBM, GE,Westinghouse, etc. and our inference is restricted to the behavior of these sets of firms. Alternatively, it could be a set of N OECD countries, or N American states. Inference in this case is conditional on the particular N firms, countries or states that are observed. One can substitute the disturbances given by (2.4) into (2.3) to get

\begin{equation} 
y=\alpha i\_{IT} + X\beta + Z\_\mu \mu +v = Z\delta + Z\_\mu \mu +v 
\end{equation} (2.5)

and then perform ordinary least squares (OLS) on (2.5) to get estimates of \$ \alpha,\beta ~and ~µ \$

Note that Z is \$ NT \times (K+1)\$ and \(Z_µ\) , the matrix of individual dummies, is\$NT \times N \$ NT × N. If N is large, (2.5) will include too many individual dummies, and the matrix to be inverted by OLS is large and of dimension \((N + K)\). In fact, since α and β are the parameters of interest, one can obtain the LSDV (least squares dummy variables) estimator from (2.5), by premultiplying the model by Q and performing OLS on the resulting transformed model:

\begin{equation} Qy=QX\beta + Qv\end{equation} (2.6)

This uses the fact that \(QZ_\mu =Qi_{NT}=0\) , since \(PZ_\mu =Z_\mu\) the Q matrix wipes out the individual effects. This is a regression of \(\tilde y =QY\) with element \((y_{it} - \bar y _{i.} )\) on \(\check X=QX\) with typical element

\begin{equation}
\widetilde{\beta}=\left(X^{\prime} Q X\right)^{-1} X^{\prime} Q y
\end{equation} (2.7)
(2.7) with \(\operatorname{var}(\widetilde{\beta})=\sigma_{v}^{2}\left(X^{\prime} Q X\right)^{-1}=\sigma_{v}^{2}\left(\widetilde{X}^{\prime} \tilde{X}\right)^{-1}\) . \(\widetilde{\beta}\) could have been obtained from (2.5) using results on partitioned inverse or the Frisch--Waugh--Lovell theorem discussed in Davidson and MacKinnon (1993, p.~19). This uses the fact that P is the projection matrix on \(Z_{\mu}\) and \(Q = I_{NT} − P\) (see problem 2.1). In addition, generalized least squares (GLS) on (2.6), using the generalized inverse, will also yield \(\widetilde{\beta }\) (see problem 2.2).

Note that for the simple regression
\begin{equation}y_{it}=\beta x_{it}+ \mu_i+ v_i     \end{equation} (2.8)

and averaging over time gives
\begin{equation}  \bar {y}_{i.}= \beta \bar{x}_{i.}+ \mu_i+ \bar{v}_i   \end{equation} (2.9)

Therefore, subtracting (2.9) from (2.8) gives \[y_{it}-\bar{y}_{i.}=\beta (x_{it}-\bar{x}_{i.}) + (v_{it}-\bar{v}_{i.})   \] (2.10)

Also, averaging across all observations in (2.8) gives \[\bar{y}_{..}=\alpha + \beta \bar{x}_{..} + \bar{v}_{..} \] (2.11)i =0 where we utilized the restriction that \$\sum\emph{\{i=1\}\^{}\{n\} \mu{i}=0 \$ This is an arbitrary restriction on the dummy variable coefficients to avoid the dummy variable trap, or perfect multicollinearity; see Suits (1984) for alternative formulations of this restriction. In fact only \(\beta\) and \$ (\alpha + \mu}\{i\})\$ are estimable from (2.8), and not α and μi separately, unless a restriction like* \[\sum_{i=1}^{n} \mu_{i}=0 \] is imposed. In this case, \(\widetilde {\beta}\) is obtained from regression (2.10), \[\widetilde {\alpha}= \bar {y}_{..}-\widetilde {\beta} \bar{x}_{..} \] can be recovered from (2.11) and \[\widetilde {\mu}_{i}=\bar{y}_{i.}- \widetilde {\alpha} - \widetilde {\beta} \bar{X}_{i.} \] from (2.9). For large labor or consumer panels, where N is very large,regressions like (2.5) may not be feasible, since one is including (N − 1) dummies in the regression. This fixed effects (FE) least squares, also known as least squares dummy variables (LSDV), suffers from a large loss of degrees of freedom. We are estimating (N − 1) extra parameters, and too many dummies may aggravate the problem of multicollinearity among the regressors. In addition, this FE estimator cannot estimate the effect of any time-invariant variable like sex, race, religion, schooling or union participation. These time-invariant variables are wiped out by the Q transformation, the deviations from means transformation (see (2.10)). Alternatively, one can see that these time-invariant variables are spanned by the individual dummies in (2.5) and therefore any regression package attempting (2.5) will fail, signaling perfect multicollinearity. If (2.5) is the true model, LSDV is the best linear unbiased estimator (BLUE) as long as \(v_{it}\) is the standard classical disturbance with mean 0 and variance--covariance matrix \$\sigma {v}\^{}\{2\} I\_\{NT\} \$ . Note that as \(T \rightarrow \infty\) the FE estimator is consistent. However, if T is fixed and \(N \rightarrow \infty\) as is typical in short labor panels, then only the FE estimator of β is consistent; the FE estimators of the individual effects \(\alpha + \mu_{i}\) are not consistent since the number of these parameters increases as N increases. This is the incidental parameter problem discussed by Neyman and Scott (1948) and reviewed more recently by Lancaster (2000). Note that when the true model is fixed effects as in (2.5), OLS on (2.1) yields biased and inconsistent estimates of the regression parameters. This is an omission variables bias due to the fact that OLS deletes the individual dummies when in fact they are relevant.

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  \emph{Testing for fixed effects.} One could test the joint significance of these dummies, i.e.~H0; \(\mu_{1}=\mu_{2}= ... = \mu_{N-1}=0\) , by performing an F-test. (Testing for individual effects will be treated extensively in Chapter 4.) This is a simple Chow test with the restricted residual sums of squares (RRSS) being that of OLS on the pooled model and the unrestricted residual sums of squares (URSS) being that of the LSDV regression. If N is large, one can perform the Within transformation and use that residual sum of squares as the URSS. In this case
\end{enumerate}

\[F_{0}=    \frac{ \dfrac{RRSS-URSS}{N-1}}{\dfrac{URSS}{NT-N-K} } \sim  F_{N-1,N(T-1)-K}           \] (2.12)

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\setcounter{enumi}{1}
\item
  \emph{Computational warning.} One computational caution for those using theWithin regression given by (2.10). The \(s^{2}\) f this regression as obtained from a typical regression package divides the residual sums of squares by NT − K since the intercept and the dummies are not included. The proper \(s^{2}\) , say \(s^{*2}\) from the LSDV regression in (2.5), would divide the same residual sums of squares by \(N(T − 1) − K\) . Therefore, one has to adjust the variances obtained from the Within regression (2.10) by multiplying the variance--covariance matrix by \[\frac{s^{2}}{s^{*2}} \] or simply by multiplying by \([NT − K]/[N(T − 1) − K]\)
\item
  \emph{Robust estimates of the standard errors.} For the Within estimator, Arellano (1987) suggests a simple method for obtaining robust estimates of the standard errors that allow for a general variance--covariance matrix on the \(v_{it}\) as in White (1980). One would stack the panel as an equation for each individual: \[y_{i}= Z_{i} \delta + \mu i_{it} + v_{i} \] (2.13)
\end{enumerate}

where \(y_i\) is T × \$Z\_i ={[}l\_T,X\_i{]} \$, \(X_i\) is T × K, \(\mu _i\) is a scalar, \(\delta ^{\prime} = (\alpha, \beta^{\prime} )\) , \(i_T\) is a vector of ones of dimension T and \(v_i\) is T x 1 . In general, \(E(v_i,v_i^{\prime}) = \Omega _ i\) for i = 1, 2, . . . , N, where \(\Omega _i\) is a positive definite matrix of dimension T . We still assume \(E(v_i,v_j^{\prime}) =0\) for \(i \ne j\) T is assumed small and N large as in household or company panels, and the asymptotic results are performed for \(N \rightarrow \infty\) and T fixed. Performing the Within transformation on this set of equations (2.13) one gets

\[  \widetilde {y}_i=\widetilde{X}_{i} \beta + \widetilde{v}_{i}  \] (2.14)

where \[\widetilde{y}=Qy \] , \[\widetilde{X}=QX \] and \[\widetilde{v}=Qv \] , with \[\widetilde{y}=(\widetilde{y}_1^{\prime}, ...,\widetilde{y}_N^{\prime} )^{\prime} \] and \[\widetilde{y}_i=(I_T-\bar{J}_T) y_i \] Computing robust least squares on this system, as described by White (1980), under the restriction that each equation has the same \(\beta\) one gets the Within estimator of β which has the following asymptotic distribution:

\[N^{\frac{1}{2} }  (\widetilde{\beta}- \beta ) \sim N(0,M^{-1}VM^{-1} ) \] (2.15)

where \[M=\frac{ p\lim(\widetilde{X}^{\prime} \widetilde{X})} {N} \] Note that \[\widetilde{X}_i=(I_T - \bar{J}_T) X_i  \] and \[\widetilde{X}^{\prime} diag[\Omega_i] Q \widetilde{X} \] (see problem 2.3). In this case, V is estimated by \[ \frac{  \widetilde{V}=\sum_{i=1}^{N} \widetilde{X}_i^{\prime}\widetilde{u}_i \widetilde{u}_i^{\prime}\widetilde{X}_i^{\prime} } {N}  \] where \[\widetilde{u}_i=\widetilde{y}_i- \widetilde{X}_i \widetilde{\beta}_i\] . Therefore, the robust asymptotic variance-- covariance matrix of \(\beta\) is estimated by \[
\operatorname{var}(\widetilde{\beta})=\left(\widetilde{X}^{\prime} \tilde{X}\right)^{-1}\left[\sum_{i=1}^{N} \widetilde{X}_{i}^{\prime} \tilde{u}_{i} \tilde{u}_{i}^{\prime} \widetilde{X}_{i}\right]\left(\widetilde{X}^{\prime} \tilde{X}\right)^{-1}
\]

\hypertarget{the-random-effects-model}{%
\section{THE RANDOM EFFECTS MODEL}\label{the-random-effects-model}}

There are too many parameters in the fixed effects model and the loss of degrees of freedom can be avoided if the μi can be assumed random. In this case \$ \mu*i* \sim IID(0, \sigma\mu\^{}2)\$, \$ν\_\{it\} ∼ IID(0, \sigma\_v\^{}2 ) \$ and the \(\mu_i\) are independent of the \(v_{it}\) . In addition, the \(X_{it}\) are independent of the \(\mu_i\) and \(v_{it}\),for all i and t. The random effects model is an appropriate specification if we are drawing N individuals randomly from a large population. This is usually the case for household panel studies. Care is taken in the design of the panel to make it ``representative'' of the population we are trying to make inferences about. In this case, N is usually large and a fixed effects model would lead to an enormous loss of degrees of freedom. The individual effect is characterized as random and inference pertains to the population from which this sample was randomly drawn.

But what is the population in this case? Nerlove and Balestra (1996) emphasize Haavelmo's (1944) view that the population ``consists not of an infinity of individuals, in general, but of an infinity of decisions'' that each individual might make. This view is consistent with a random effects specification. From (2.4), one can compute the variance--covariance matrix

\begin{equation}
\begin{aligned}
\Omega &=E\left(u u^{\prime}\right)=Z_{\mu} E\left(\mu \mu^{\prime}\right) Z_{\mu}^{\prime}+E\left(v v^{\prime}\right) \\
&=\sigma_{\mu}^{2}\left(I_{N} \otimes J_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes I_{T}\right)
\end{aligned}
\end{equation}

This implies a homoskedastic variance \(\operatorname{var}\left(u_{i t}\right)=\sigma_{\mu}^{2}+\sigma_{v}^{2} \mathrm{f}\) for all i and t, and an equicorrelated block-diagonal covariance matrix which exhibits serial correlation over time only between the disturbances of the same individual. In fact,

\(\begin{aligned} \operatorname{cov}\left(u_{i t}, u_{j s}\right) &=\sigma_{\mu}^{2}+\sigma_{v}^{2} & \text { for } \quad i=j, t=s \\ &=\sigma_{\mu}^{2} & \text { for } i=j, t \neq s \end{aligned}\)

and zero otherwise. This also means that the correlation coefficient between \(\mu _{it}\) and \(\mu _{js}\) is \(\begin{aligned} \rho=\operatorname{correl}\left(u_{i t}, u_{j s}\right) &=1 & & \text { for } i=j, t=s \\ &=\sigma_{\mu}^{2} /\left(\sigma_{\mu}^{2}+\sigma_{v}^{2}\right) & \text { for } i=j, t \neq s \end{aligned}\)

and zero otherwise. In order to obtain the GLS estimator of the regression coefficients, we need \$\Omega \^{}\{-1\} \$. This is a huge matrix for typical panels and is of dimension \(NT × NT\). No brute force inversion should be attempted even if the researcher's application has a small N and T .1 We will follow a simple trick devised by Wansbeek and Kapteyn (1982b, 1983) that allows the derivation of \$\Omega \^{}\{-1\} \$ ans \(\Omega^{-1 / 2}\) Essentially, one replaces \(J_{T}\) by \(T \bar{J}_{T}\) and \(I_{T}\) by \(\left(E_{T}+\bar{J}_{T}\right)\) where \(E_T\) is by definition \(\left(I_{T}-\bar{J}_{T}\right)\) . In this case

\(\Omega=T \sigma_{\mu}^{2}\left(I_{N} \otimes \bar{J}_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes E_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes \bar{J}_{T}\right)\)

Collecting terms with the same matrices, we get \begin{equation}
\Omega=\left(T \sigma_{\mu}^{2}+\sigma_{v}^{2}\right)\left(I_{N} \otimes \bar{J}_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes E_{T}\right)=\sigma_{1}^{2} P+\sigma_{v}^{2} Q
\end{equation}

where \(\sigma_{1}^{2}=T \sigma_{\mu}^{2}+\sigma_{v}^{2}\) . (2.18) is the spectral decomposition representation of \(\Omega\), with \(\sigma_1^2\) being the first unique characteristic root of\(\Omega\) of multiplicity \(N(T − 1)\). It is easy to verify, using the properties of P and Q, that

\begin{equation}
\Omega^{-1}=\frac{1}{\sigma_{1}^{2}} P+\frac{1}{\sigma_{v}^{2}} Q
\end{equation} and \begin{equation}
\Omega^{-1 / 2}=\frac{1}{\sigma_{1}} P+\frac{1}{\sigma_{v}} Q
\end{equation}

In fact, \(\Omega^{r}=\left(\sigma_{1}^{2}\right)^{r} P+\left(\sigma_{v}^{2}\right)^{r} Q\) where r is an arbitrary scalar. Now we can obtain GLS as a weighted least squares. Fuller and Battese (1973, 1974) suggested premultiplying the regression equation given in (2.3) by \(\sigma_{v} \Omega^{-1 / 2}=Q+\left(\sigma_{v} / \sigma_{1}\right) P\) and performing OLS on the resulting transformed regression. In this case, \(y^{*}=\sigma_{v} \Omega^{-1 / 2} y\) has a typical element \(y_{i t}-\theta \bar{y}_{i .}\) where \(\theta=1-\left(\sigma_{v} / \sigma_{1}\right)\) (see problem 2.4). This transformed regression inverts a matrix of dimension \((K + 1)\) and can easily be implemented using any regression package.

The best quadratic unbiased (BQU) estimators of the variance components arise naturally from the spectral decomposition of \(\Omega\) . In fact, \(P u \sim\left(0, \sigma_{1}^{2} P\right)\) and \(Q u \sim\left(0, \sigma_{v}^{2} Q\right)\) and

\begin{equation}
\widehat{\sigma}_{1}^{2}=\frac{u^{\prime} P u}{\operatorname{tr}(P)}=T \sum_{i=1}^{N} \bar{u}_{i .}^{2} / N
\end{equation} and

\begin{equation}
\widehat{\sigma}_{v}^{2}=\frac{u^{\prime} Q u}{\operatorname{tr}(Q)}=\frac{\sum_{i=1}^{N} \sum_{t=1}^{T}\left(u_{i t}-\bar{u}_{i .}\right)^{2}}{N(T-1)}
\end{equation}

provide the BQU estimators of \(\sigma_1^2\) and\(\sigma_v^2\) , respectively (see problem 2.5).

These are analyses of variance-type estimators of the variance components and are minimum variance-unbiased under normality of the disturbances (see Graybill, 1961). The true disturbances are not known and therefore (2.21) and (2.22) are not feasible. Wallace and Hussain (1969) suggest substituting OLS residual \(\widehat{u}_{\mathrm{OLS}}\) instead of the true u. After all, under the random effects model, the OLS estimates are still unbiased and consistent, but no longer efficient. Amemiya (1971) shows that these estimators of the variance components have a different asymptotic distribution from that knowing the true disturbances. He suggests using the LSDV residuals instead of the OLS residuals. In this case \(\tilde{u}=y-\tilde{\alpha} \iota_{N T}-X \widetilde{\beta}\) where and \(\bar{X}_{. .}^{\prime}\) is a \(1 \times K\)

vector of averages of all regressors. Substituting these \(\hat{u}\) for u in (2.21) and (2.22) we get the Amemiya-type estimators of the variance components. The resulting estimates of the variance components have the same asymptotic distribution as that knowing the true disturbances:

\begin{equation}
\left(\begin{array}{c}
\sqrt{N T}\left(\widehat{\sigma}_{v}^{2}-\sigma_{v}^{2}\right) \\
\sqrt{N}\left(\widehat{\sigma}_{\mu}^{2}-\sigma_{\mu}^{2}\right)
\end{array}\right) \sim N\left(0,\left(\begin{array}{cc}
2 \sigma_{v}^{4} & 0 \\
0 & 2 \sigma_{\mu}^{4}
\end{array}\right)\right)
\end{equation}

where \(\widehat{\sigma}_{\mu}^{2}=\left(\widehat{\sigma}_{1}^{2}-\widehat{\sigma}_{v}^{2}\right) / T .^{3}\)

Swamy and Arora (1972) suggest running two regressions to get estimates of the variance components from the corresponding mean square errors of these regressions. The first regression is the Within regression, given in (2.10), which yields the following \(s^2\):

\begin{equation}
\widehat{\sigma}_{v}^{2}=\left[y^{\prime} Q y-y^{\prime} Q X\left(X^{\prime} Q X\right)^{-1} X^{\prime} Q y\right] /[N(T-1)-K]
\end{equation}

The second regression is the Between regression which runs the regression of averages across time, i.e.

\begin{equation}
\bar{y}_{i .}=\alpha+\bar{X}_{i .}^{\prime} \beta+\bar{u}_{i .} \quad i=1, \ldots, N
\end{equation}

(2.25)

This is equivalent to premultiplying the model in (2.5) by P and running OLS. The only caution is that the latter regression has NT observations because it repeats the averages T times for each individual, while the cross-section regression in (2.25) is based on N observations. To remedy this, one can run the cross-section regression

\begin{equation}
\sqrt{T} \bar{y}_{i .}=\alpha \sqrt{T}+\sqrt{T} \bar{X}_{i .}^{\prime} \beta+\sqrt{T} \bar{u}_{i .}
\end{equation} (2.26)

where one can easily verify that \(\operatorname{var}\left(\sqrt{T} \bar{u}_{i .}\right)=\sigma_{1}^{2} .\) This regression will yield an \(s^{2}\) given by

\begin{equation}
\widehat{\sigma}_{1}^{2}=\left(y^{\prime} P y-y^{\prime} P Z\left(Z^{\prime} P Z\right)^{-1} Z^{\prime} P y\right) /(N-K-1)
\end{equation} (2.27)

Note that stacking the following two transformed regressions we just performed yields \begin{equation}
\left(\begin{array}{l}
Q y \\
P y
\end{array}\right)=\left(\begin{array}{l}
Q Z \\
P Z
\end{array}\right) \delta+\left(\begin{array}{c}
Q u \\
P u
\end{array}\right)
\end{equation} (2.28)

and the transformed error has mean 0 and variance--covariance matrix given by

\[
\left(\begin{array}{cc}
\sigma_{v}^{2} Q & 0 \\
0 & \sigma_{1}^{2} P
\end{array}\right)
\]

Problem 2.7 asks the reader to verify that OLS on this system of 2NT observations yields OLS on the pooled model (2.3). Also, GLS on this system yields GLS on (2.3). Alternatively, one could get rid of the constant α by running the following stacked regressions:

\begin{equation}
\left(\begin{array}{c}
Q y \\
\left(P-\bar{J}_{N T}\right) y
\end{array}\right)=\left(\begin{array}{c}
Q X \\
\left(P-\bar{J}_{N T}\right) X
\end{array}\right) \beta+\left(\begin{array}{c}
Q u \\
\left(P-\bar{J}_{N T}\right) u
\end{array}\right)
\end{equation} (2.29)

This follows from the fact that QιNT = 0 and (P − J¯NT )ιNT = 0. The transformed error has zero mean and variance--covariance matrix \[
\left(\begin{array}{cc}
\sigma_{v}^{2} Q & 0 \\
0 & \sigma_{1}^{2}\left(P-\bar{J}_{N T}\right)
\end{array}\right)
\] OLS on this system yields OLS on (2.3) and GLS on (2.29) yields GLS on (2.3). In fact, \begin{equation}
\begin{aligned}
\widehat{\beta}_{\mathrm{GLS}}=&\left[\left(X^{\prime} Q X / \sigma_{v}^{2}\right)+X^{\prime}\left(P-\bar{J}_{N T}\right) X / \sigma_{1}^{2}\right]^{-1}\left[\left(X^{\prime} Q y / \sigma_{v}^{2}\right)\right.\\
&\left.+X^{\prime}\left(P-\bar{J}_{N T}\right) y / \sigma_{1}^{2}\right] \\
=&\left[W_{X X}+\phi^{2} B_{X X}\right]^{-1}\left[W_{X y}+\phi^{2} B_{X y}\right]
\end{aligned}
\end{equation} (2.30)

with \(\operatorname{var}\left(\widehat{\beta}_{\mathrm{GLS}}\right)=\sigma_{v}^{2}\left[W_{X X}+\phi^{2} B_{X X}\right]^{-1} .\) Note that \(W_{X X}=X^{\prime} Q X, B_{X X}=X^{\prime}\left(P-\bar{J}_{N T}\right) X\) and \(\phi^{2}=\sigma_{v}^{2} / \sigma_{1}^{2}\). Also, the Within estimator of \(\beta\) is \(\underline{\beta}_{\text {Within }}=W_{X X}^{-1} W_{X y}\) and the Between estimator of \(\beta\) is \(\widehat{\beta}_{\text {Between }}=B_{X X}^{-1} B_{X y} .\) This shows that \(\widehat{\beta}_{\mathrm{GLS}}\) is a matrix weighted average of \(\widetilde{\beta}_{\text {Within and }} \widehat{\beta}_{\text {Between }}\) weighing each estimate by the inverse of its corresponding variance. In fact

\begin{equation}
\widehat{\beta}_{\mathrm{GLS}}=W_{1} \widetilde{\beta}_{\mathrm{Within}}+W_{2} \widehat{\beta}_{\mathrm{Between}}
\end{equation} (2.31) where \[
W_{1}=\left[W_{X X}+\phi^{2} B_{X X}\right]^{-1} W_{X X}
\] and \[
W_{2}=\left[W_{X X}+\phi^{2} B_{X X}\right]^{-1}\left(\phi^{2} B_{X X}\right)=I-W_{1}
\] This was demonstrated by Maddala (1971). Note that (i) if \(\sigma_{\mu}^{2}=0\) then \(\phi^{2}=1\) and \(\widehat{\beta}_{\text {GLS }}\) reduces to \(\widehat{\beta}_{\text {OLs. }}\) (ii) If \(T \rightarrow \infty\), then \(\phi^{2} \rightarrow 0\) and \(\widehat{\beta}_{\text {GLS }}\) tends to \(\widetilde{\beta}_{\text {Within. }}\) Also, if \(W_{X X}\) is huge compared to \(B_{X X}\) then \(\widehat{\beta}_{\mathrm{GLS}}\) will be close to \(\widetilde{\beta}_{\text {Within }}\). However, if \(B_{X X}\) dominates \(W_{X X}\) then \(\widehat{\beta}_{\mathrm{GLS}}\) tends to \(\widehat{\beta}_{\text {Between. }}\) In other words, the Within estimator ignores the Between variation, and the Between estimator ignores the Within variation. The OLS estimator gives equal weight to the Between and Within variations. From \((2.30)\), it is clear that \(\operatorname{var}\left(\widetilde{\beta}_{\text {Within }}\right)-\operatorname{var}\left(\hat{\beta}_{\mathrm{GLS}}\right)\) is a positive semidefinite matrix, since \(\phi^{2}\) is positive. However, as \(T \rightarrow \infty\) for any fixed \(N, \phi^{2} \rightarrow 0\) and both \(\widehat{\beta}_{\mathrm{GLS}}\) and \(\widetilde{\beta}_{\text {Within }}\) have the same asymptotic variance.

Another estimator of the variance components was suggested by Nerlove (1971a). His zuggestion is to estimate \(\sigma^{2}\) as \(\sum^{N} \cdot(\widehat{u} \cdot-\widehat{\pi})^{2} /(N-1)\) where \(\widehat{u}\). are the dummv coefficients estimates from the LSDV regression. \(\sigma_{v}^{2}\) is estimated from the Within residual sums of squares divided by \(N T\) without correction for degrees of freedom. \({ }^{4}\)

Note that, except for Nerlove's (1971a) method, one has to retrieve \(\widehat{\sigma}_{\mu}^{2}\) as \(\left(\widehat{\sigma}_{1}^{2}-\widehat{\sigma}_{v}^{2}\right) / T .\) In this case, there is no guarantee that the estimate of \(\widehat{\sigma}_{\mu}^{2}\) would be nonnegative. Searle (1971) has an extensive discussion of the problem of negative estimates of the variance components in the biometrics literature. One solution is to replace these negative estimates by zero. This in fact is the suggestion of the Monte Carlo study by Maddala and Mount (1973). This study finds that negative estimates occurred only when the true \(\sigma_{\mu}^{2}\) was small and close to zero. In these cases OLS is still a viable estimator. Therefore, replacing negative \(\widehat{\sigma}_{\mu}^{2}\) by zero is not a bad sin after all, and the problem is dismissed as not being serious. \({ }^{5}\)

How about the properties of the various feasible GLS estimators of \(\beta\) Under the random effects model, GLS based on the true variance components is BLUE, and all the feasible GLS estimators considered are asymptotically efficient as either N or \$N \rightarrow \infty \$. Maddala and Mount (1973) compared OLS, Within, Between, feasible GLS methods, MINQUE, Henderson's method III, true GLS and maximum likelihood estimation using their Monte Carlo study. They found little to choose among the various feasible GLS estimators in small samples and argued in favor of methods that were easier to compute. MINQUE was dismissed as more difficult to compute and the applied researcher given one shot at the data was warned to compute at least two methods of estimation, like an ANOVA feasible GLS and maximum likelihood to ensure that they do not yield drastically different results. If they do give different results, the authors diagnose misspecification.

Taylor (1980) derived exact finite sample results for the one-way error component model. He compared the Within estimator with the Swamy--Arora feasible GLS estimator. He found the following important results:

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  Feasible GLS is more efficient than LSDV for all but the fewest degrees of freedom.
\item
  The variance of feasible GLS is never more than 17\% above the Cramer--Rao lower bound.
\item
  More efficient estimators of the variance components do not necessarily yield more efficient feasible GLS estimators.
\end{enumerate}

These finite sample results are confirmed by the Monte Carlo experiments carried out by Maddala and Mount (1973) and Baltagi (1981a).

Bellmann, Breitung and Wagner (1989) consider the bias in estimating the variance components using the Wallace and Hussain (1969) method due to the replacement of the true disturbances by OLS residuals, also the bias in the regression coefficients due to the use of estimated variance components rather than the true variance components. The magnitude of this bias is estimated using bootstrap methods for two economic applications. The first application relates product innovations, import pressure and factor inputs using a panel at the industry level. The second application estimates the earnings of 936 full-time working German males based on the first and second wave of the German Socio-Economic Panel. Only the first application revealed considerable bias in estimating \$\sigma\_\mu\^{}2 \$. However, this did not affect the bias much in the corresponding regression coefficients

\hypertarget{fixed-vs-random}{%
\subsection{Fixed vs Random}\label{fixed-vs-random}}

Having discussed the fixed effects and the random effects models and the assumptions underlying them, the reader is left with the daunting question, which one to choose? This is not as easy a choice as it might seem. In fact, the fixed versus random effects issue has generated a hot debate in the biometrics and statistics literature which has spilled over into the panel data econometrics literature. Mundlak (1961) and Wallace and Hussain (1969) were early proponents of the fixed effects model and Balestra and Nerlove (1966) were advocates of the random error component model. In Chapter 4, we will study a specification test proposed by Hausman (1978) which is based on the difference between the fixed and random effects estimators. Unfortunately, applied researchers have interpreted a rejection as an adoption of the fixed effects model and nonrejection as an adoption of the random effects model.6 Chamberlain (1984) showed that the fixed effects model imposes testable restrictions on the parameters of the reduced form model and one should check the validity of these restrictions before adopting the fixed effects model (see Chapter 4). Mundlak (1978) argued that the random effects model assumes exogeneity of all the regressors with the random individual effects. In contrast, the fixed effects model allows for endogeneity of all the regressors with these individual effects. So, it is an ``all'' or ``nothing'' choice of exogeneity of the regressors and the individual effects, see Chapter 7 for a more formal discussion of this subject.

Hausman and Taylor (1981) allowed for some of the regressors to be correlated with the individual effects, as opposed to the all or nothing choice. These over-identification restrictions are testable using a Hausman-type test (see Chapter 7). For the applied researcher, performing fixed effects and random effects and the associated Hausman test reported in standard packages like Stata, LIMDEP, TSP, etc., the message is clear: Do not stop here. Test the restrictions implied by the fixed effects model derived by Chamberlain (1984) (see Chapter 4) and check whether a Hausman and Taylor (1981) specification might be a viable alternative (see Chapter 7).

\hypertarget{the-two-way-error-component-regression-model}{%
\chapter{The Two-way Error Component Regression Model}\label{the-two-way-error-component-regression-model}}

\hypertarget{ntroduction}{%
\section{NTRODUCTION}\label{ntroduction}}

Wallace and Hussain (1969), Nerlove (1971b) and Amemiya (1971), among others, the regression model given by (2.1), but with two-way error components disturbances: \begin{equation}
u_{i t}=\mu_{i}+\lambda_{t}+v_{i t} \quad i=1, \ldots, N ; t=1, \ldots, T
\end{equation} (3.1)

where \(\mu_i\) denotes the unobservable individual effect discussed in Chapter 2, \(\lambda_t\) denotes the unobservable time effect and \(v_{it}\) is the remainder stochastic disturbance term. Note that \(\lambda_t\) is individual-invariant and it accounts for any time-specific effect that is not included in the regression. For example, it could account for strike year effects that disrupt production; oil embargo effects that disrupt the supply of oil and affect its price; Surgeon General reports on the ill-effects of smoking, or government laws restricting smoking in public places, all of which could affect consumption behavior. In vector form, (3.1) can be written as

\begin{equation}
u=Z_{\mu} \mu+Z_{\lambda} \lambda+v
\end{equation} (3.2)

where \(Z_\mu, \mu\) and \(v\) were defined earlier. \(Z_\lambda = i_N \otimes I_T\) is the matrix of time dummies that one may include in the regression to estimate the \(\lambda_t\) if they are fixed parameters, and \(\lambda^{\prime}= (\lambda_1, ..., \lambda_T )\) Note that \[Z_\lambda Z_\lambda^ {\prime}=J_N \otimes I_T \] and the projection on \(Z_{\lambda}\) is \[Z_{\lambda}\left(Z_{\lambda}^{\prime} Z_{\lambda}\right)^{-1} Z_{\lambda}^{\prime}=\bar{J}_{N} \otimes I_T  \] This last matrix averages the data over individuals, i.e., if we regress y on \(Z_\lambda\), the predicted values are given by \[ (\bar {J_N} \otimes I_T)y \] which has typical element \(\bar{y}_{. t}=\sum_{i=1}^{N} y_{i t} / N\) .

\hypertarget{the-fixed-effects-model-1}{%
\section{THE FIXED EFFECTS MODEL}\label{the-fixed-effects-model-1}}

If the \(\mu_{i}\) and \(\lambda_{t}\) are assumed to be fixed parameters to be estimated and the remainder disturbances stochastic with \(v_{i t} \sim \operatorname{IID}\left(0, \sigma_{v}^{2}\right)\), then (3.1) represents a two-way fixed effects error component model. The \(X_{i t}\) are assumed independent of the \(v_{i t}\) for all \(i\) and \(t\). Inference in this case is conditional on the particular \(N\) individuals and over the specific time periods observed. Recall that \(Z_{\lambda}\), the matrix of time dummies, is \(N T \times T\). If \(N\) or \(T\) is large, there will be too many dummy variables in the regression \(\{(N-1)+(T-1)\}\) of them, and this causes an enormous loss in degrees of freedom. In addition, this attenuates the problem of multicollinearity among the regressors. Rather than invert a large \((N+T+K-1)\) matrix, one can obtain the fixed effects estimates of \(\beta\) by performing the following Within transformation given by Wallace and Hussain (1969):

\begin{equation}
Q=E_{N} \otimes E_{T}=I_{N} \otimes I_{T}-I_{N} \otimes \bar{J}_{T}-\bar{J}_{N} \otimes I_{T}+\bar{J}_{N} \otimes \bar{J}_{T}
\end{equation} (3.3)

where \(E_{N}=I_{N}-\bar{J}_{N}\) and \(E_{T}=I_{T}-\bar{J}_{T}\). This transformation ``sweeps'' the \(\mu_{i}\) and \(\lambda_{t}\) effects. In fact, \(\tilde{y}=Q y\) has a typical element \(\tilde{y}_{i t}=\left(y_{i t}-\bar{y}_{i .}-\bar{y}_{i t}+\bar{y} . .\right)\) where \(\bar{y}_{. .}=\sum_{i} \sum_{t} y_{i t} /\) \(N T\), and one would perform the regression of \(\tilde{y}=Q y\) on \(\widetilde{X}=Q X\) to get the Within estimator \(\widetilde{\beta}=\left(X^{\prime} Q X\right)^{-1} X^{\prime} Q y\)

Note that by averaging the simple regression given in (2.8) over individuals, we get

\begin{equation}
\bar{y}_{. t}=\alpha+\beta \bar{x}_{. t}+\lambda_{t}+\bar{v}_{. t}
\end{equation} (3.4)

where we have utilized the restriction that \(\sum_i \mu_i=0\) to avoid the dummy variable trap.
Similarly the averages defined in (2.9) and (2.11) still hold using \(\sum_t \lambda_t=0\) and one can deduce that

\begin{equation}
\left(y_{i t}-\bar{y}_{i .}-\bar{y}_{. t}+\bar{y}_{. .}\right)=\left(x_{i t}-\bar{x}_{i .}-\bar{x}_{. t}+\bar{x}_{. .}\right) \beta+\left(v_{i t}-\bar{v}_{i .}-\bar{v}_{. t}+\bar{v}_{. .}\right)
\end{equation} (3.5)

OLS on this model gives \(\widetilde {\beta}\) the Within estimator for the two-way model. Once again, the
Within estimate of the intercept can be deduced from
\[\widetilde {\alpha}=\bar{y}_..-\widetilde {\beta} \bar{x}  \]
and those of \(\mu_i\) and \(\lambda_i\) are given by

\begin{equation}
\tilde{\mu}_{i}=\left(\bar{y}_{i .}-\bar{y}_{. .}\right)-\widetilde{\beta}\left(\bar{x}_{i .}-\bar{x}_{. .}\right)
\end{equation} (3.6)

\begin{equation}
\tilde{\lambda}_{t}=\left(\bar{y}_{. t}-\bar{y}_{. .}\right)-\widetilde{\beta}\left(\bar{x}_{. t}-\bar{x}_{. .}\right)
\end{equation} (3.7)

Note that the Within estimator cannot estimate the effect of time-invariant and individualinvariant variables because the Q transformation wipes out these variables. If the true model
is a two-way fixed effects model as in (3.2), then OLS on (2.1) yields biased and inconsistent estimates of the regression coefficients. OLS ignores both sets of dummy variables, whereas the one-way fixed effects estimator considered in Chapter 2 ignores only the time dummies. If
these time dummies are statistically significant, the one-way fixed effects estimator will also
suffer from omission bias.

\hypertarget{testing-for-fixed-effects}{%
\subsection{Testing for Fixed Effects}\label{testing-for-fixed-effects}}

As in the one-way error component model case, one can test for joint significance of the dummy
variables:

\[
H_{0}: \mu_{1}=\ldots=\mu_{N-1}=0 \quad \text { and } \quad \lambda_{1}=\ldots=\lambda_{T-1}=0
\]
The restricted residual sums of squares (RRSS) is that of pooled OLS and the unrestricted residual sums of squares (URSS) is that from the Within regression in (3.5). In this case,

\begin{equation}
F_{1}=\frac{(\mathrm{RRSS}-\mathrm{URSS}) /(N+T-2)}{\mathrm{URSS} /(N-1)(T-1)-K} \stackrel{H_{0}}{\sim} F_{(N+T-2),(N-1)(T-1)-K}
\end{equation} (3.8)

Next, one can test for the existence of individual effects allowing for time effects, i.e.
\(H_{2}: \mu_{1}==u_{N}=0 \quad\) allowing \(\quad \lambda \neq 0\) for \(t=1 \ldots \quad T-1\)

The URSS is still the Within residual sum of squares. However, the RRSS is the regression with time-series dummies only, or the regression based upon

\begin{equation}
\left(y_{i t}-\bar{y}_{. t}\right)=\left(x_{i t}-\bar{x}_{. t}\right) \beta+\left(u_{i t}-\bar{u}_{. t}\right)
\end{equation} (3.9)

In this case the resulting \(F\) -statistic is \(F_{2} \stackrel{H_{0}}{\sim} F_{(N-1),(N-1)(T-1)-K}\). Note that \(F_{2}\) differs from \(F_{0}\) in ( \(2.12\) ) in testing for \(\mu_{i}=0\). The latter tests \(H_{0}: \mu_{i}=0\) assuming that \(\lambda_{t}=0\), whereas the former tests \(H_{2}: \mu_{i}=0\) allowing \(\lambda_{t} \neq 0\) for \(t=1, \ldots, T-1\). Similarly, one can test for the existence of time effects allowing for individual effects, i.e.

\begin{equation}
H_{3}: \lambda_{1}=\ldots=\lambda_{T-1}=0 \quad \text { allowing } \quad \mu_{i} \neq 0 ; i=1, \ldots,(N-1)
\end{equation}

The RRSS is given by the regression in (2.10), while the URSS is obtained from the regression
(3.5). In this case, the resulting F-statistic is \(F_{3} \sim^{H_{0}} F_{(T-1),(N-1)(T-1)-K}\) .

\emph{Computational Warning}

As in the one-way model, \(s^2\) from the regression in (3.5) as obtained from any standard regression package has to be adjusted for loss of degrees of freedom. In this case, one divides by\$ (N − 1)(T − 1) − K \$ and multiplies by \$(NT − K) \$to get the proper variance--covariance matrix of the Within estimator.

\hypertarget{the-random-effects-model-1}{%
\section{THE RANDOM EFFECTS MODEL}\label{the-random-effects-model-1}}

If \(\mu_{i} \sim \operatorname{IID}\left(0, \sigma_{\mu}^{2}\right), \lambda_{t} \sim \operatorname{IID}\left(0, \sigma_{\lambda}^{2}\right)\) and \(v_{i t} \sim \operatorname{IID}\left(0, \sigma_{v}^{2}\right)\) independent of each other, then this
is the two-way random effects model. In addition, \(X_{i t}\) is independent of \(\mu_{i}, \lambda_{t}\) and \(v_{i t}\) for all \(i\) and \(t\). Inference in this case pertains to the large population from which this sample was randomly drawn. From (3.2), one can compute the variance-covariance matrix

\begin{equation}
\begin{aligned}
\Omega &=E\left(u u^{\prime}\right)=Z_{\mu} E\left(\mu \mu^{\prime}\right) Z_{\mu}^{\prime}+Z_{\lambda} E\left(\lambda \lambda^{\prime}\right) Z_{\lambda}^{\prime}+\sigma_{v}^{2} I_{N T} \\
&=\sigma_{\mu}^{2}\left(I_{N} \otimes J_{T}\right)+\sigma_{\lambda}^{2}\left(J_{N} \otimes I_{T}\right)+\sigma_{v}^{2}\left(I_{N} \otimes I_{T}\right)
\end{aligned}
\end{equation} (3.10)

The disturbances are homoskedastic with \(\operatorname{var}\left(u_{i t}\right)=\sigma_{\mu}^{2}+\sigma_{\lambda}^{2}+\sigma_{v}^{2}\) for all \(i\) and \(t\),

\begin{equation}
\begin{array}{rl}
\operatorname{cov}\left(u_{i t}, u_{j s}\right)=\sigma_{\mu}^{2} & i=j, t \neq s \\
=\sigma_{\lambda}^{2} & i \neq j, t=s
\end{array}
\end{equation} (3.11)

and zero otherwise. This means that the correlation coefficient

\begin{equation}
\begin{aligned}
\operatorname{correl}\left(u_{i t}, u_{j s}\right) &=\sigma_{\mu}^{2} /\left(\sigma_{\mu}^{2}+\sigma_{\lambda}^{2}+\sigma_{v}^{2}\right) & & i=j, t \neq s \\
&=\sigma_{\lambda}^{2} /\left(\sigma_{\mu}^{2}+\sigma_{\lambda}^{2}+\sigma_{v}^{2}\right) & & i \neq j, t=s \\
&=1 & & i=j, t=s \\
&=0 & & i \neq j, t \neq s
\end{aligned}
\end{equation} (3.12)

In order to get \(\Omega^{-1}\), we replace \(J_{N}\) by \(N \bar{J}_{N}, I_{N}\) by \(E_{N}+\bar{J}_{N}, J_{T}\) by \(T \bar{J}_{T}\) and \(I_{T}\) by \(E_{T}+\bar{J}_{T}\) and collect terms with the same matrices. This gives

\begin{equation}
\Omega=\sum_{i=1}^{4} \lambda_{i} Q_{i}
\end{equation} (3.13)

where \(\lambda_{1}=\sigma_{v}^{2}, \lambda_{2}=T \sigma_{\mu}^{2}+\sigma_{v}^{2}, \lambda_{3}=N \sigma_{\lambda}^{2}+\sigma_{v}^{2}\) and \(\lambda_{4}=T \sigma_{\mu}^{2}+N \sigma_{\lambda}^{2}+\sigma_{v}^{2}\). Correspond-
ingly, \(Q_{1}=E_{N} \otimes E_{T}, Q_{2}=E_{N} \otimes \bar{J}_{T}, Q_{3}=\bar{J}_{N} \otimes E_{T}\) and \(Q_{4}=\bar{J}_{N} \otimes \bar{J}_{T}\), respectively.
The \(\lambda_{i}\) are the distinct characteristic roots of \(\Omega\) and the \(Q_{i}\) are the corresponding matrices of eigenprojectors. \(\lambda_{1}\) is of multiplicity \((N-1)(T-1), \lambda_{2}\) is of multiplicity \((N-1), \lambda_{3}\) is of multiplicity \((T-1)\) and \(\lambda_{4}\) is of multiplicity \(1 .{ }^{1}\) Each \(Q_{i}\) is symmetric and idempotent with its rank equal to its trace. Moreover, the \(Q_{i}\) are pairwise orthogonal and sum to the identity matrix. The advantages of this spectral decomposition are that

\begin{equation}
\Omega^{r} =\sum_{i=1}^{4} \lambda_{i}^{r} Q_{i}
\end{equation} (3.14)

where \(r\) is an arbitrary scalar so that

\begin{equation}
\sigma_{v} \Omega^{-1 / 2}=\sum_{i=1}^{4}\left(\sigma_{v} / \lambda_{i}^{1 / 2}\right) Q_{i}
\end{equation} (3.15)

and the typical element of \(y^{*}=\sigma_{\nu} \Omega^{-1 / 2} y\) is given by

\begin{equation}
y_{i t}^{*}=y_{i t}-\theta_{1} \bar{y}_{i .}-\theta_{2} \bar{y}_{. t}+\theta_{3} \bar{y}_{. .}
\end{equation} (3.16)

where \(\theta_{1}=1-\left(\sigma_{v} / \lambda_{2}^{1 / 2}\right), \theta_{2}=1-\left(\sigma_{v} / \lambda_{3}^{1 / 2}\right)\) and \(\theta_{3}=\theta_{1}+\theta_{2}+\left(\sigma_{v} / \lambda_{4}^{1 / 2}\right)-1\). As a result,
GLS can be obtained as OLS of \(y^{*}\) on \(Z^{*}\), where \(Z^{*}=\sigma_{\nu} \Omega^{-1 / 2} Z\). This transformation was first derived by Fuller and Battese (1974), see also Baltagi (1993).

The best quadratic unbiased (BQU) estimators of the variance components arise naturally from the fact that \(Q_{i} u \sim\left(0, \lambda_{i} Q_{i}\right) .\) Hence,

\begin{equation}
\widehat{\lambda}_{i}=u^{\prime} Q_{i} u / \operatorname{tr}\left(Q_{i}\right)
\end{equation} (3.17)

is the BQU estimator of \(\lambda_{i}\) for \(i=1,2,3\). These ANOVA estimators are minimum variance unbiased (MVU) under normality of the disturbances (see Graybill, 1961 ). As in the one-way error component model, one can obtain feasible estimates of the variance components by replacing the true disturbances by OLS residuals (see Wallace and Hussain, 1969 ). OLS is still an unbiased and consistent estimator under the random effects model, but it is inefficient and results in biased standard errors and \(t\) -statistics. Alternatively, one could substitute the Within residuals with \(\tilde{u}=y-\widetilde{\alpha} \iota_{N T}-X \widetilde{\beta}\), where \(\tilde{\alpha}=\bar{y}_{. .}-\bar{X}_{. .}^{\prime} \tilde{\beta}\) and \(\widetilde{\beta}\) is obtained by the regression
in (3.5). This is the method proposed by Amemiya (1971). In fact, Amemiya (1971) shows that the Wallace and Hussain (1969) estimates of the variance components have a different asymptotic distribution from that knowing the true disturbances, while the Amemiya (1971) estimates of the variance components have the same asymptotic distribution as that knowing the true disturbances:

\begin{equation}
\left(\begin{array}{c}
\sqrt{N T}\left(\widehat{\sigma}_{v}^{2}-\sigma_{v}^{2}\right) \\
\sqrt{N}\left(\widehat{\sigma}_{\mu}^{2}-\sigma_{\mu}^{2}\right) \\
\sqrt{T}\left(\widehat{\sigma}^{2}-\sigma_{\mu}^{2}\right)
\end{array}\right) \sim N\left(0,\left(\begin{array}{ccc}
2 \sigma_{v}^{4} & 0 & 0 \\
0 & 2 \sigma_{\mu}^{4} & 0 \\
0 & 0 & 2 \sigma^{4}
\end{array}\right)\right)
\end{equation} (3.18)

SubstitutingOLSorWithin residuals instead of the true disturbances in (3.17) introduces bias in
the corresponding estimates of the variance components. The degrees of freedom corrections
that make these estimates unbiased depend upon traces of matrices that involve the matrix
of regressors X. These corrections are given in Wallace and Hussain (1969) and Amemiya
(1971), respectively. Alternatively, one can infer these correction terms from the more general
unbalanced error component model considered in Chapter 9.
Swamy and Arora (1972) suggest running three least squares regressions and estimating
the variance components from the corresponding mean square errors of these regressions. The
first regression corresponds to the Within regression which transforms the original model by
\(Q_1=E_N \otimes E_T\) . This is equivalent to the regression in (3.5), and yields the following estimate
of \(\sigma_v^2\) :

\begin{equation}
\widehat{\lambda}_{1}=\widehat{\sigma}_{v}^{2}=\left[y^{\prime} Q_{1} y-y^{\prime} Q_{1} X\left(X^{\prime} Q_{1} X\right)^{-1} X^{\prime} Q_{1} y\right] /[(N-1)(T-1)-K]
\end{equation} (3.19)\\
( à arranger)

The second regression is the Between individuals regression which transforms the original
model by \[Q_2=E_N \otimes \bar{J}_T \] This is equivalent to the regression of \[ (\bar{y}_{i.}- \bar{y}_{i..}) \] on
\[ (\bar{X}_{i.}- \bar{X}_{i..}) \]
and yields the following estimate of
\$ \lambda\_2=T\sigma\_v\^{}2 + \sigma\_v\^{}2 \$:

\begin{equation}
\widehat{\lambda}_{2}=\left[y^{\prime} Q_{2} y-y^{\prime} Q_{2} X\left(X^{\prime} Q_{2} X\right)^{-1} X^{\prime} Q_{2} y\right] /[(N-1)-K]
\end{equation} (3.20)

from which one obtains \(\widehat{\sigma}_{\mu}^{2}=\left(\widehat{\lambda}_{2}-\widehat{\sigma}_{v}^{2}\right) / T .\) The third regression is the Between time-periods regression which transforms the original model by \(Q_{3}=\bar{J}_{N} \otimes E_{T}\). This is equivalent to the regression of \(\left(\bar{y}_{. t}-\bar{y}_{. .}\right)\) on \(\left(\bar{X}_{. t}-\bar{X}_{. .}\right)\) and yields the following estimate of \(\lambda_{3}=N \sigma_{\lambda}^{2}+\sigma_{v}^{2}\)

\begin{equation}
\widehat{\lambda}_{3}=\left[y^{\prime} Q_{3} y-y^{\prime} Q_{3} X\left(X^{\prime} Q_{3} X\right)^{-1} X^{\prime} Q_{3} y\right] /[(T-1)-K]
\end{equation} (3.21)

from which one obtains
\[ (\widehat{\widehat {\sigma_\lambda^2} }= \widehat{\widehat {\lambda} }_3 -  \widehat{\widehat {\lambda} }_v)/N \] Stacking the three transformed regressions just
performed yields

\begin{equation}
\left(\begin{array}{l}
Q_{1} y \\
Q_{2} y \\
Q_{3} y
\end{array}\right)=\left(\begin{array}{l}
Q_{1} X \\
Q_{2} X \\
Q_{3} X
\end{array}\right) \beta+\left(\begin{array}{l}
Q_{1} u \\
Q_{2} u \\
Q_{3} u
\end{array}\right)
\end{equation} (3.22)

since \(Q_{i} \iota_{N T}=0\) for \(i=1,2,3\), and the transformed error has mean 0 and variance-covariance matrix given by \(\operatorname{diag}\left[\lambda_{i} Q_{i}\right]\) with \(i=1,2,3 .\) Problem \(3.4\) asks the reader to show that \(\mathrm{OLS}\) on this system of \(3 N T\) observations yields the same estimator of \(\beta\) as OLS on the pooled model (2.3). Also, GLS on this system of equations (3.22) yields the same estimator of \(\beta\) as GLS on (2.3). In fact,

\begin{equation}
\begin{aligned}
\widehat{\beta}_{\mathrm{GLS}}=&\left[\left(X^{\prime} Q_{1} X\right) / \sigma_{v}^{2}+\left(X^{\prime} Q_{2} X\right) / \lambda_{2}+\left(X^{\prime} Q_{3} X\right) / \lambda_{3}\right]^{-1} \\
& \times\left[\left(X^{\prime} Q_{1} y\right) / \sigma_{v}^{2}+\left(X^{\prime} Q_{2} y\right) / \lambda_{2}+\left(X^{\prime} Q_{3} y\right) / \lambda_{3}\right] \\
=&\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1}\left[W_{X y}+\phi_{2}^{2} B_{X y}+\phi_{3}^{2} C_{X y}\right]
\end{aligned}
\end{equation} (3.23)

with \(\operatorname{var}\left(\widehat{\beta}_{\mathrm{GLS}}\right)=\sigma_{v}^{2}\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1}\). Note that \(W_{X X}=X^{\prime} Q_{1} X, B_{X X}=X^{\prime} Q_{2} X\)
and \(C_{X X}=X^{\prime} Q_{3} X\) with \(\phi_{2}^{2}=\sigma_{v}^{2} / \lambda_{2}, \phi_{3}^{2}=\sigma_{v}^{2} / \lambda_{3} .\) Also, the Within estimator of \(\beta\) is \(\widetilde{\beta}_{W}=\)
\(W_{X X}^{-1} W_{X y}\), the Between individuals estimator of \(\beta\) is \(\widehat{\beta}_{B}=B_{X X}^{-1} B_{X y}\) and the Between timeperiods estimator of \(\beta\) is \(\widehat{\beta}_{C}=C_{X X}^{-1} C_{X y}\). This shows that \(\widehat{\beta}_{\mathrm{GLS}}\) is a matrix-weighted average of \(\widetilde{\beta}_{W}, \widehat{\beta}_{B}\) and \(\widehat{\beta}_{C}\). In fact,

\begin{equation}
\widehat{\beta}_{\mathrm{GLS}}=W_{1} \widetilde{\beta}_{W}+W_{2} \widehat{\beta}_{B}+W_{3} \widehat{\beta}_{C}
\end{equation} (3.24)

where

\begin{equation}
\begin{aligned}
&W_{1}=\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1} W_{X X} \\
&W_{2}=\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1}\left(\phi_{2}^{2} B_{X X}\right) \\
&W_{3}=\left[W_{X X}+\phi_{2}^{2} B_{X X}+\phi_{3}^{2} C_{X X}\right]^{-1}\left(\phi_{3}^{2} C_{X X}\right)
\end{aligned}
\end{equation}

This was demonstrated by Maddala (1971). Note that (i) if \(\sigma_{\mu}^{2}=\sigma_{\lambda}^{2}=0, \phi_{2}^{2}=\phi_{3}^{2}=1\) and \(\widehat{\beta}_{\mathrm{GLS}}\) reduces to \(\widehat{\beta}_{\mathrm{OLs}}\); (ii) as \(T\) and \(N \rightarrow \infty, \phi_{2}^{2}\) and \(\phi_{3}^{2} \rightarrow 0\) and \(\widehat{\beta}_{\mathrm{GLS}}\) tends to \(\widetilde{\beta}_{W}\); (iii) if
\(\phi_{2}^{2} \rightarrow \infty\) with \(\phi_{3}^{2}\) finite, then \(\widehat{\beta}_{\mathrm{GLS}}\) tends to \(\widehat{\beta}_{B}\); (iv) if \(\phi_{3}^{2} \rightarrow \infty\) with \(\phi_{2}^{2}\) finite, then \(\widehat{\beta}_{\text {GLS }}\) tends to \(\widehat{\beta}_{C}\).
Wallace and Hussain (1969) compare \(\widehat{\beta}_{\mathrm{GLS}}\) and \(\widetilde{\beta}_{\text {Within }}\) in the case of nonstochastic (repetitive) \(X\) and find that both are (i) asymptotically normal, (ii) consistent and unbiased and that

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  \(\widehat{\beta}_{\mathrm{GLS}}\) has a smaller generalized variance (i.e.~more efficient) in finite samples. In the case of nonstochastic (nonrepetitive) \(X\) they find that both \(\widehat{\beta}_{\mathrm{GLS}}\) and \(\widetilde{\beta}_{\text {Within }}\) are consistent, asymptotically unbiased and have equivalent asymptotic variance-covariance matrices, as both \(N\) and \(T \rightarrow \infty\). The last statement can be proved as follows: the limiting variance of the GLS estimator is
\end{enumerate}

\begin{equation}
\frac{1}{N T} \lim _{N \rightarrow \infty \atop T \rightarrow \infty}\left(X^{\prime} \Omega^{-1} X / N T\right)^{-1}=\frac{1}{N T} \lim _{N \rightarrow \infty \atop T \rightarrow \infty}\left[\sum_{i=1}^{3} \frac{1}{\lambda_{i}}\left(X^{\prime} Q_{i} X / N T\right)\right]^{-1}
\end{equation} (3.25)

but the limit of the inverse is the inverse of the limit, and

\begin{equation}
\lim _{N \rightarrow \infty \atop T \rightarrow \infty} \frac{X^{\prime} Q_{i} X}{N T} \quad \text { for } i=1,2,3
\end{equation} (3.26)

all exist and are positive semidefinite, since \[\lim _{N \rightarrow \infty \atop T \rightarrow \infty}\left(X^{\prime} X / N T\right)\] is assumed finite and positive definite. Hence

\[
\lim _{N \rightarrow \infty \atop T \rightarrow \infty} \frac{1}{\left(N \sigma_{\lambda}^{2}+\sigma_{v}^{2}\right)}\left(\frac{X^{\prime} Q_{3} X}{N T}\right)=0
\]

and
\[
\lim _{N \rightarrow \infty \atop T \rightarrow \infty} \frac{1}{\left(T \sigma_{\mu}^{2}+\sigma_{v}^{2}\right)}\left(\frac{X^{\prime} Q_{2} X}{N T}\right)=0
\]
Therefore the limiting variance of the GLS estimator becomes
\[
\frac{1}{N T} \lim _{N \rightarrow \infty \atop T \rightarrow \infty} \sigma_{v}^{2}\left(\frac{X^{\prime} Q_{1} X}{N T}\right)^{-1}
\]

which is the limiting variance of the Within estimator. One can extend Nerlove's (1971a) method for the one-way model, by estimating \(\sigma_{\mu}^{2}\) as \(\sum_{i=1}^{N}\left(\widehat{\mu}_{i}-\widehat{\mu}\right)^{2} /(N-1)\) and \(\sigma_{\lambda}^{2}\) as \(\sum_{t=1}^{T}\left(\widehat{\lambda}_{t}-\bar{\lambda}\right)^{2} /(T-1)\) where the \(\widehat{\mu}_{i}\) and \(\widehat{\lambda}_{t}\) are obtained
as coefficients from the least squares dummy variables regression (LSDV). \(\sigma_{v}^{2}\) is estimated from the Within residual sums of squares divided by \(N T\). Baltagi (1995, appendix 3) develops two other methods of estimating the variance components. The first is Rao's (1970) minimum norm quadratic unbiased estimation (MINQUE) and the second is Henderson's method III as described by Fuller and Battese (1973). These methods require more notation and development and may be skipped in a brief course on this subject. Chapter 9 studies these estimation methods in the context of an unbalanced error component model.

Baltagi (1981a) performed a Monte Carlo study on a simple regression equation with twoway error component disturbances and studied the properties of the following estimators:
OLS, the Within estimator and six feasible GLS estimators denoted by WALHUS, AMEMIYA, SWAR, MINQUE, FUBA and NERLOVE corresponding to the methods developed by Wallace and Hussain (1969), Amemiya (1971), Swamy and Arora (1972), Rao (1972), Fuller and Battese (1974) and Nerlove (1971a), respectively. The mean square error of these estimators was computed relative to that of true GLS, i.e.~GLS knowing the true variance components. To review some of the properties of these estimators: OLS is unbiased, but asymptotically inefficient, and its standard errors are biased; see Moulton (1986) for the extent of this bias in empirical applications. In contrast, the Within estimator is unbiased whether or not prior

information about the variance components is available. It is also asymptotically equivalent to the GLS estimator in case of weakly nonstochastic exogenous variables. Early in the literature, Wallace and Hussain (1969) recommended the Within estimator for the practical researcher, based on theoretical considerations but more importantly for its ease of computation. In Wallace and Hussain's (1969, p.~66) words the ``covariance estimators come off with a surprisingly clear bill of health''. True GLS is BLUE, but the variance components are usually not known and have to be estimated. All of the feasible GLS estimators considered are asymptotically efficient. In fact, Prucha (1984) showed that as long as the estimate of \(\sigma_{v}^{2}\) is consistent, and the probability limits of the estimates \(\sigma_{\mu}^{2}\) and \(\sigma_{\lambda}^{2}\) are finite, the corresponding feasible GLS estimator is asymptotically efficient. Also, Swamy and Arora (1972) proved the existence of a family of asymptotically efficient two-stage feasible GLS estimators of the regression coefficients. Therefore, based on asymptotics only, one cannot differentiate among these twostage GLS estimators. This leaves undecided the question of which estimator is the best to use. Some analytical results were obtained by Swamy (1971) and Swamy and Arora (1972). These studies derived the relative efficiencies of (i) SWAR with respect to OLS, (ii) SWAR with respect to Within and (iii) Within with respect to OLS. Then, for various values of \(N, T\), the variance components, the Between groups, Between time-periods and Within groups sums of squares of the independent variable, they tabulated these relative efficiency values (see Swamy, 1971 , chapters II and III; Swamy and Arora, 1972, p.~272). Among their basic findings is the fact that, for small samples, SWAR is less efficient than OLS if \(\sigma_{\mu}^{2}\) and \(\sigma_{\lambda}^{2}\) are small. Also, SWAR is less efficient than Within if \(\sigma_{\mu}^{2}\) and \(\sigma_{\lambda}^{2}\) are large. The latter result is disconcerting, since Within, which uses only a part of the available data, is more efficient than SWAR, a feasible GLS estimator, which uses all of the available data.

\hypertarget{references}{%
\section{REFERENCES}\label{references}}

\hypertarget{test-of-hypotheses-with-panel-data}{%
\chapter{Test of Hypotheses with Panel Data}\label{test-of-hypotheses-with-panel-data}}

\hypertarget{tests-for-poolability-of-the-data}{%
\section{TESTS FOR POOLABILITY OF THE DATA}\label{tests-for-poolability-of-the-data}}

The question of whether to pool the data or not naturally arises with panel data. The restricted model is the pooled model given by (2.3) representing a behavioral equation with the same parameters over time and across regions. The unrestricted model, however, is the same behavioral equation but with different parameters across time or across regions. For example, Balestra and Nerlove (1966) considered a dynamic demand equation for natural gas across 36 states over six years. In this case, the question of whether to pool or not to pool boils down to the question of whether the parameters of this demand equation vary from one year to the other over the six years of available data. One can have a behavioral equation whose parameters may vary across regions. For example, Baltagi and Griffin (1983) considered panel data on motor gasoline demand for 18 OECD countries. In this case, one is interested in testing whether the behavioral relationship predicting demand is the same across the 18 OECD countries, i.e.~the parameters of the prediction equation do not vary from one country to the other.

These are but two examples of many economic applications where time-series and crosssection data may be pooled. Generally, most economic applications tend to be of the first type, i.e.~with a large number of observations on individuals, firms, economic sectors, regions, industries and countries but only over a few time periods. In what follows, we study the tests for the poolability of the data for the case of pooling across regions keeping in mind that the other case of pooling over time can be obtained in a similar fashion.
For the unrestricted model, we have a regression equation for each region given by

\begin{equation}
  y_i=Z_i \delta _i + \mu_i \text{i=1,2,...,N}
\end{equation} (4.1)

where \[ y^{\prime}=(y_i1,...,y_{iT}) \], \(Z_i=[i_T,X_i]\) ans \(X_i\) is \$T \times K \$ .

The important thing to notice is that \(\delta_{1}\) is different for every regional equation. We want to test the hypothesis \(H_{0}: \delta_{l}=\delta\) for all \(i\), so that undcr \(H_{0}\) we can write the restricted model given in \((4.1)\) as

\begin{equation}
y= Z \delta + \mu
\end{equation}

where \[ Z^{\prime}=\left(Z_{1}^{\prime} , Z_{2}^{\prime}, \ldots, Z_{N}^{\prime}\right) \] and \[ u^{\prime}=\left(u_{1}^{\prime}, u_{2}^{\prime}, \ldots, u_{N}^{\prime}\right) \] . The unrestricted model can also be written as

\begin{equation}
y=\left(\begin{array}{cccc}
Z_{1} & 0 & \ldots & 0 \\
0 & Z_{2} & \ldots & 0 \\
\vdots & & \ddots & \vdots \\
0 & 0 & \ldots & Z_{N}
\end{array}\right)\left(\begin{array}{c}
\delta_{1} \\
\delta_{2} \\
\vdots \\
\delta_{N}
\end{array}\right)+u=Z^{*} \delta^{*}+u
\end{equation}

where \[\delta^{* \prime}=\left(\delta_{1}^{\prime}, \delta_{2}^{\prime}, \ldots, \delta_{N}^{\prime}\right)\] and \[ Z=Z^{*} I^{*} \] with \[ I^{*}=\left(\iota_{N} \otimes I_{K^{\prime}}\right)\], an \[ N K^{\prime} \times K^{\prime}\] matrix, with
\[K^{\prime}=K+1 \] . Hence the variables in Z are all linear combinations of the variables in \[ Z^{*}\] .

\hypertarget{test-for-poolability-under}{%
\subsection{Test for Poolability under}\label{test-for-poolability-under}}

\[ u \sim N\left(0, \sigma^{2} I_{N T}\right)\]

Assumption 4. 1 \[\mu   \sim N\left(0, \sigma^{2} I_{N T}\right)\]

Under assumption 4.1, the minimum variance unbiased estimator for \(\delta\) in equation (4.2) is

\begin{equation}
\widehat{\delta}_{\mathrm{OLS}}=\widehat{\delta}_{m l e}=\left(Z^{\prime} Z\right)^{-1} Z^{\prime} y
\end{equation}

and therefore

\begin{equation}
y=Z \widehat{\delta}_{\mathrm{OLS}}+e
\end{equation}

implying that \[e=\left(I_{NT}-Z \left(Z Z^{\prime}\right)^{-1}Z^{\prime}\right)y =My=M\left(Z\delta +\mu \right)= M \mu \] since \(MZ=0\). Similarly,
under assumption 4.1, the MVU for \(\delta_i\) is given by

\begin{equation}
\widehat{\delta}_{i, \mathrm{OLS}}=\widehat{\delta}_{i, m l e}=\left(Z_{i}^{\prime} Z_{i}\right)^{-1} Z_{i}^{\prime} y_{i}
\end{equation}

therefore

\begin{equation}
y_{i}=Z_{i} \widehat{\delta}_{i, \mathrm{OLS}}+e_{i}
\end{equation}

implying that \[ e_{i}=\left(I_{T}-Z_{i}\left(Z_{i}^{\prime} Z_{i}\right)^{-1} Z_{i}^{\prime}\right) y_{i}=M_{i} y_{i}=M_{i}\left(Z_{i} \delta_{i}+u_{i}\right)=M_{i} u_{i}\] since \$M\_\{i\} Z\_\{i\}=0 \$ and this is true for \(i=1,2, \ldots, N\) . Also, let

\[
M^{*}=I_{N T}-Z^{*}\left(Z^{* \prime} Z^{*}\right)^{-1} Z^{* \prime}=\left(\begin{array}{cccc}
M_{1} & 0 & \ldots & 0 \\
0 & M_{2} & \ldots & 0 \\
\vdots & & \ddots & \vdots \\
0 & 0 & \ldots & M_{N}
\end{array}\right)
\]

One can easily deduce that \(y=Z^{*} \widehat{\delta}^{*}+e^{*}\) with \(e^{*}=M^{*} y=M^{*} u\) and \(\widehat{\delta}^{*}=\left(Z^{* \prime} Z^{*}\right)^{-1} Z^{* \prime} y\).
Note that both \(M\) and \(M^{*}\) are symmetric and idempotent with \(M M^{*}=M^{*}\). This easily follows since

\begin{equation}
\begin{aligned}
Z\left(Z^{\prime} Z\right)^{-1} Z^{\prime} Z^{*}\left(Z^{* \prime} Z^{*}\right)^{-1} Z^{* \prime} &=Z\left(Z^{\prime} Z\right)^{-1} I^{* \prime} Z^{* \prime} Z^{*}\left(Z^{* \prime} Z^{*}\right)^{-1} Z^{* \prime} \\
&=Z\left(Z^{\prime} Z\right)^{-1} Z^{\prime}
\end{aligned}
\end{equation} (Non Numéroté)

This uses the fact that \(Z=Z^{*} I^{*} .\) Under assumption 4.1, \(e^{\prime} e-e^{* \prime} e^{*}=u^{\prime}\left(M-M^{*}\right) u\) and \(e^{* \prime} e^{*}=u^{\prime} M^{*} u\) are independent since \(\left(M-M^{*}\right) M^{*}=0 .\) Also, both quadratic forms when divided by \(\sigma^{2}\) are distributed as \(\chi^{2}\) since \(\left(M-M^{*}\right)\) and \(M^{*}\) are idempotent. Dividing these quadratic forms by their respective degrees of freedom and taking their ratio leads to the following test statistic: \({ }^{1}\)

\[F_{obs}=\frac{\left(e^{\prime}e-e^{* \prime} \right) / \left( \operatorname{tr}\left(M\right)-\operatorname{tr}\left(M^*\right) \right)}
{e^{* \prime}e^* / \operatorname{tr}\left(M\right) }  \]

\begin{equation}
F_{obs}=\frac{\left(e_1^{\prime}e-e_2^{\prime}e_1 -e^{\prime}e_2 -\ldots -e_N^{\prime}e \right)/ \left(N-1 \right) K^{\prime}  }
{\left(e_1^{\prime}e-e_2^{\prime}e_1 -e^{\prime}e_2 -\ldots -e_N^{\prime}e \right)/ N \left(T-K^{\prime} \right) } 
\end{equation}

Under \(H_0,F_{obs}\) is distributed as an \[F \left(\left(N-1 \right)K^{\prime}, N\left(T-K^{\prime}\right)\right) \] Hence the critical region for this test is defined as

\[\brace  F_{obs}> \left(\left(N-1 \right)K^{\prime}, NT-NK^{\prime} ,\alpha_0 \right)      \]
where \(\alpha_0\) denotes the level of significance of the test. This is exactly the Chow test presented by Chow (1960) extended to the case of \(N\) linear regressions. Therefore if an economist has reason to believe that assumption 4.1 is true, and wants to pool his data across regions, then it is recommended that he or she test for the poolability of the data using the Chow test given in (4.8). However, for the variance component model \(\mu \sim \left(0,\Omega \right)\) and not \(\left(0,\sigma^2 I_{NT} \right)\) Therefore, even if we assume normality on the disturbances two questions remain: (1) is the Chow test still the right test to perform when \(\mu \sim N\left(0,\Omega \right)\) ? and (2) does the Chow statistic still have an
F-distribution when \(\mu \sim N\left(0,\Omega \right)\) ? The answer to the first question is no, the Chow test given
in (4.8) is not the right test to perform. However, as will be shown later, a generalized Chow
test will be the right test to perform. As for the second question, it is still relevant to ask because
it highlights the problem of economists using the Chow test assuming erroneously that \(\mu\) is \(N\left(0,\sigma^2 I_{NT} \right)\) when in fact it is not. For example, Toyoda (1974), in treating the case where
the \(\mu_i\) are heteroskedastic, found that the Chow statistic given by (4.8) has an approximate \(F-\text{Distribution}\) where the degree of freedom of the denominator depends upon the true variances.
Hence for specific values of these variances, Toyoda demonstrates how wrong it is to apply the Chow test in case of heteroskedastic variances.

Having posed the two questions above, we can proceed along two lines: the first is to find the approximate distribution of the Chow statistic (4.8) in case \(\mu \sim N \left(0,\Omega \right)\) and therefore show
how erroneous it is to use the Chow test in this case (this is not pursued in this book). The second route, and the more fruitful, is to derive the right test to perform for pooling the data in case \(\mu \sim N \left(0,\Omega \right)\) This is done in the next subsection.

\hypertarget{test-for-poolability-under-the-general-assumption}{%
\subsection{Test for Poolability under the General Assumption}\label{test-for-poolability-under-the-general-assumption}}

\[ u \sim N\left(0, \Omega\right)\]
\emph{Assumption} 4.2 \[ u \sim N\left(0, \Omega\right)\]

In case \(\Omega\) is known up to a scalar factor, the test statistic employed for the poolability of
the data would be simple to derive. All we need to do is transform our model (under both
the null and alternative hypotheses) such that the transformed disturbances have a variance of \(\sigma^2 I_{NT}\) , then apply the Chow test on the transformed model. The later step is legitimate because
the transformed disturbances have homoskedastic variances and the analysis of the previous
subsection applies in full. Given \$\Omega =\sigma\^{}2 \sum \$ , we premultiply the restricted model given in (4.2)
by \(\sum^{-1/2}\) and we call \(\sum^{-1/2}y=\dot{y}\) , \(\sum^{-1/2}Z=\dot{Z}\) and \(\sum^{-1/2} \mu=\dot{\mu}\) Hence

\begin{equation}
\dot{y}=\dot{Z}\delta + \dot{u}
\end{equation}

with \[E\left(\dot{u}\dot{u^{\prime}}\right) =\sum^{-1/2} E\left(u,u^{\prime}\right) \sum^{-1/2  \prime} =\sigma^2 I_{NT} \].
Similarly, we premultiply the unrestricted model
given in (4.3) by \(\sum^{-1/2}\) and we call \(\sum^{-1/2} Z^*=Z^*\).
Therefore

\begin{equation}
\dot{y}=\dot{Z}^{*} \delta ^{*} + \dot{u}
\end{equation}

with \(E\left(\dot{u}\dot{u}^{\prime}\right)=\sigma^2 I_{NT}\) .

At this stage, we can test \(H_0:\delta_i =\delta\) for every \(i=1,2,\ldots, N\) , simply by using the Chow statistic, only nowon the transformed models (4.9) and (4.10) since they satisfy assumption 4.1
of homoskedasticity of the normal disturbances. Note that \[\dot{Z}=\dot{Z^*}I^* \] , which is simply obtained
from \$Z=Z\textsuperscript{* I}* \$ by premultiplying by \(\sum^{-1/2}\).

Defining \[\dot{M}=I_{NT}-\dot{Z}\left(\dot{Z^{\prime}}\dot{Z} \right)^{-1} \dot{Z^{\prime}}   \] and \[\dot{M^*}=I_{NT}-\dot{Z^*}\left(\dot{Z^{* \prime}}\dot{Z^*} \right)^{-1} \dot{Z^{* \prime}}   \] it is easy to show that \(\dot{M}\) and \(\dot{M^*}\) are both symmetric, idempotent and such that \[\dot{M} \dot{M^*}=\dot{M^*}  \] Once again the conditions for lemma 2.2 of Fisher (1970) are satisfied, and the test statistic

\begin{equation}
\dot{F}_{obs}=\frac{\left(\dot{e}^{\prime} \dot{e}-\dot{e}^{* \prime}    \dot{e}^* \right)  /  \left(\operatorname{tr}\left(\dot{M}\right)-\operatorname{tr}\left(\dot{M^*}  \right) \right)  } 
{\dot{e}^{* \prime}    \dot{e}^* / \operatorname{tr}\left( \dot{M^*} \right) } 
\sim
F \left(\left( N-1 \right)K^{\prime} , N \left( T- K^{\prime} \right)          \right)
\end{equation}

\[
\begin{aligned}
\text{where  } \dot{e}=\dot{y}-\dot{Z} \widehat{\dot{\delta}}_{OLS}  
 \text{ and } \widehat{\dot{\delta}}_{OLS} =\left(\dot{Z^{\prime}\dot{Z}} \right)^{-1} \dot{Z^{\prime}} \dot{y}  \text{ implying that } \dot{e}=\dot{M}\dot{y}=\dot{M}\dot{u} \text{.   Similarly,}   \dot{e^*}= \\ \dot{y}-\dot{Z^*}\widehat{\dot{\delta}_{OLS}^*} \text{ and } \widehat{\dot{\delta}_{OLS}^*}=\left(\dot{Z^{* \prime}} \dot{Z} \right)^{-1} \dot{Z^{* \prime}} \dot{y} \text{ implying that }  \dot{e^*}=\dot{M^*}\dot{y}= \dot{M^*} \dot{u} \text{. Using the fact that } \\ \dot{M} \text{ and } \dot{M^*} \text{ are symmetric and idempotent, we can rewrite (4.11) as } 
 \end{aligned}
 \]

\[
\dot{F}_{obs}=  \frac{\left(\dot{y}^{\prime}\dot{M}\dot{y}-\dot{y}^{\prime}\dot{M^*} \dot{y} \right) / \left(N-1\right) K^{\prime} } 
 {\dot{y}^{\prime}\dot{M}\dot{y} / N \left( T-K^{\prime} \right)    }\]

\begin{equation}
 \dot{F}_{obs}=\frac{   \left(y^{\prime} \sum^{-1/2}\dot{M} \sum^{-1/2}y -\sum^{-1/2}\dot{M^*} \sum^{-1/2}y \right) / \left(N-1\right) K^{\prime}  }
{ \sum^{-1/2}\dot{M^*} \sum^{-1/2}y  / N \left(T-K^{\prime} \right)  }
\end{equation}

But

\[ \dot{M}=I_{NT}-\sum^{-1/2} Z\left(Z^{\prime } \sum^{-1} Z \right)^{-1} Z^{\prime} \sum^{-1/2^{\prime}} \]
And

\[ \dot{M^*}=I_{NT}-\sum^{-1/2} Z^{*}\left(Z^{*} \sum^{-1} Z \right)^{-1} Z^{* \prime} \sum^{-1/2^{\prime}} \]
so that
\[\sum^{-1/2}\dot{M}\sum_{-1/2} =\sum^{-1}-\sum^{-1} Z \left(Z^{\prime}\sum^{-1}Z  \right)^{-1} Z^{\prime} \]

and

\[\sum^{-1/2}\dot{M^*}\sum_{-1/2} =\sum^{-1}-\sum^{-1} Z^* \left(Z^{*\prime}\sum^{-1}Z^*  \right)^{-1} Z^{*\prime} \sum^{-1} \]
Hence we can write (4.12) in the form

\hypertarget{tests-for-individual-and-time-effects}{%
\section{TESTS FOR INDIVIDUAL AND TIME EFFECTS}\label{tests-for-individual-and-time-effects}}

\hypertarget{hausmans-specification-test}{%
\section{HAUSMAN'S SPECIFICATION TEST}\label{hausmans-specification-test}}

\hypertarget{methods}{%
\chapter{Methods}\label{methods}}

We describe our methods in this chapter.

Les données de panel, ou données longitudinales possèdent les deux dimensions précédentes (individuelle et temporelle). En effet, il est souvent intéressant d'identifier l'effet associé à chaque individu (un effet qui ne varie pas dans le temps, mais qui varie d'un individu à un autre). Cet effet peut être fixe ou aléatoire.

Par conséquent, le modèle en données de panel s'écrit comme un modèle à double indice qui prend la forme suivante :

\[ Y_{it}= \alpha_i\sum_{k}\beta_{ki}x_{ki}+ \epsilon_{it} \]

avec
\[ i:1 \rightarrow N \]\\
et
\[ t:1 \rightarrow T \]

La double dimension qu'offrent les données de panel est un atout majeur. En effet, si les données en séries temporelles permettent d'étudier l'évolution des relations dans le temps, elles ne permettent pas de contrôler l'hétérogénéité entre les individus. A l'inverse, les données en coupes transversales permettent d'analyser l'hétérogénéité entre les individus mais elles ne peuvent pas tenir compte des comportements dynamiques, puisque la dimension temporelle est exclue du champ d'analyse.

Ainsi, en utilisant des données de panel, on pourra exploiter les deux sources de variation de l'information statistique :
- Temporelle où variabilité intra-individuelle (within)
- et individuelle ou variabilité inter-individuelle (Between).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.3.5     v purrr   0.3.4
## v tibble  3.1.4     v dplyr   1.0.7
## v tidyr   1.1.3     v stringr 1.4.0
## v readr   2.0.1     v forcats 0.5.1
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(stargazer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Please cite as:
\end{verbatim}

\begin{verbatim}
##  Hlavac, Marek (2018). stargazer: Well-Formatted Regression and Summary Statistics Tables.
\end{verbatim}

\begin{verbatim}
##  R package version 5.2.2. https://CRAN.R-project.org/package=stargazer
\end{verbatim}

\hypertarget{analyses}{%
\chapter{Analyses}\label{analyses}}

Nous faisons \emph{application} des méthodes présentées dans le chapitre précédant pour l'analyse des données de pannel

Avant de passefr à la modélisation, nous ferons une description de nos variables d'interet d'une manière statique : nos prédicteurs et la variables réponses

\hypertarget{netoyage-de-la-base-des-donnuxe9es}{%
\section{Netoyage de la base des données}\label{netoyage-de-la-base-des-donnuxe9es}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\NormalTok{opts\_chunk}\SpecialCharTok{$}\FunctionTok{set}\NormalTok{(}\AttributeTok{echo =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{knitr}\SpecialCharTok{::}\NormalTok{opts\_chunk}\SpecialCharTok{$}\FunctionTok{set}\NormalTok{(}\AttributeTok{warning =}  \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Aperçue globale des données

\begin{table}

\caption{\label{tab:unnamed-chunk-3}Echantillon de la base des données}
\centering
\begin{tabular}[t]{r|l|r|l|r|r}
\hline
N° & Country/destination & Year & Goods & Weight & Taxe\\
\hline
1 & AFRIQUE DU SUD & 2011 & GRUES SUR PNEUMATIQUE & 13500 & 0\\
\hline
2 & AFRIQUE DU SUD & 2011 & CAMION FAMIL & 12000 & 0\\
\hline
3 & AFRIQUE DU SUD & 2011 & CAMION SOMUL & 24000 & 0\\
\hline
4 & AFRIQUE DU SUD & 2013 & Café vert arabica k4 & 183 & 0\\
\hline
5 & AFRIQUE DU SUD & 2013 & Café vert arabica k4 & 19520 & 264771\\
\hline
6 & AFRIQUE DU SUD & 2013 & Café vert arabica k4 & 19520 & 272817\\
\hline
7 & AFRIQUE DU SUD & 2013 & Café vert arabica k4 & 19520 & 283220\\
\hline
8 & AFRIQUE DU SUD & 2013 & Café vert arabica k4 & 19520 & 264142\\
\hline
9 & AFRIQUE DU SUD & 2013 & CAMION & 24000 & 0\\
\hline
10 & AFRIQUE DU SUD & 2017 & Instruments et appareils du n°90.15 & 654 & 0\\
\hline
\end{tabular}
\end{table}

Voici la structure de la base des données

La variables \textbf{Goods } a 740 modalités. En observant de près les modalités, on trouve que ces modalités sont rédondantes.Pour cela, il faudra une récodification des cettes variales.

Ainsi, donc les modalités representant la même marchandise seront groupées ensemble , pour des raisons de simplification.

Usage de tm et Stringr pour manipuler les chaines des caractères

\begin{verbatim}
##  [1] "Autres Marchandises"                      
##  [2] "Bois"                                     
##  [3] "Machines et appareils domestique"         
##  [4] "Médicaments et plantes médécinales"       
##  [5] "Poissaons, viande et oeufs"               
##  [6] "Matériels de construction"                
##  [7] "Materiel Informatique et Electroniques"   
##  [8] "Véhicules,camions,Motos et acc"           
##  [9] "Vetements,tissus et acc et chaussure"     
## [10] "boissons, bières et limonades"            
## [11] "Machine us Ingsutriel"                    
## [12] "Article Menange et Campement"             
## [13] "sacs, sachetsn emballages"                
## [14] "Papiers et fournitures de bureaux"        
## [15] "Produits alimentaires,prep et huiles"     
## [16] "caféarabica"                              
## [17] "Minérais et dérivés"                      
## [18] "engins et tracteurs"                      
## [19] "Cigarette et papier cigarettes et tabac"  
## [20] "constructionprefabriquees"                
## [21] "cadreset conteneurs"                      
## [22] "Pièces de Réchange appareils"             
## [23] "Générateurs,baterie et piles"             
## [24] "etuis en plastique ou textile"            
## [25] "Pétrole et dérivées et huile de graissage"
## [26] "boissons, bières,liqueurs et limonades"   
## [27] "produits beaute"                          
## [28] "peauxdes betes"
\end{verbatim}

netoyyage de la variable country\_desti qui est un facteur dans le quel nous retrouvons les niveaux rédondants (sur l'identifiant des pays)

Dans la base des données il y a des entreprises que l'on a enregistré à la place des pays. ces genre des cas ont été traité par remplacement avec le \emph{NA} pour \textbf{Not Available} et ces dernier on été élagués de la base des données, car nous avions jugé qu' aucune méthode d'imputation n'est applicable pour ce genre de situation. Nous avions fait la même chose pour les variables telles que \textbf{Les marchandises}.

\textbf{Nouvelle base de données pour les analyses}

Regroupement des variables pour la synthèse pour rendre la base des données simple à exploiter, éliminer les NA dans les observations telsque les pays et les valeurs pour les marchandises et les taxes.

\begin{table}

\caption{\label{tab:unnamed-chunk-40}Table de corrélation entre les variables quantitatives}
\centering
\begin{tabular}[t]{l|l|r}
\hline
var1 & var2 & coef\_corr\\
\hline
Weight & Year & -0.1727414\\
\hline
Taxe & Year & -0.1965648\\
\hline
Year & Weight & -0.1727414\\
\hline
Taxe & Weight & 0.6699457\\
\hline
Year & Taxe & -0.1965648\\
\hline
Weight & Taxe & 0.6699457\\
\hline
\end{tabular}
\end{table}

\hypertarget{modele-avec-les-pays-comme-individus}{%
\chapter{Modele avec les pays comme individus}\label{modele-avec-les-pays-comme-individus}}

\hypertarget{agregation-des-donnuxe9es-avec-la-muxe9thode-reduce}{%
\section{Agregation des données avec la méthode reduce}\label{agregation-des-donnuxe9es-avec-la-muxe9thode-reduce}}

\hypertarget{analyse-descriptive-des-varariales}{%
\section{Analyse descriptive des Varariales}\label{analyse-descriptive-des-varariales}}

Conversion des données en modèle des panels des données

\begin{verbatim}
##  [1] "AFRIQUE DU SUD"                          
##  [2] "ALGERIE"                                 
##  [3] "ALLEMAGNE"                               
##  [4] "AMERIQUE LATINE"                         
##  [5] "GRANDE BRATAGNE"                         
##  [6] "ANGOLA"                                  
##  [7] "ARABIE"                                  
##  [8] "ASIE"                                    
##  [9] "AUSTRALIE"                               
## [10] "BELGIQUE"                                
## [11] "BURUNDI"                                 
## [12] "CANADA"                                  
## [13] "CHINE"                                   
## [14] "CHYPRE"                                  
## [15] "CONGO BRAZA"                             
## [16] "REP TCHEQUE"                             
## [17] "NA"                                      
## [18] "EMIRATES ARABES UNIES"                   
## [19] "ESPAGNE"                                 
## [20] "FRANCE"                                  
## [21] "GABON"                                   
## [22] "GRECE"                                   
## [23] "HONG KONG"                               
## [24] "ILE MAURICE"                             
## [25] "INDE"                                    
## [26] "ITALIE"                                  
## [27] "JAPON"                                   
## [28] "KENYA"                                   
## [29] "KP - Corée, République Populaire démocra"
## [30] "LUXEMBOURG"                              
## [31] "MALAISIE"                                
## [32] "MAROC"                                   
## [33] "NERLAND"                                 
## [34] "PAYS BAS"                                
## [35] "NIGERIA"                                 
## [36] "NOUVELLE ZELANDE"                        
## [37] "OUGANDA"                                 
## [38] "PANAMA"                                  
## [39] "PHILLIPINE"                              
## [40] "POLOGNE"                                 
## [41] "PORTUGAL"                                
## [42] "ROYAUME UNI"                             
## [43] "RDC"                                     
## [44] "USA"                                     
## [45] "RWANDA"                                  
## [46] "SINGAPOUR"                               
## [47] "SUISSE"                                  
## [48] "SENEGAL"                                 
## [49] "SOMALIE"                                 
## [50] "SOUDAN"                                  
## [51] "SUD SOUDAN"                              
## [52] "SUEDE"                                   
## [53] "Swaziland"                               
## [54] "TANZANIE"                                
## [55] "TCHAD"                                   
## [56] "THAILANDE"                               
## [57] "UNION EUROPEENNE"                        
## [58] "ZAMBIE"
\end{verbatim}

\hypertarget{overall-variations}{%
\section{Overall Variations}\label{overall-variations}}

\begin{verbatim}
## 
## ====================================================================================
## Statistic  N    St. Dev.         Min        Pctl(25)      Pctl(75)         Max      
## ------------------------------------------------------------------------------------
## Taxes     228 24,567,143.00 -8,268,474.00 -8,268,474.00 -5,225,015.00 153,754,050.00
## Weight    228  407,973.40    -218,369.60   -196,559.50    -7,893.40    2,883,127.00 
## ------------------------------------------------------------------------------------
\end{verbatim}

L'écart-type des taxes pour les individus à travars le temps est 24,567,143.00 et celle des poids des marchandises est de 407,973.40 Kg .

\hypertarget{between-variations}{%
\section{Between Variations}\label{between-variations}}

\begin{verbatim}
## Adding missing grouping variables: `Destination_Country`
\end{verbatim}

\begin{verbatim}
## 
## ==========================================================================
## Statistic N      Mean       St. Dev.   Min Pctl(25)  Pctl(75)      Max    
## --------------------------------------------------------------------------
## Taxes     58 4,215,140.00 9,499,457.00  0     0     3,345,864.0 47,724,880
## Weight    58  132,331.80   196,253.90  100  19,665   120,394.6   940,804  
## --------------------------------------------------------------------------
\end{verbatim}

De ce tableau, on peut lire que:

\begin{itemize}
\tightlist
\item
  Les taxes varient de varient de 4,215,140.00 en moyenne d'un individu à un autre
\item
  Les poids des marchandises varient de 132,331.80 dollars d'un pays à un autre.
\end{itemize}

\hypertarget{within-variations}{%
\section{Within variations}\label{within-variations}}

\begin{verbatim}
## Adding missing grouping variables: `Destination_Country`
\end{verbatim}

\begin{verbatim}
## `mutate_all()` ignored the following grouping variables:
## Column `Destination_Country`
## Use `mutate_at(df, vars(-group_cols()), myoperation)` to silence the message.
\end{verbatim}

\begin{verbatim}
## 
## ==========================================================================
## Statistic  N    St. Dev.        Min       Pctl(25)   Pctl(75)      Max    
## --------------------------------------------------------------------------
## Taxes     228 20,714,497.00 -47,724,880 -3,291,776.0 175,658.1 133,691,390
## Weight    228  322,405.60    -870,261    -63,771.4   29,042.9   2,624,477 
## --------------------------------------------------------------------------
\end{verbatim}

De ce tableau, on peut lire que :

\begin{itemize}
\tightlist
\item
  L'écart moyen des taxes dans un pays, d'une année à une autre est de 20,714,497.00 dollars.
\item
  L'écart moyen des poids des marchandises est de 322,405.60 kg d'une année à une autre, pour un pays.
\end{itemize}

\hypertarget{moduxe9lisation}{%
\section{Modélisation}\label{moduxe9lisation}}

Modèle à polaire, considérant que le modèle est le même pour tous les pays. ce la suppose l'absence des éffets aléatoire et des éffets aléatoires.

\begin{verbatim}
## Pooling Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = "pooling")
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -76127299  -3525554    -38253         0    822609 135485918 
## 
## Coefficients:
##                Estimate  Std. Error t-value Pr(>|t|)    
## (Intercept) -8.7251e+05  1.3302e+06 -0.6559   0.5125    
## Weight       4.1859e+01  2.8796e+00 14.5367   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    1.37e+17
## Residual Sum of Squares: 7.0803e+16
## R-Squared:      0.48321
## Adj. R-Squared: 0.48092
## F-statistic: 211.315 on 1 and 226 DF, p-value: < 2.22e-16
\end{verbatim}

Le modèle s'écrit:
\[Y= 4.1859e^{01} X - 8.7251e^{05}  \]
Avec:

\begin{itemize}
\tightlist
\item
  Y : Les taxes recoltées pour les différentes marchandises dans tout les pays
\item
  X : Le poids globales des toutes les marchandises ayant traversé la douane pour chaque période concernant notre étude, et pour chaque individus
\end{itemize}

Notons que, pour ce type de panel, nos individus sont les pays et le temps est mésuré en année , à partir de l'année 2010 jusqu'en 2020.

La variable poids, dans les données des bases a été agrées, en calculant la somme de tous les poids pour pour les différentes marchandises n pour une année
Ainsi, nous avions:

\[ P_{i.t}=\sum_{j=1}^{n} P{i..} \]
i indiquant les marchandises , de la prémière à la n-ième marchandise. Ainsi donc, nous avions somme les poids de chaque marchandise pour trouver le poids annuel des marchanides ayant traversé la douane d'un pays. Il en est de même pour les taxes.

Le coefficient associé au poids des marchandises est significatif car le p-value associé est inférieur à 0,05. Tansdis que le terme indépendant n'est pas significativement différent de 0 vu que le p-value associé est supérieur au seuil.

Ainsi donc, quand le poids augmente d'une unité, les taxes augmentent de 4,185 unités, pour tous les pays, et à travers le temps. Cette augmentation est significativement différent de 0.

En testant la significativité globale du modèle, nous utilisant le Langranhe Multiplier test.

\begin{verbatim}
## 
##  Lagrange Multiplier Test - (Honda) for unbalanced panels
## 
## data:  Taxes ~ Weight
## normal = 0.89501, p-value = 0.1854
## alternative hypothesis: significant effects
\end{verbatim}

Le test pour le modèle \texttt{pooling} est non significatif vu que le p-value associé au test est supérieur au seuil de 5\% (0,05). Ainsi donc, nous adoptons l'hypothèse nulle du test selon laquelle le modèle polaire n'est pas significatif.

Modele à éffet fixes.
Nous produisons ce modèle en utilisant la methode \texttt{Within} qui traduit les variations de la variables dependante en fonction des variables dépendantes, mais pour un individus à travers le temps.

\begin{verbatim}
## Oneway (individual) effect Within Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, effect = "individual", 
##     model = "within")
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -69551626  -1715042         0         0   1537006 114103679 
## 
## Coefficients:
##        Estimate Std. Error t-value  Pr(>|t|)    
## Weight  39.6087     3.8914  10.178 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    9.7404e+16
## Residual Sum of Squares: 6.0386e+16
## R-Squared:      0.38005
## Adj. R-Squared: 0.16728
## F-statistic: 103.601 on 1 and 169 DF, p-value: < 2.22e-16
\end{verbatim}

ici, nous modélisons les éffets individuels.
Le coefficient des taxes signifie, que les pays augmentaient leurs importations d'une unitées, chacune, nous aurions une augmentation de 39,6087 dollars pour ce pays.

EXtraction des effets fixes
Ce sont les effects individuels spécifiques pour chaque pays.

On remarque que:

\begin{itemize}
\tightlist
\item
  La chine a 21758301 dollars de taxe de plus que la moyenne des taxes de tous les pays, et ce, d'une manière significative.
\item
  HONG KONG 21758301 dollars de plus que la moyenne des pays, et ce, significativement.
\item
  Les effets individuels de tous les autres pays ne sont pas significativement différents de 0 vu que les p-values associées, respectivement pour chaque pays sont de loin supérieur au seuil chacune.
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-51}Effets individuels }
\centering
\begin{tabular}[t]{l|r|r|r|r}
\hline
  & Estimate & Std. Error & t-value & Pr(>|t|)\\
\hline
\cellcolor{gray!6}{AFRIQUE DU SUD} & \cellcolor{gray!6}{-2984326.03} & \cellcolor{gray!6}{8460861} & \cellcolor{gray!6}{-0.3527213} & \cellcolor{gray!6}{0.7247369}\\
\hline
ALGERIE & -1165271.62 & 18903294 & -0.0616438 & 0.9509193\\
\hline
\cellcolor{gray!6}{ALLEMAGNE} & \cellcolor{gray!6}{-1632580.61} & \cellcolor{gray!6}{7723181} & \cellcolor{gray!6}{-0.2113871} & \cellcolor{gray!6}{0.8328399}\\
\hline
AMERIQUE LATINE & 2202439.71 & 13368089 & 0.1647535 & 0.8693349\\
\hline
\cellcolor{gray!6}{GRANDE BRATAGNE} & \cellcolor{gray!6}{-3470934.54} & \cellcolor{gray!6}{6056452} & \cellcolor{gray!6}{-0.5730970} & \cellcolor{gray!6}{0.5673408}\\
\hline
ANGOLA & -15589167.27 & 18967690 & -0.8218801 & 0.4123031\\
\hline
\cellcolor{gray!6}{ARABIE} & \cellcolor{gray!6}{-142028.25} & \cellcolor{gray!6}{18902837} & \cellcolor{gray!6}{-0.0075136} & \cellcolor{gray!6}{0.9940139}\\
\hline
ASIE & 38936.72 & 18902846 & 0.0020598 & 0.9983589\\
\hline
\cellcolor{gray!6}{AUSTRALIE} & \cellcolor{gray!6}{285990.29} & \cellcolor{gray!6}{18902686} & \cellcolor{gray!6}{0.0151296} & \cellcolor{gray!6}{0.9879466}\\
\hline
BELGIQUE & 3926237.34 & 7009603 & 0.5601226 & 0.5761375\\
\hline
\cellcolor{gray!6}{BURUNDI} & \cellcolor{gray!6}{-315018.56} & \cellcolor{gray!6}{6301266} & \cellcolor{gray!6}{-0.0499929} & \cellcolor{gray!6}{0.9601871}\\
\hline
CANADA & 6630399.23 & 10924084 & 0.6069524 & 0.5446970\\
\hline
\cellcolor{gray!6}{CHINE} & \cellcolor{gray!6}{21758300.68} & \cellcolor{gray!6}{6513971} & \cellcolor{gray!6}{3.3402513} & \cellcolor{gray!6}{0.0010301}\\
\hline
CHYPRE & 2015623.85 & 18902888 & 0.1066305 & 0.9152086\\
\hline
\cellcolor{gray!6}{CONGO BRAZA} & \cellcolor{gray!6}{355028.22} & \cellcolor{gray!6}{18902684} & \cellcolor{gray!6}{0.0187819} & \cellcolor{gray!6}{0.9850373}\\
\hline
REP TCHEQUE & 1577815.74 & 18903000 & 0.0834691 & 0.9335774\\
\hline
\cellcolor{gray!6}{NA} & \cellcolor{gray!6}{-1030865.82} & \cellcolor{gray!6}{13367444} & \cellcolor{gray!6}{-0.0771176} & \cellcolor{gray!6}{0.9386212}\\
\hline
EMIRATES ARABES UNIES & 1635013.00 & 7146910 & 0.2287720 & 0.8193227\\
\hline
\cellcolor{gray!6}{ESPAGNE} & \cellcolor{gray!6}{358452.36} & \cellcolor{gray!6}{9451857} & \cellcolor{gray!6}{0.0379240} & \cellcolor{gray!6}{0.9697930}\\
\hline
FRANCE & -3760302.34 & 6321394 & -0.5948533 & 0.5527371\\
\hline
\cellcolor{gray!6}{GABON} & \cellcolor{gray!6}{270146.82} & \cellcolor{gray!6}{18902687} & \cellcolor{gray!6}{0.0142915} & \cellcolor{gray!6}{0.9886143}\\
\hline
GRECE & -167122.77 & 13366412 & -0.0125032 & 0.9900389\\
\hline
\cellcolor{gray!6}{HONG KONG} & \cellcolor{gray!6}{14181338.15} & \cellcolor{gray!6}{6715252} & \cellcolor{gray!6}{2.1118103} & \cellcolor{gray!6}{0.0361728}\\
\hline
ILE MAURICE & -18631113.63 & 18994748 & -0.9808561 & 0.3280658\\
\hline
\cellcolor{gray!6}{INDE} & \cellcolor{gray!6}{2932397.32} & \cellcolor{gray!6}{9457208} & \cellcolor{gray!6}{0.3100701} & \cellcolor{gray!6}{0.7568897}\\
\hline
ITALIE & -3579816.54 & 13371879 & -0.2677123 & 0.7892472\\
\hline
\cellcolor{gray!6}{JAPON} & \cellcolor{gray!6}{-11074.78} & \cellcolor{gray!6}{10913538} & \cellcolor{gray!6}{-0.0010148} & \cellcolor{gray!6}{0.9991915}\\
\hline
KENYA & -367019.02 & 6683619 & -0.0549132 & 0.9562725\\
\hline
\cellcolor{gray!6}{KP - Corée, République Populaire démocra} & \cellcolor{gray!6}{218970.88} & \cellcolor{gray!6}{18902915} & \cellcolor{gray!6}{0.0115840} & \cellcolor{gray!6}{0.9907712}\\
\hline
LUXEMBOURG & 3908067.60 & 9453578 & 0.4133956 & 0.6798409\\
\hline
\cellcolor{gray!6}{MALAISIE} & \cellcolor{gray!6}{9323874.62} & \cellcolor{gray!6}{7990237} & \cellcolor{gray!6}{1.1669084} & \cellcolor{gray!6}{0.2448913}\\
\hline
MAROC & -3041138.54 & 13370444 & -0.2274523 & 0.8203470\\
\hline
\cellcolor{gray!6}{NERLAND} & \cellcolor{gray!6}{-1458943.80} & \cellcolor{gray!6}{18905086} & \cellcolor{gray!6}{-0.0771720} & \cellcolor{gray!6}{0.9385780}\\
\hline
PAYS BAS & -2135869.03 & 6707725 & -0.3184193 & 0.7505601\\
\hline
\cellcolor{gray!6}{NIGERIA} & \cellcolor{gray!6}{69469.46} & \cellcolor{gray!6}{13366251} & \cellcolor{gray!6}{0.0051974} & \cellcolor{gray!6}{0.9958592}\\
\hline
NOUVELLE ZELANDE & -964653.67 & 9452267 & -0.1020553 & 0.9188338\\
\hline
\cellcolor{gray!6}{OUGANDA} & \cellcolor{gray!6}{-9660163.23} & \cellcolor{gray!6}{6259154} & \cellcolor{gray!6}{-1.5433657} & \cellcolor{gray!6}{0.1246125}\\
\hline
PANAMA & 1902251.68 & 13367426 & 0.1423050 & 0.8870086\\
\hline
\cellcolor{gray!6}{PHILLIPINE} & \cellcolor{gray!6}{377090.25} & \cellcolor{gray!6}{18902684} & \cellcolor{gray!6}{0.0199490} & \cellcolor{gray!6}{0.9841076}\\
\hline
POLOGNE & -189313.83 & 13366333 & -0.0141635 & 0.9887163\\
\hline
\cellcolor{gray!6}{PORTUGAL} & \cellcolor{gray!6}{-1520165.36} & \cellcolor{gray!6}{9453188} & \cellcolor{gray!6}{-0.1608098} & \cellcolor{gray!6}{0.8724353}\\
\hline
ROYAUME UNI & -1520165.36 & 13367521 & -0.1137208 & 0.9095941\\
\hline
\cellcolor{gray!6}{RDC} & \cellcolor{gray!6}{-10887866.60} & \cellcolor{gray!6}{8575838} & \cellcolor{gray!6}{-1.2695980} & \cellcolor{gray!6}{0.2059733}\\
\hline
USA & -3702024.25 & 7157453 & -0.5172265 & 0.6056744\\
\hline
\cellcolor{gray!6}{RWANDA} & \cellcolor{gray!6}{-2745202.66} & \cellcolor{gray!6}{6429503} & \cellcolor{gray!6}{-0.4269697} & \cellcolor{gray!6}{0.6699449}\\
\hline
SINGAPOUR & -1271537.64 & 7722149 & -0.1646611 & 0.8694075\\
\hline
\cellcolor{gray!6}{SUISSE} & \cellcolor{gray!6}{-6428958.73} & \cellcolor{gray!6}{6084800} & \cellcolor{gray!6}{-1.0565604} & \cellcolor{gray!6}{0.2922202}\\
\hline
SENEGAL & -164360.36 & 18902760 & -0.0086950 & 0.9930727\\
\hline
\cellcolor{gray!6}{SOMALIE} & \cellcolor{gray!6}{182031.20} & \cellcolor{gray!6}{18902817} & \cellcolor{gray!6}{0.0096298} & \cellcolor{gray!6}{0.9923280}\\
\hline
SOUDAN & 370990.51 & 18902684 & 0.0196263 & 0.9843646\\
\hline
\cellcolor{gray!6}{SUD SOUDAN} & \cellcolor{gray!6}{-3003470.69} & \cellcolor{gray!6}{18905608} & \cellcolor{gray!6}{-0.1588667} & \cellcolor{gray!6}{0.8739636}\\
\hline
SUEDE & -1129587.86 & 13367521 & -0.0845024 & 0.9327570\\
\hline
\cellcolor{gray!6}{Swaziland} & \cellcolor{gray!6}{-975538.34} & \cellcolor{gray!6}{7726665} & \cellcolor{gray!6}{-0.1262561} & \cellcolor{gray!6}{0.8996793}\\
\hline
TANZANIE & -373840.11 & 6683928 & -0.0559312 & 0.9554627\\
\hline
\cellcolor{gray!6}{TCHAD} & \cellcolor{gray!6}{127674.41} & \cellcolor{gray!6}{18902700} & \cellcolor{gray!6}{0.0067543} & \cellcolor{gray!6}{0.9946189}\\
\hline
THAILANDE & -6581130.20 & 9554902 & -0.6887700 & 0.4919125\\
\hline
\cellcolor{gray!6}{UNION EUROPEENNE} & \cellcolor{gray!6}{86341.53} & \cellcolor{gray!6}{18902832} & \cellcolor{gray!6}{0.0045677} & \cellcolor{gray!6}{0.9963609}\\
\hline
ZAMBIE & -1561477.21 & 18903647 & -0.0826019 & 0.9342658\\
\hline
\end{tabular}
\end{table}

Le modèle à éffets aléatoire

\begin{verbatim}
## Oneway (individual) effect Between Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = "between")
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## Observations used in estimation: 58
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -17710356  -1366186    300948         0    907729  22825793 
## 
## Coefficients:
##                Estimate  Std. Error t-value  Pr(>|t|)    
## (Intercept) -9.2150e+05  9.0924e+05 -1.0135    0.3152    
## Weight       3.8816e+01  3.8643e+00 10.0449 3.886e-14 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    5.1437e+15
## Residual Sum of Squares: 1.8358e+15
## R-Squared:      0.64309
## Adj. R-Squared: 0.63671
## F-statistic: 100.9 on 1 and 56 DF, p-value: 3.886e-14
\end{verbatim}

Ainsi donc, le modèle within s'écrit:

\[ Y = + 3.8816e^{01}X - 9.2150e^{05} \]
Pour fragmentation d'une unité pour le poids des marchandises, on observe une augmentation des taxes de 38,81 unitées d'un pays à un autre. cela signifie que, si un pays à importé un 1Kg plus qu'un autre, nous observerons une différence de 38,82 dollars pour les taxes.

\begin{verbatim}
## 
##  F test for individual effects
## 
## data:  Taxes ~ Weight
## F = 0.51147, df1 = 57, df2 = 169, p-value = 0.998
## alternative hypothesis: significant effects
\end{verbatim}

Le choix du modèle en utlisant le test d'Hausman

Ce test consiste à comparer les coefficients de ce s deux modèles, pour en fint chhoisir le modèle qui est consistant entre les modèle à éffet individuel et le modèle à éffet aléatoire.

\begin{verbatim}
## 
##  Hausman Test
## 
## data:  Taxes ~ Weight
## chisq = 0.020872, df = 1, p-value = 0.8851
## alternative hypothesis: one model is inconsistent
\end{verbatim}

Ce test étant non qignificatif, c'est-à-dire , nous adoptons l'hypothèse nulle : les coefficients du modèle à éffet fixe et ceux du modèle à éffet aléatoire ne sont pas significativement différents. Ainsi donc, nous utiliserons les modèles à éffets aléatoire car celui-ci est efficien (éficace).

Effet aleatoire

\begin{verbatim}
## Oneway (individual) effect Random Effect Model 
##    (Wallace-Hussain's transformation)
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = "random", 
##     random.method = "walhus")
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Effects:
##                     var   std.dev share
## idiosyncratic 3.578e+14 1.891e+07     1
## individual    0.000e+00 0.000e+00     0
## theta:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0       0       0       0       0       0 
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -76127299  -3525554    -38253         0    822609 135485918 
## 
## Coefficients:
##                Estimate  Std. Error z-value Pr(>|z|)    
## (Intercept) -8.7251e+05  1.3302e+06 -0.6559   0.5119    
## Weight       4.1859e+01  2.8796e+00 14.5367   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    1.37e+17
## Residual Sum of Squares: 7.0803e+16
## R-Squared:      0.48321
## Adj. R-Squared: 0.48092
## Chisq: 211.315 on 1 DF, p-value: < 2.22e-16
\end{verbatim}

\hypertarget{moduxe8le-avec-les-marchandises-comme-individus}{%
\chapter{Modèle avec les marchandises comme individus}\label{moduxe8le-avec-les-marchandises-comme-individus}}

Modèle à polaire, considérant les deux effets

\begin{verbatim}
## Pooling Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = "pooling")
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -76127299  -3525554    -38253         0    822609 135485918 
## 
## Coefficients:
##                Estimate  Std. Error t-value Pr(>|t|)    
## (Intercept) -8.7251e+05  1.3302e+06 -0.6559   0.5125    
## Weight       4.1859e+01  2.8796e+00 14.5367   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    1.37e+17
## Residual Sum of Squares: 7.0803e+16
## R-Squared:      0.48321
## Adj. R-Squared: 0.48092
## F-statistic: 211.315 on 1 and 226 DF, p-value: < 2.22e-16
\end{verbatim}

Modele à éffet aléatoire

\begin{verbatim}
## Oneway (individual) effect Within Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, effect = "individual", 
##     model = "within")
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -69551626  -1715042         0         0   1537006 114103679 
## 
## Coefficients:
##        Estimate Std. Error t-value  Pr(>|t|)    
## Weight  39.6087     3.8914  10.178 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    9.7404e+16
## Residual Sum of Squares: 6.0386e+16
## R-Squared:      0.38005
## Adj. R-Squared: 0.16728
## F-statistic: 103.601 on 1 and 169 DF, p-value: < 2.22e-16
\end{verbatim}

l'expression du modèle est : \$ Y=39,6087 X\$

Ainsi donc, ce coefficient étant significatif, traduit que l'augmentation du poids des marchnise de une unité entrainte une augmentation des taxes perçues de 39,6087 dollars, pour la même marchandise

Le modèle à éffets aléatoire

\begin{verbatim}
## Oneway (individual) effect Between Model
## 
## Call:
## plm(formula = Taxes ~ Weight, data = p_DF_aggreg, model = "between")
## 
## Unbalanced Panel: n = 58, T = 1-10, N = 228
## Observations used in estimation: 58
## 
## Residuals:
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -17710356  -1366186    300948         0    907729  22825793 
## 
## Coefficients:
##                Estimate  Std. Error t-value  Pr(>|t|)    
## (Intercept) -9.2150e+05  9.0924e+05 -1.0135    0.3152    
## Weight       3.8816e+01  3.8643e+00 10.0449 3.886e-14 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    5.1437e+15
## Residual Sum of Squares: 1.8358e+15
## R-Squared:      0.64309
## Adj. R-Squared: 0.63671
## F-statistic: 100.9 on 1 and 56 DF, p-value: 3.886e-14
\end{verbatim}

Le modèle s'écrit de la manière suivante:

\[Y= 3.8816e^{01}X -9.2150e^{05}\]
Le coefficient associé au poids étant significatif, on trouve que: si une marchandise dépassait en poids une autre de 1Kg, les taxes perçues pour cette marchandises dépasseraient cette autre de 38,8 dollars.

Condidérant le R-Carré ajutsté, Ce modèle explique à 63,7\% les variations des taxes en fonction des poids des marchandises.

Pour arbitrer le choix entre le modèle à effet fixe et le modèle à éffet aléatoire, nous allons utiliser le test d'Hausman qui consite à comprer les coefficients de ces deux modèles

\begin{verbatim}
## # A tibble: 1 x 5
##   statistic p.value parameter method       alternative              
##       <dbl>   <dbl>     <int> <chr>        <chr>                    
## 1      9.03 0.00265         1 Hausman Test one model is inconsistent
\end{verbatim}

Le test d'Hausman étant significatif pour ces données, nous optons donc le modèle à éffet à éffet fixe pour estimer les taxes sachant que les individus sont les marchandises car celui-ci est consistant.

On suppose donc une variation significative entre les marchandises.

\hypertarget{conclusion}{%
\chapter{Conclusion}\label{conclusion}}

Dans ce document nous venons de modeliser les taxes perçues dans les différents pays sur les marchandises à leurs destinations. Le modèle a pour variable exogène les \textbf{taxes} et comme variable endogène \textbf{les poids des marchandises} .

Nous avions manipulé ces données de manière à en extraire deux bases pour les données de panel:

\begin{itemize}
\tightlist
\item
  une base des données dans laquelle les individus sont les pays.
  \emph{dans cette base, nous avions aggrégé les poids des tous les marchandises en une seul variable \texttt{weight} en faisant leur somme.il en est de même pour les variables taxes}
\item
  une base des données dans laquelle les individus sont les marchandises.
  *dans cette base, nous avions utlisé un format large de notre dataframe. nous avions agrégé la variable poids et la variable taille en faisant la sommes, pour chaque ligne, pour tous les pays.
\end{itemize}

La modélisation a donc consister à estimer :

\begin{itemize}
\tightlist
\item
  Le modèle \textbf{pooling}
\item
  Le modèle \textbf{within}
\item
  le modèle \textbf{between}
\end{itemize}

Pour chaque estimation, nous avions fait les test de spécification du modèle pour identifier , le quel de ces trois modèles sus indiqués represente au mieux nos données. Nous avions possédé au test de \textbf{Langrade Multiplier}, et au test d'\textbf{Hausman}.

  \bibliography{book.bib,packages.bib}

\end{document}
